// This file is generated

S_author_0 = [
"",
"Ancestry.com and The Church of Jesus Christ of Latter-day Saints",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Ancestry.com",
"Edmund West, comp.",
"Edmund West, comp.",
"Edmund West, comp.",
"",
"Heritage Consulting",
"Heritage World Family History Services",
"National Archives and Records Administration",
"National Cemetery Administration",
"",
"Yates Publishing"
]
Dwr.ScriptLoaded('dwr_db_S_author_0.js');
