// This file is generated

S_text_0 = [
"<p>\n<b>\nPublication information: \n</b>\nOnline publication - Provo, UT, USA: Ancestry.com.  Original data:  Family Tree files submitted by Ancestry members.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com and The Church of Jesus Christ of Latter-day Saints\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nOnline publication - Provo, UT, USA: Ancestry.com Operations Inc, 2007.Original data - Dobson, David. Scottish Quakers and Early America, 1650-1700. Baltimore, MD, USA: Genealogical Publishing Co., 1998.Original data: Dobson, David. Scottish Quakers and Ea\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nAncestry.com\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations, Inc.\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdmund West, comp.\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdmund West, comp.\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nEdmund West, comp.\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nHeritage Consulting\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nHeritage World Family History Services\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nNational Archives and Records Administration\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"<p>\n<b>\nAuthor: \n</b>\nNational Cemetery Administration\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>",
"",
"<p>\n<b>\nAuthor: \n</b>\nYates Publishing\n</p><p>\n<b>\nPublication information: \n</b>\nAncestry.com Operations Inc\n</p>"
]
Dwr.ScriptLoaded('dwr_db_S_text_0.js');
