// This file is generated

I_death_place_0 = [
"",
"",
"",
"",
", , , France",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"England",
"Wincanton, Somerset, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Soissons-sur-nacey, Burgandy, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kent, England",
"Gloucester, Essex, Massachusetts, United States",
"",
"",
"",
"Kincardineshire, Scotland",
"",
"",
"",
"",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"Cumberland, Cumberland, New Jersey, United States",
"",
"",
"",
"",
"",
"England",
"Berks County, Pennsylvania",
"",
"Richmond Palace, Richmond, Surrey, England",
"Cape May, New Jersey, USA",
"Devonshire, England",
"",
"Newark-on-Trent, Newark and Sherwood District, Nottinghamshire, England Cemetery: Worcester Cathedral Burial or Cremation Place: Worcester, City of Worcester, Worcestershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Wilmington, Kent, England",
"Wilmington, Kent, England",
"",
"Cape May, New Jersey, USA",
"",
"Norte dame, Rosen, Seine-Maritime France",
"",
"",
"",
", , England",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Oppenheim, , Rheinland-Pfalz, Germany",
"",
"",
"Upper Frederick Township, Montgomery, Pennsylvania",
"Tantallon Castle, North Berwick, East Lothian, Scotland",
"",
"",
"England",
"East Hampton, Suffolk, New York, United States",
"",
"Speldhurst, Kent, England",
"England",
"Gifford, East Lothian, Scotland",
"Ross Cromarty, Scotland",
"Melrose Abbey (buried in Paisley Priory)",
"Bampton (Devonshire) England, Church",
"",
"",
"Fyvie, Aberdeenshire, Scotland",
"SCOTLAND",
"",
"",
"",
"",
"",
"",
"",
"",
"Deborah NJ",
"",
"",
"Gloucester, Essex, Massachusetts, USA",
"Metz, Moselle, Lorraine, France",
"Burr Abbaye De St Vincent, Paris, Ile-De-France, France",
"Metz, Moselle, Alsace-Champagne-Ardenne-Lorraine, France",
"",
"Staffordshire, England",
"",
"",
"",
"Long Island City, Queens, New York, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Somme, Picardie, France",
"",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Ivrea, Torino, Piemonte, Italy",
"Bamberg Castle, Bamberg, Franken, Bayem, Germany",
"",
"",
"",
"",
"Arbuthnott, Kincardineshire, Scotland",
"",
"leys, kincardine, Scotland",
"",
"scotland",
"leys, kincardine, Scotland",
"Arbuthnott, Kincardineshire, Scotland",
"",
"Kilkenny, Ireland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Preston, Glocestershire, England",
"Philadelphia, Pennsylvania, USA",
"",
"",
"Yorktown, York, Virginia, United States",
"Fort Defiance, Happy Valley Wilkes, North Carolina, USA",
"Scotland Neck, Halifax, North Carolina, American Colonies",
"Aberdeenshire, Scotland",
"Lincolnshire, England",
"",
"East Hampton, Suffolk County, New York, United States of America",
"Lynn, Essex County. Massachusetts Bay Colony",
"swarkstone, Derbyshire, England",
"swarkstone, Derbyshire, England",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"",
"England",
"Trussville, Jefferson, Alabama, USA",
"",
"",
"",
"",
"",
"",
"",
"Voorhees, Camden, New Jersey, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia City, Philadelphia, Pennsylvania",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tufara, Campobasso, Molise, Italy",
"",
"",
"",
"Frederick, Montgomery, Pennsylvania, United States",
"England",
"Freehold, Monmouth, New Jersey, USA",
"Awliscombe, Devon, England",
"Somerset, Devon, England",
"Crediton, Devon, , England",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"ABERDEENSHIRE, SCOTLAND",
"",
"",
"Philadelphia, Philadelphia Co., PA",
"Winchester, City of Winchester, Hampshire, England",
"",
"Greenwich, Royal Borough of Greenwich, Greater London, England",
"Castle Dunbar, East Lothian, Scotland",
"Sussex, England",
"",
"Berks County, Pennsylvania, United States of America",
"",
"",
"England",
"",
"",
"",
"",
"",
"",
"",
"",
"Gloucester City, NJ",
"",
"",
"",
"",
"",
"",
"Gloucester City, NJ",
"",
"",
"",
"",
"",
"",
"",
"",
"France",
"France",
"",
"",
"",
"",
"",
"",
"Woodbury, Gloucester, New Jersey, United States",
"",
"",
"",
"",
"",
"",
"",
"Hedeby, Midtjylland, Denmark",
"Stratford, Fairfield, Connecticut, USA",
"Stratford, Fairfield County, Connecticut, USA",
"Yorktown, York County, Virginia, United States of America",
"Dennisville, Cape May, New Jersey",
"Dividing Creek, Cumberland, New Jersey, United States",
"Morris Twnsp, Washington County, Pa",
"Rockland, Berks, Pennsylvania",
"",
"",
"",
"",
"",
"",
"",
"Hampstead,Queens,New York,USA",
"Greenwich, Gloucester, New Jersey, United States",
"",
"England",
"Bolney, Sussex, England",
"Bolney, Sussex, England",
"Bolney, Sussex, England",
"Bolney, Sussex, , England",
"Awilscombe, Devon, England",
"",
"Bamberg Castle, Bamberg, Franken, Bayem, Germany",
"Haughton, Staffordshire, England",
"",
"",
"",
"Devon, England",
"Troyes, Departement de l'Aube, Champagne-Ardenne, France",
"St. Cray's, North Cray, Bromley, Kent, England",
"Dorset County, Eng.",
"Perth, Perthshire, , Scotland",
"hill, western, Australia",
"Kilmarnock, Ayrshire, Scotland",
"",
"Alnwick, Northumberland Unitary Authority, Northumberland, England",
"",
"Ayrshire, Scotland",
"",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dundonald, Ayrshire, Scotland",
"Birmensdorf, , Z\u00fcrich, Switzerland",
"",
"",
"",
"Germantown, Philadelphia, Pennsylvania, United States",
"",
"",
"East Nottingham, Chester, Pennsylvania, USA",
"Cecil, Maryland, United States",
"Little Britain, Lancaster, Pennsylvania, USA",
"",
"",
"",
"Rising Sun, Cecil, Maryland, USA",
"West Nottingham, Cecil, Maryland, USA",
"Nottingham, Chester, PA, Colonial America",
"Lancaster Co, Pennsylvania",
"Hall, Ontario, New York, USA",
"",
"",
"Chester, Pennsylvania, United States",
"",
"West Nottingham, Chester, PA, USA",
"",
"",
"Sundridge, Kent, England UK",
"St Dunstan and All Saints, Middlesex, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Clyst St George, Devon, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Halifax, West Riding, Yorkshire, England",
"England",
"Westtown, Chester, Pennsylvania, United States",
"",
"",
"Keynsham, Bath and North East Somerset Unitary Authority, Somerset, England",
"",
"",
"Hampshire, Shropshire, England",
"england",
"leys, kincardine, Scotland",
"",
"Sag Harbor, East Hampton Suffolk, NY, USA",
"scotland",
"",
"leys, kincardine, Scotland",
"leys, kincardine, Scotland",
"",
"",
"West Creek, Monmouth, New Jersey",
"",
"Virginia, United States",
"",
"",
"",
"",
"1661089, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Lurgan, Armagh, Ireland",
"Friends Grnd, Movraverty, Drumgorr, Ireland",
"",
"Northumberland, England",
"Monzievaird and Strowan, Perthshire, Scotland",
"",
"",
"Ravanusa, Agrigento, Sicilia, Italy",
"",
"",
"Kirkintilloch, Dunbartonshire, Scotland",
"Mesen, West Flanders, Belgium",
"Tarsus, Turkey",
"Meulan, Yvelines, \u00cele-de-France, France",
"",
"",
"Neithrop, Oxford, England",
"St Andrews,Dundee, Scotland.",
"",
"",
"Pennsylvania",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Crossing the pass at Brides-les-Bains, Rhone-Alpes, France",
"",
"murdered in Vermandois, Aisne, Picardie, France",
"",
"Auxerre, Yonne, Bourgogne, France",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"",
"",
"Ravanusa, Agrigento, Sicilia, Italy",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Pilesgrove, Salem County, New Jersey, United States of America",
"",
"Dividing Creek, NJ",
"",
"",
"",
"Long Island, Nassau, New York, United States",
"Ashford, Kent, England",
"Ashford, Kent, England",
"Hempstead, Queens, New York",
"Cheltenham, Gloucestershire, England",
"Pantfield Bulmer, Essex, England",
"",
"Thornbury, Chester, Pennsylvania, United States",
"",
"Carlisle, Cumbria, England",
"",
"",
"",
"Ravanusa, Civile, Agrigento, Sicilia, Italy",
"",
"",
"",
"Ravanusa, Agrigento, Sicilia, Italy",
"italy",
"Cherry Hill, Camden, New Jersey, USA",
"",
"Newport, Newport, Rhode Island",
"London, City of London, Greater London, England",
"England",
"Arnold, Nottinghamshire, England",
"",
"",
"",
"",
"",
"",
"",
"Halifax, Halifax, North Carolina, American Colonies",
"as a prisoner accused of witchcraft, Peel Castle, Isle of Man, England",
"Windsor, Hartford County, Connecticut Colony, USA",
"Donnyat, Somersetshire, England",
"Chester, Pennsylvania, United States",
", Chester, Pennsylvania, United States",
"Goshen, Chester, Pennsylvania",
"Goshen, Chester, Pennsylvania, United States",
"Up Holland, West Lancashire District, Lancashire, England",
"Kilmarnock, Renfrewshire, Scotland",
"Ochiltree Castle, Uphall, West-Lothian, Schotland",
"New Jersey, USA",
"",
"Jerusalem, Palestine",
"Reims, Marne, Champagne-Ardenne, France",
"",
"",
"",
"Badenoch, Inverness-shire, Scotland",
"Altyre, Morayshire, Scotland",
"Durham, Northumberland, England (killed by Northumbrians)",
"Altyre, Morayshire, Scotland",
"",
"Yarmouth, Barnstable, Massachusetts, USA.",
"",
"",
"Cheshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Berkhamsted, Dacorum Borough, Hertfordshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Gatinais, Loire, Orleanais/Centre france",
"",
"Fleury-Ouche-Anjou, Pay-de-la-Loire, France",
"Macon, Saone-et-Loire, Bourgogne, France",
"Salins, Seine-et-Marne, \u00cele-de-France, France",
"Newham Manor, Plympton St Mary, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Unknown",
"England",
"Brunswick Co., Virginia, United States",
"England",
"Edgecombe County, North Carolina, USA",
"York, Virginia",
"York, Virginia, United States",
"Normandy , France",
"Jedburgh, Roxburghshire, Scotland",
"",
"",
"",
"Cape May, Cape May, New Jersey, United States",
"Essex, Virginia, United States",
"",
"Woodbridge, Middlesex County, New Jersey Colony",
"Woodbridge, Middlesex, New Jersey, United States",
"Sandwich, Barnstable, Massachusetts, British Colony",
"Sandwich, Barnstable, Massachusetts, United States",
"",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Cape May, Cape May, New Jersey, USA",
"Windham, Windham, Connecticut, United States",
"Cape May,Cape May,New Jersey,USA",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Cape May, Cape May, New Jersey, United States",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Stratford, Fairfield, Connecticut, United States",
"Stratford, Fairfield, Connecticut, United States",
"Stratford, Fairfield County, Connecticut, United States of America",
"",
"Jupille , Belgium",
"",
"",
"",
"",
"Germany",
"",
"",
"London, City of London, Greater London, England",
"",
"",
"Carthago",
"",
"",
"Meulan, Yvelines, \u00cele-de-France, France",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"",
"",
"",
"",
"Fleury-sur-Ouche",
"",
"",
"",
"",
"",
"",
"Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Armstrong County, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Berks Co., PA",
"Longswamp, Berks, Pennsylvania, USA",
"Berks County, Pennsylvania ",
"Emmaus, Lehigh County, Pennsylvania, USA",
"Fontevrault, Maine-et-Loire, Pays de la Loire, France",
"",
"London, City of London, Greater London, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"Rouen, Seine-Maritime, Haute-Normandie, France",
"",
"",
"Arundel, Arun District, West Sussex, England",
"",
"",
"",
"",
"Vincennes, Val-de-Marne, \u00cele-de-France, France",
"Lille, Nord, Nord-Pas-de-Calais, France",
"",
"",
"",
"",
"Derbyshire, England",
"",
"Amiens, Somme, Picardie, France",
"",
"Eastchurch, Swale Borough, Kent, England",
"Kent, England",
"Rainham, Medway Unitary Authority, Kent, England",
"",
"douglas, castle, Lanarkshire, Scotland",
"",
"normandy, France",
"Arques, Seine Inferieure, Normandy, France",
"Arques, Seine Inferieure, Normandy, France",
"",
"",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"",
"Castle Dunbar, East Lothian, Scotland",
"Samlesbury, Lancashire, England",
"angus, scotland",
"Forfar, Angus, Scotland",
"Falaise, Calvados, Basse-Normandie, France",
"Falaise, Calvados, Basse-Normandie, France",
"",
"Grey Friars, Worcestershire, England.",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Okeover, Staffordshire, , England",
"Church, Wetzel, West Virginia, United States",
"",
"",
"",
"",
"Tamworth Castle, Staffordshire, England",
"Woodham Ferrers, Chelmsford Borough, Essex, England",
"Fardell Manor, Ivybridge, Devon, England",
"",
"",
"Chester, Cheshire, England",
"Biggar, Lanarkshire, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"",
"",
"",
"",
"",
"Badenoch, Inverness-shire, Scotland",
"",
"",
"Groby Castle, Leicestershire, England",
"",
"",
"France",
"",
"",
"",
"Surrey, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"Boreham, Chelmsford Borough, Essex, England",
"Aberdeenshire, Scotland",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Northumberland, England",
"Lancashire, England",
"Saint Denis, France",
"Inverness-shire, Scotland",
"Lancashire, England",
"",
"Lens, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Boulogne, Hauts-de-Seine, \u00cele-de-France, France",
"",
"",
"",
"Slain by Saracens of Battle of Mansura, Nile, delta, Egypt",
"Salisbury castle, Wiltshire, England",
"",
"",
"",
"",
"scotland",
"",
"",
"",
"",
"",
"Remiremont, Vosges, Lorraine, France",
"",
"",
"",
"",
"Vermand, Aisne, Picardie, France",
"",
"Normany, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Aumale, Seine-Maritime, Haute-Normandie, France",
"Nicea, Bithynia, Turkey",
"Amington, Staffordshire, England",
"",
"Solihull, Warwickshire, England",
"Solihull, Warwickshire, England",
"",
"Amesbury, Wiltshire Unitary Authority, Wiltshire, England",
"Dunbar, East Lothian, Scotland",
"Y, Somme, Picardie, France",
"",
"",
"",
"",
"",
"scotland",
"",
"",
"Aberdeenshire, Scotland",
"",
"",
"",
"Plouigneau, Finist\u00e8re, Bretagne, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Roma, Lazio, Italy",
"Lot-et-Garonne, Aquitaine, France",
"West cot, Dorking, Surrey, England",
"Lancashire, England",
"Speldhurst, Kent, England",
"Huntingdon, Huntingdonshire, England",
"Varenne, Cher, Centre, France",
"Lewes, Sussex, England",
"Lewes, Sussex, England",
"",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Y, Somme, Picardie, France",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
", Warwickshire, , England",
"Turin, Torino, Piemonte, Italy",
"",
"Ulcombe, Kent, England",
"Scotland, United Kingdom",
"Philadelphia, Philadelphia, Pennsylvania",
"Cropredy, Oxfordshire, England",
"",
"Y",
"Paris, Paris, Ile-De-France, France",
"Derby, Derbyshire, Kingdom of England",
"",
"",
"",
"",
"Castle Acre, Norfolk, England",
"Elmley Castle, Wychavon District, Worcestershire, England",
"Lewes, Sussex, England",
"",
"Ravanusa",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Woburn, Middlesex, Massachusetts, USA",
"",
"Gainsborough, Lincolnshire, England",
"Gainsborough, Lincolnshire, England",
"",
"",
"",
"Goshen, Chester, Pennsylvania, United States",
"Ulcombe, Kent, , England",
"Rainham, Medway Unitary Authority, Kent, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia City, Philadelphia, Pennsylvania",
"St. Johnston, Donegal, Ireland",
"",
"Hermiston, Midlothian, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"scotland",
"Aberdeenshire, Scotland",
"",
"glenorchy, Argyll, Scotland",
"douglas, castle, Lanarkshire, Scotland",
"douglas, castle, Lanarkshire, Scotland",
"Abernethy, Perthshire, Scotland",
"Huntly, Aberdeenshire, Scotland",
"",
"",
"St, Mary, Churchyard, Melton Mowbray, Leicestershire, England",
"",
"",
"London, City of London, Greater London, England",
"",
"",
"",
"",
"Scone, Pershire, Scotland",
"",
"Scotland",
"Scotland",
"",
"",
"Scotland",
"",
"Scotland",
"",
"Pittsgrove Twp., Salem Co., New Jersey",
"",
"",
"Clayton, Gloucester Co., New Jersey",
"",
"Clayton, Gloucester, New Jersey, USA",
"Clayton, Gloucester, New Jersey, USA",
"",
"Pittsgrove, Salem, New Jersey, USA",
"",
"Pittsgrove, Salem, New Jersey, USA",
"Wilmington, New Castle, Delaware, USA",
"Lower Alloways Creek, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, United States",
"Upper Alloway Creek, Salem, New Jersey, United States",
"Pittsgrove, Salem, New Jersey, United States",
"Daretown, Salem, New Jersey, United States",
"Hardingville, Gloucester, New Jersey, USA",
"Doylestown, Bucks, Pennsylvania, United States",
"Tullamore, Kerry, Ireland",
"",
"",
"Arbuthnott, Kincardineshire, Scotland",
"",
"",
"Dursley, Gloucestershire, England",
"bridgen, of, Lintrathen, Angus, Scotland",
"Somerset, England",
"England",
"Wincanton, Somerset, , England",
"",
"Whitechapel, London, Middlesex, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Buried: St. Peter and St. Paul Churchyard; Wincanton, Somerset, England",
"",
"Wincanton, Somerset, England",
"Wincanton, Somerset, England",
"England",
"",
"Jefferson, Alexandria, Virginia, United States",
"Burgh-by-Sands, City of Carlisle, Cumbria, England",
"Burgh-by-Sands, City of Carlisle, Cumbria, England",
"Berkeley, Stroud District, Gloucestershire, England",
"Berkeley, Stroud District, Gloucestershire, England",
"Richmond, London Borough of Richmond upon Thames, Greater London, England",
"",
"",
"",
"New Buckenham, Norfolk, England",
"Harwich, Barnstable, Massachusetts, United States",
"",
"Chatham, Barnstable, Massachusetts, USA",
"Eastham, Barnstable, Massachusetts, USA",
"Chatham, Barnstable, Massachusetts -LOST AT SEA",
"Yarmouth, Barnstable, Massachusetts, USA",
"Smyrna, Kent, Delaware, United States",
"Great Saxham, Suffolk, England",
"Wellfleet, Barnstable County, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"",
"",
"Cape May, Cape May, New Jersey, USA",
"Boston, Suffolk, Massachusetts, United States",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts",
"Delaware",
"Cape May, Cape May, New Jersey, USA",
"Smyrna, Kent, De",
"Amesbury, Essex, Massachusetts, United States",
"Eastham, Barnstable, Massachusetts, USA",
"",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"Cape May, Cape May, New Jersey, United States",
"",
"",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"Cape May, Cape May, New Jersey, United States",
"Yarmouth, Barnstable, Massachusetts, USA",
"Port Norris, Downe Twsp.,Cumberland, New Jersey, USA",
"",
"Kingston, Washington, Rhode Island, USA",
"Y",
"Amesbury, Wiltshire Unitary Authority, Wiltshire, England",
"",
"",
"Cape May, Cape May, New Jersey, USA",
"",
"",
"",
"",
"",
"Hempstead, Nassau, New York, United States",
"Flushing, Queens, New York, United States",
"Long Island City, Queens, New York, United States",
"",
"",
"New York, USA",
"Hempstead, Livingston, New York, United States",
"Hempstead, Nassau, New York, United States",
"Indiana, United States",
"",
"",
"",
"",
"Hempstead, Nassau, New York, United States",
"Hempstead, Nassau, New York, United States",
"",
"Hempstead, Queens, New York, United States",
"Freehold, Monmouth, New Jersey, USA",
"Dunbar, East Lothian, Scotland",
"",
"",
"",
"",
"",
"",
"Ipswich, Essex, Massachusetts",
"",
"",
"Haddonfield, Camden, New Jersey, USA",
"Groby Castle, Leicestershire, England",
"Groby, Leicestershire, England.",
"Wrotham, Kent, England",
"Leicestershire, England",
"",
"Raglan, Monmouth, Gwent, Wales",
"Baddesley Clinton Manor, Warwick, Warwickshire, England",
"Burton, Yorkshire, England",
"Newton Abbot, Devon, England",
"",
"",
"West Peckham, Kent, , England",
"Norton, Northamptonshire, , England",
"Baddesley Clinton, Warwickshire, England",
"",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Kingston upon Soar, Nottinghamshire, England",
"Halifax, Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"USA",
"",
"Surrey, England",
"Arundel, Arun District, West Sussex, England",
"",
"Lacock Abbey, Wiltshire, England",
"Normandy",
"Woodham Walter, Essex, England",
"Badlesmere, Swale Borough, Kent, England",
"",
"Siege, of, Damietta, Egypt",
"Tawstock, Devon, England",
"Austin Friars,london,middlesex,england",
"Nythway, Devon, England",
"Keynsham, Bath and North East Somerset Unitary Authority, Somerset, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"Flanders, Nord, Nord-Pas-Calais, France",
"Ghent, Flandre Orientale, Belgium",
"Arras, Hautes-Pyr\u00e9n\u00e9es, Midi-Pyr\u00e9n\u00e9es, France",
"Blandijnberg, Ghent. East Flanders Belgium",
"Vlaanderen, East Flanders, Belgium",
"Caen, Calvados, Basse-Normandie, France",
"",
"",
"",
"Kilmarnock, Ayrshire, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"",
"",
"",
"England",
"Newnham Manor, Plympton St Mary, Devonshire, Bermuda",
"",
"Kent, England",
"Beverly, Essex, Massachusetts, United States",
"Rolvenden, Kent, England",
"Rolvenden, Kent, England",
"Showton, Hallow, Worcestershire, England",
"",
"",
"",
"",
"",
"",
"Bilinghurst, Sussex, England",
"",
"",
"",
"All Saints Parrish, Derby, Derbyshire, England",
"All Saints Parish, Derby, Derbyshire, England",
"Cambridge, Gloucestershire, England",
"Derby, Derbyshire, England",
"Dursley, Gloucestershire, England",
"Dursley, Gloucestershire, England",
"",
"",
"",
"",
"",
"Tufara, Campobasso, Molise, Italy",
"",
"Tufara, Campobasso, Molise, Italy",
"Tufara, Campobasso, Molise, Italy",
"New Hanover, Montgomery, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia County, Pennsylvania, United States of America",
"Philadelphia, Philadelphia, Pennsylvania",
"Ipswich, Essex, Massachusetts, United States",
"Ipswich, Essex, Massachusetts, USA",
"Wiltshire, England",
"",
"Bolbec, Pays de Caux, Haute-Normandie, France",
"scotland",
"",
"",
"Thorne, Devon, England",
"",
"England",
"Over Wallop, Hampshire, England",
"England",
"Upham, Hampshire, England",
"",
"Itchell, Hampshire, England",
"Billerica, Middlesex, Massachusetts Bay Colony, British Colonial America",
"Woodbridge, Middlesex, New Jersey, United States",
"England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Fyvie, Aberdeenshire County, Scotland",
"",
"Wilmington, Kent, England",
"Sussex, England",
"",
"",
"",
"",
"",
"Aberdeenshire, Scotland",
"Cape May, Cape May, New Jersey, United States",
"massachusetts bay colony",
"",
"",
"",
"",
"Myers",
"",
"New Haven, New Haven County, Connecticut, USA",
"",
"Tunbridge, Kent, , England",
"Stansted, Kent, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Silkstone with Stainborough, All Saints, Yorkshire, England",
"Pittsgrove, Salem, New Jersey, USA",
"Stratford, Fairfield, Connecticut, United States",
"Newport, Newport, Rhode Island, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Hartford, Hartford, Connecticut, United States",
"",
"Shrewsbury Abbey, Shrewsbury, Shropshire, England",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Aaronsburg, Centre, Pennsylvania, USA",
"Saybrook, Middlesex, Connecticut, United States",
"St Michael, Crooked Lane, London, or Speldhhurst, Tonbridge Wells, Kent, England",
"",
"Mancetter, Warwickshire, England",
"",
"Speldhurst, Kent, England",
"Speldhurst, Kent, England",
"",
"",
"",
"Germantown, Philadelphia County, Pennsylvania, United States of America",
"",
"West Nottingham, Cecil County, Maryland",
"",
"",
"",
"",
"leys, kincardine, Scotland",
"leys, kincardine, Scotland",
"Lanarkshire, Scotland",
"Yarmouth, Barnstable, Massachusetts, United States",
"Worcestershire, England",
"",
"",
"",
"",
", Cape May, New Jersey, USA",
"",
"",
"1766 Norris St.",
"",
"",
"Hebron, Tolland, Connecticut, United States",
"Cape May, Cape May, New Jersey, United States",
"England",
"East Hampton, Suffolk, NY, USA",
"East Hampton, Suffolk, NY, USA",
"",
"Elmer, Salem, New Jersey, USA",
"Cape May, New Jersey, USA",
"Massachusetts, United States",
"Seaville, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"",
"",
"Bridgeton City, Cumberland, New Jersey",
"",
"Williamsport, Pennsylvania",
"",
"Cape May, Cape May, New Jersey, United States",
"",
"Cape May, Cape May, New Jersey, United States",
"East Hampton, Suffolk, New York, United States",
"",
"",
"Westmeath, Ireland",
"England",
"",
"Camden Camden County NJ USA",
"Cape May, New Jersey, United States",
"Port Norris, Commercial Township, Cumberland Co., New Jersey",
"Port Norris, Commercial Township, Cumberland Co., New Jersey",
"",
"",
"Millville, NJ",
"Tunbridge, Kent, England",
"Tunbridge, Kent, , England",
"Medford, Burlington, New Jersey",
"",
"",
"",
"",
"Cape May, Cape May, New Jersey, United States",
"Washington, Virginia, United States",
"Washington County, Virginia, USA",
"Easthampton, Long Island, Suffolk, NY, USA",
"Washington County, VA",
"Washington, Virginia, United States",
"",
"",
"England",
"Cape May, Cape May, New Jersey, United States",
"Newport, Cumberland County, New Jersey",
"Shelby, Illinois, United States",
"england",
"England",
"England, United Kingdom",
"Stafford, Staffordshire, England",
"",
"",
"",
"England",
"Staffordshire, England",
"Staffordshire, England",
"Guilford, New Haven, Connecticut",
"suffolk, ny, british colonial america",
"East Hampton, Suffolk, New York, United States",
"East Hampton, Livingston, New York, United States",
"Cape May, Cape May, New Jersey, United States",
"",
"Staffordshire, England",
"",
"East Hampton, Suffolk County, New York, United States of America",
"Long Island City, Queens, New York, United States",
"Staffordshire, England",
"Staffordshire, England",
"",
"",
"Hammondssett/Guilford, New Haven, CT",
"Guilford, New Haven, Connecticut, United States",
"NJ, United States",
"",
"",
"",
"Cumberalnd Co., New Jersey",
"",
"",
"",
"Boston, Suffolk, Massachusetts, USA",
"Boston, Suffolk, Massachusetts, USA",
"New Jersey,USA",
"Easthampton, Suffolk, New York, United States",
"East Guilford, New Haven, Connecticut, USA",
"",
"",
"",
"",
"",
"",
"",
"",
", , Massachusetts, USA",
", , Massachusetts, USA",
"",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, USA",
"Lewistown, Mifflin, Pennsylvania, USA",
"",
"Craven, North Carolina, United States",
"Middletown, Middlesex, Connecticut, United States",
"Newport, Cumberland, New Jersey",
"West Point Troup Georgia",
"",
"Cape May County, New Jersey, Colonies",
"",
"Cape May, Cape May, New Jersey, United States",
"",
"",
"Trenton, Hunterdon, New Jersey, United States",
"",
"",
"",
"",
"",
"Cold Spring, Cape May, New Jersey, United States",
"Seaville, Cape May, New Jersey, United States",
"Cape May, New Jersey, USA",
"",
"Stafford, England",
"Stepney, Middlesex, England",
"Long Island City, Queens, New York, United States",
"",
"Kent, England",
"Kent, England",
"",
"",
"",
"",
"Sundridge, Kent, England",
"Shropshire, England",
"",
"Wilmington, Kent, England",
"Wilmington, Kent, England",
"Staffordshire, England",
"",
"",
"Washington County, Virginia, USA",
"Cape May, Cape May, New Jersey, United States",
"Long Island City, Queens, New York, United States",
"Staffordshire, England",
"Staffordshire, England",
"Cape May, New Jersey, USA",
"Staffordshire, England",
"Benenden, Kent, England",
"",
"Wilmington, Kent, England",
"",
"",
"Newport, New Jersey, US",
"",
"Downe Twsp.,Cumberland,New Jersey,USA",
"",
"East Hampton, Suffolk County, New York, United States of America",
"Wilmington, Kent, England",
"",
"Kent, England",
"Wilmington, Kent, England",
"Easthampton, Suffolk, New York",
"East Hampton, Suffolk County, New York, United States of America",
"East Hampton, Suffolk, New York",
"Wales",
"England",
"",
"Wincanton, Somerset, England",
"New Hanover, Montgomery, Pennsylvania, USA",
"",
"",
"",
"",
"Bedford, Lawrence, Indiana, USA",
"Germany",
"Berks County, Pennsylvania, USA",
"Douglass, Berks, Pennsylvania, USA",
"",
"",
"",
"Kent, England",
"Bound Brook, Somerset County, New Jersey, US",
"New Jersey, US",
"West Nottingham, Chester, PA, USA",
"Nottingham, Chester County, Pennsylvania, US",
"",
"Upper Pittsgrove, Salem, New Jersey, USA",
"",
"Elizabethtown, NJ",
"Somerset, NJ",
"",
"West Nottingham, Chester Co., Pennsylvania",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex, New Jersey",
"Rochester, Kent, England",
"Wilmington, New Hanover County, North Carolina, US",
"",
"",
"",
"Hardin Co., KY",
"",
"",
"",
"",
"",
"Ipswich, Essex, Massachusetts, United States",
"West Nottingham, Chester Co., Pennsylvania",
"(7) W. Nottingham, Chester, PA, USA",
"",
"Gloucester, Essex, Massachusetts, United States",
"Philadelphia, Philadelphia Co., PA",
"Lynn, Essex, Massachusetts, United States",
"Gloucester, Essex, Massachusetts, USA",
"",
"Gloucester, Essex, Massachusetts, USA",
"Gloucester, Essex, Massachusetts, USA",
"Charlton, Somerset, , England",
"Gloucester, Essex County, Massachusetts, USA",
"Charlton Musgrove, South Somerset District, Somerset, England",
"",
"",
"Westminster, Middlesex, England",
"",
"",
"",
"Errol, Perthshire, Scotland",
"Aberdeenshire, Scotland",
"",
"Branxton, Northumberland, England",
"Collieston, Aberdeenshire, Scotland",
"Huntly, Aberdeenshire, Scotland",
"",
"yester, haddingtonshire scotland",
"Dunbar, East Lothian, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Gifford, East Lothian, Scotland",
"",
"",
"",
"",
"",
"",
"",
"Diseworth, Leicestershire, England",
"Diseworth, Leicestershire, England",
"",
"",
"",
"Morayshire, Scotland",
"",
"Berks County, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Arnold, Nottinghamshire, , England, ",
"Westminster, City of Westminster, Greater London, England",
"Westminster, City of Westminster, Greater London, England",
"Emmaus, Lehigh County, Pennsylvania",
"Woodthorpe, Staveley, Derbyshire, Kingdom of England",
"Kingdom of England",
"",
"",
"",
"",
"",
"",
"Diseworth, Leicestershire, England",
"Diseworth, Leicestershire, England",
"Derby, Derbyshire, England",
"Downe,Cumberland, New Jersey",
"Westtown, Chester, Pennsylvania, United States",
"Turkey Point, Cumberland, New Jersey, United States",
"Thornbury, Chester, Pennsylvania, United States",
"Thornbury,Chester,Pennsylvania,USA",
"Thornbury,Chester,Pennsylvania,USA",
"Thornbury,Chester,Pennsylvania,USA",
"Thornbury,Chester,Pennsylvania,USA",
"Newport, Dividing Creek, NJ",
"Battle Creeek, Kalamazoo, Michigan, United States",
"Battle Creeek, Kalamazoo, Michigan, United States",
"Cumberland, Cumberland, New Jersey, United States",
"Dividing Creek, NJ",
"Camden CO, New Jersey",
"Marlborrough, Witlshire, England",
"James City, Virginia, United States",
"Gainsborough Hall, Lincolnshire, England",
"Dennisville, Cape May, New Jersey, United States",
"Bulmer, Essex, England",
"",
"Heuchelheim, Bamberg, Bayern, Germany",
"Barwick, Somerset, England",
"",
"Wincanton, Somerset, England",
"",
"Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania",
"Philadelphia City, Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania",
"England",
"Up Holland, West Lancashire District, Lancashire, England",
"Wallingford, South Oxfordshire District, Oxfordshire, England",
"",
"",
"Up Holland, West Lancashire District, Lancashire, England",
"Up Holland, West Lancashire District, Lancashire, England",
"",
"Up Holland, West Lancashire District, Lancashire, England",
"",
"",
"Goshen, Chester, Pennsylvania, United States",
"Westtown, Chester, Pennsylvania, USA",
"Goshen, Chester, Pennsylvania, United States",
"Great Moorsholm, Skelton-Cleveland, Yorkshire, England",
"Middleton Falls, Bucks, Pennsylvania, USA",
"East Bradford Twp., Chester Co., Pennsylvania",
"Staplehurst, Kent, England",
"",
"",
"Scituate, Plymouth, Massachusetts, United States",
"scotland",
"scotland",
"",
"Scituate, Plymouth, Massachusetts, United States",
"Barnstable, Barnstable, Massachusetts, United States",
"",
"",
"",
"Gloucester, MA",
"",
"",
"",
"",
"PA, Montgomery, Hatbor0, United States",
"",
"",
"",
"Dorset, England",
"",
"",
"",
"",
"",
"Westtown, Chester, Pennsylvania, United States",
"Westtown, Chester, Pennsylvania, USA",
"Germany",
"",
"",
"",
"",
"",
"",
"",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Marcon, Sarthe, Pays de la Loire, France",
"",
"",
"",
"Ghent, East Flanders, Flanders, Belgium",
"",
"",
"Bengeworth, Worcestershire, England",
"Long Island City, Queens, New York, United States",
"Clare, St Edmundsbury Borough, Suffolk, England",
"Clare, St Edmundsbury Borough, Suffolk, England",
"Newark-on-Trent, Newark and Sherwood District, Nottinghamshire, England",
"",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Aberdeenshire, Scotland",
"",
"Kirkcudbrightshire, Scotland",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"",
"",
"Pennsylvania, USA",
"",
"",
"",
"Aachen, Reichsstad, Germany",
"Quierzy, France",
"Modena, Emilia-Romagna, Italy  (buried in Paris, France)",
"",
"Ingelheim, Germany (buried in Metz, France)",
"",
"",
"",
"",
"ireland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Dunnottar, Kincardineshire, Scotland",
"",
"England",
"Hitcham, Cosford, Suffolk, England",
"",
"",
"Jutland, Denmark",
"Overton, Hampshire, England",
"st james, Clerkenwell, Middlesex, England",
"Yardley Hastings, Northamptonshire, England",
"St James, Clerkenwell, Middlesex, England",
"England",
"",
"Over Wallop, Hampshire, England",
"",
"",
"Overton, Hampshire, England",
"Speldhurst, Kent, England",
"Tunbridge Castle, Kent, England",
"Tunbridge Castle, Kent, England",
"Groombridge,Speldhurst,Kent,England",
"",
"",
"Rattlesden, Suffolk, England",
"London, London, England",
"",
"",
"Pluderhausen, Wurttemberg, Germany",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"Collingswood, New Jersey, United States",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"Aaronsburg, Centre, Pennsylvania",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"Winningen, Mayen-Koblenz, Rheinland-Pfalz, Germany",
"Philadelphia County, Pennsylvania, United States of America",
"",
"",
"",
"",
"Broughton, Kent, England",
"Stockwell, London Borough of Lambeth, Greater London, England",
"England",
"Bury St Edmunds, St Edmundsbury Borough, Suffolk, England",
"",
"Gloucester, Essex, Massachusetts, United States",
"Berks Co., Pennsylvania",
"Edinburgh, Midlothian, Scotland",
"",
"",
"Berks County, Pennsylvania ",
"",
"",
"",
"",
"Beckermet, Cumberland, England",
"Hermiston, Midlothian, Scotland",
"Cumberland, England",
"",
"",
"Cape May, Cape May, New Jersey, United States",
"",
"Cape May, Cape May, New Jersey, USA",
"Cape May County, New Jersey",
"Cape May",
"Cape May, New Jersey, USA",
"West, Jersey, Channel Islands",
"",
"Aberdeen, Aberdeen City, Scotland",
"",
"Philadelphia, Philadelphia Co., PA",
"Philadelphia, Philadelphia Co., PA",
"Fort Defiance, Wilkes, North Carolina, United States",
"Philadelphia, Pa",
"Philadelphia, Philadelphia County, Pennsylvania, United States of America",
"sURREY, vIRGINIA",
"Tarboro, Edgecombe, North Carolina, USA",
"",
"",
"",
"",
"",
"",
"Norwalk, Fairfield, Connecticut, United States",
"",
"Stratford, Fairfield County, Connecticut, United States of America",
"Fyvie, Aberdeenshire, Scotland",
"Scotland",
"leys, kincardine, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Perth, Perthshire, , Scotland",
"",
"Monzie, Perthsire, Scotland",
"",
"",
"Chinon, Indre-et-Loire, Centre, France",
"Renfrewshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Virginia Colony",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable County, Massachusetts, USA",
"leys, kincardine, Scotland",
"Cushnie, Aberdeenshire, Scotland",
"",
"Northumberland, England",
"",
"",
"",
"Scotland",
"",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Phila, Phila, Pennsylvania, USA",
"Merchantville, Camden, New Jersey, USA",
"",
"Philadelphia, Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania",
"Vineland, Cumberland, New Jersey, USA",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia City, Philadelphia, Pennsylvania",
"Philadelphia City, Philadelphia, Pennsylvania",
"",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Philadelphia, Philadelphia, Pennsylvania",
"Philadelphia City, Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia , pa",
"",
"Carlisle, Cumbria, England",
"Forfar, Angus, Scotland",
"Forfar, Angus, Scotland",
"Finella's Castle, Fettercairn, Kincardineshire, Scotland",
"",
"Glamis Castle, Angus, Forfarshire, Scotland",
"Lorne, Argyll and Bute, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"Falaise, Calvados, Basse-Normandie, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Upper Providence Twp., Chester (later Delaware), Pennsylvania",
"",
"",
"",
"",
"Poitiers, Vienne, Poitou-Charentes, France",
"Haughton, Staffordshire, England",
"Marlborough, Wiltshire Unitary Authority, Wiltshire, England",
"Gloucester, Essex, Massachusetts, United States",
"Ravanusa, Agrigento, Sicilia, Italy",
"Bolney, Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Uitikon, Zurich, Switzerland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Angusshire, Scotland",
"",
"Fyvie, Aberdeenshire, Scotland",
"Fyvie, Aberdeenshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Edinburgh, Midlothian, Scotland, United Kingdom",
"Bishops, Stortford, Hertfordshire, England",
"England",
"Colyton, Devon, England",
"",
"Buckinghamshire, Suffolk, England",
"",
"Essex, England",
"Tamworth, Staffordshire, England",
"",
"Hempstead, Nassau, New York, USA",
"Westtown, Chester, Pennsylvania, United States",
"Dunbar, East Lothian, Scotland",
"Lanarkshire, Scotland",
"",
"",
"",
"scotland",
"",
"",
"England",
"Berkeley, Gloucestershire, , England",
"",
"",
"Winchester, Hampshire, England",
"Berks County, Pennsylvania, USA",
"Berks County, Pennsylvania ",
"Frankenthal Evangelical Church, Heuchelheim, Bayern, Germany ",
"Zurich, Switzerland",
"Uitikon, Zurich, Switzerland",
"Pfalzdorf, Kleve, Nordrhein-Westfalen, Germany ",
"Winningen, Mayen-Koblenz, Rheinland-Pfalz, Germany",
"Switzerland",
"",
"Germany",
"Germany",
"Bretten, Karlsruhe, Baden-Wuerttemberg, Germany",
"Cochem, Cochem-Zell, Rheinland-Pfalz, Germany",
"",
"",
"Chesterfield, Burlington, New Jersey, USA",
"Worksop, Nottinghamshire, England",
"Crosswicks, Burlington, New Jersey, USA",
"Lurgan, Armagh, Northern Ireland",
"Lincolnshire, England",
"Westmoreland, Virginia, United States",
"",
"South Yorkshire, England",
"Ipswich, Essex, Massachusetts, United States",
"Streat, Sussex, England",
"",
"",
"Hempstead, LI, New York, United States",
"",
"",
"Indiana, Indiana, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Murdered at Picquigny, Somme, Picardy, France",
"Murdered at Picquigny, Somme, Picardy, France",
"",
"",
"",
"Altena, M\u00e4rkischer Kreis, North Rhine-Westphalia, Germany",
"",
"",
"Mark, Germany",
"Arnsberg, Germany",
"Werle, Germany",
"",
"",
"",
"",
"",
"Bayeux, de, Evreux, Eure, Haute-Normandie, France",
"",
"Bengeworth, Evesham, Worcestershire, England",
"Berg , Germany",
"Berg , Germany",
"Berg , Germany",
"",
"",
"",
"",
"",
"",
"Harby, Newark and Sherwood District, Nottinghamshire, England",
"",
"Lobith, Rijnwaarden, Gelderland, Netherlands",
"",
"Cleves, Germany",
"Cleves, Germany",
"Germany",
"",
"",
"Alsace, France",
"",
"",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"",
"",
"Leicester, Leicester Unitary Authority, Leicestershire, England Cemetery: Saint Paul's Cathedral Burial or Cremation Place: London, City of London, Greater London, England",
"",
"",
"",
"",
"",
"",
"",
"lahngau, Germany",
"Death Place: Staffordshire, England Cemetery: Saint Paul's Cathedral Burial or Cremation Place: London, City of London, Greater London, England",
"Death Place: Leicester, Leicester Unitary Authority, Leicestershire, England Cemetery: Church of the Annunciation of St. Mary Burial or Cremation Place: Leicester, Leicester Unitary Authority, Leicestershire, England",
"Death Place: England Cemetery: Church of the Annunciation of St. Mary Burial or Cremation Place: Leicester, Leicester Unitary Authority, Leicestershire, England",
"",
"",
"",
"Laufen, Berchtesgadener Land, Bavaria, Germany",
"Lobdengau, Germany",
"",
"Mark, Germany",
"Germany",
"Bamberg, Germany",
"",
"Neiderlahngau, Germany",
"",
"",
"France",
"France",
"",
"Conquereuil, Loire-Inferierure, Bretagne, France",
"",
"Swabia, Germany",
"Swabia, Germany",
"",
"Alsace, France",
"",
"",
"Laufen, Berchtesgadener Land, Bavaria, Germany",
"London, City of London, Greater London, England",
"",
"",
"angus, scotland",
"",
"scotland",
"Moulin, Perthshire, Scotland",
"Lintrathen, Angus, Scotland",
"Moulin, Perthshire, Scotland",
"Arques, Seine-Maritime, Haute-Normandie, France",
"Arques, Seine Inferieure, Normandy, France",
"",
"Piscataway, Middlesex County, New Jersey, US",
"",
"",
"",
"Woodbridge, Middlesex, New Jersey",
"Middletown, Bucks, Pennsylvania, United States",
"Piscataway, Middlesex County, New Jersey",
"Raritan Landing, Somerset, New Jersey, United States",
"Piscataway, Middlesex, New Jersey, United States",
"Woodbridge, Middlesex, New Jersey, United States",
"Woodbridge, Middlesex, New Jersey, United States",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Woodbridge, Middlesex Co, New Jersey",
"Scituate, Plymouth, Massachusetts, USA",
"All Saints Parish, Derbyshire, England",
"Woodbridge, Middlesex Co, New Jersey",
"Narragasett Bay, Middlesex, Massachusetts, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Cape May, New Jersey, USA",
"Philadelphia City, Philadelphia, Pennsylvania",
"Cape May, Cape May, New Jersey, USA",
"",
"Wessex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"England",
"England",
"Buckinghamshire, England",
"",
"",
"Shrewsbury, Shropshire, England",
"",
"",
"Northumberland, England",
"Yorkshire, England",
"Brooznell, Chester, Pennsylvania, United States",
"",
"St Botolph Bishopsgate, London, England",
"West Creek, Ocean, New Jersey, United States",
"Stafford Township, Monmouth, New Jersey, USA",
"Springfield, Essex, New Jersey, USA",
"Burlington, New Jersey",
"",
"",
"",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"",
"",
"Bayonne, Departement des Pyr\u00e9n\u00e9es-Atlantiques, Aquitaine, France",
"",
"Ghent, Arrondissement Gent, East Flanders (Oost-Vlaanderen), Belgium",
"Ghent, Arrondissement Gent, East Flanders (Oost-Vlaanderen), Belgium",
"Quendon, Uttlesford District, Essex, England",
"Quendon, Uttlesford District, Essex, England",
"",
"",
"England",
"",
"",
"Cupar, Fife, Scotland",
"",
"",
"England",
"Nord-Pas-de-Calais, France",
"",
"",
"Winchester, City of Winchester, Hampshire, England",
"Chateau, Eure-et-Loir, Centre, France",
"Firle Church, Sussex, England",
"Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Basing, Hampshire, England",
"Chew Magna, Somerset, England",
"Bayern, Staudach-Egerndach, Traunstein, Oberbayern, Bavaria, Germany",
"M\u00fcnchen, M\u00fcnchen, Oberbayern, Bayern, Germany",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Aquitaine, France",
"Aquitaine, France",
"",
", , , England",
"",
"",
"",
"",
"",
"",
"",
"",
"Forfar shire, Scotland",
"",
"",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Dublin, Ireland",
"",
"",
"",
"Westchester Square, Bronx County, New York, United States of America",
"Northern Ireland",
"Hortensia, Monmouth, New Jersey",
"Niddry-Seton Castle, Edinburgh, Scotland ",
"Freehold, Monmouth, New Jersey",
"",
"Conquereuil, Loire-Inferierure, Bretagne, France",
"lived Suffolk, England",
"Hundon, Suffolk, England",
"Suffolk, England",
"",
"St Michael Bassishaw, London, England",
"",
"",
"Derby, Derbyshire, England",
"",
"Derby, Derbyshire or Westmoreland, England",
"Derby, Derbyshire, England",
"",
"",
"Derby, Derbyshire, England",
"",
"",
"",
"",
"Elizabeth City, , Virginia, USA",
"Hamilton, Lanarkshire, Scotland",
"Hamilton, Lanarkshire, Scotland",
"Downe, Cumberland,New Jersey",
"Staffordshire, England",
"",
"England",
"Banbury, Oxfordshire, England",
"",
"",
"Gloucester, Essex, Massachusetts, USA",
"Gloucester, Essex, Massachusetts, USA",
"",
"Burton upon Trent, Staffordshire, Kingdom of England",
"Staveley, Derbyshire, Kingdom of England",
"",
"Thueringen, Germany",
"",
"",
"",
"",
"",
"killed in battle of Halidon Hill",
"",
"",
"",
"",
"",
"",
"Springfield, PA, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia, Pennsylvania, United States",
"",
"Aston, Delaware, Pennsylvania, USA",
"",
"",
"Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Camden, NJ, United States",
"Camden County, New Jersey, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"Woodbury, Gloucester, New Jersey, United States",
"",
"",
"",
"",
"Leabeg, Ferbane, County Offaly or Pollagh, Galway, Ireland (died of pneumonia)",
"",
"",
"",
"",
"",
"",
"",
"California, USA",
"Colorado Springs, Co",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"Abington, Montgomery, Pennsylvania, USA",
"",
"",
"",
"",
"Deborah NJ",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia, Pennsylvania",
"Phila, pa",
"Philadelphia, Philadelphia County, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Cinnaminson, Burlington, New Jersey, USA",
"",
"",
"",
"",
"",
"",
"Ulcombe, Maidstone Borough, Kent, England",
"Ulcombe, Maidstone Borough, Kent, England",
"Ulcombe, Kent, England",
"Ulcombe, Maidstone Borough, Kent, England",
"",
"Ulcombe, Kent, England",
"",
"Niddry Castle, Midlothian, Scotland",
"Niddrew Castle, Edinburgh, Scotland",
"Sewell, Gloucester, New Jersey, USA",
"",
"England, United Kingdom",
"",
"Emmaus, Lehigh, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Uitikon,  Zurich,  Switzerland",
"",
"Philadelphia County, Pennsylvania, USA",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia County, Pennsylvania, USA",
"Philadelphia, Pennsylvania, USA",
"Willingboro, Burlington, New Jersey, USA",
"Jenkintown, Montgomery, Pennsylvania, USA",
"",
"Burlington County, New Jersey, USA",
"",
"",
"",
"",
"",
"Parkertown, Burlington, New Jersey, United States",
"England",
"Y",
"",
"Hempstead, LI, New York, United States",
"Long Island City, Queens, New York, United States",
"",
"New Jersey, Monmouth, New Jersey, United States",
"West Creek, Ocean, New Jersey, United States",
"Little Egg Harbor, Burlington, New Jersey, USA",
"",
"Hempstead, LI, New York, USA",
"Nassau, Livingston, New York, United States",
"",
"",
"",
"",
"Michigan, United States",
"Stamford, Fairfield, Connecticut, United States",
"Y",
"Hempstead, Nassau, New York, USA",
"Leicestershire, England",
"Pantfield, Essex, England",
"Hempstead, Long Island, New York, USA",
"Hempstead, LI, New York, United States",
"Hempstead, Nassau, New York, USA",
"New Hempstead, Orange, New York, United States",
"Stafford, Monmouth, New Jersey",
"West Creek, Monmouth, New Jersey, United States",
"Y",
"Little Egg Harbor, Ocean, New Jersey, United States",
"",
"",
"",
"",
"",
"St Dunstan and All Saints, Stepney, Middlesex, England",
"Stafford, Monmouth, New Jersey, United States",
"Unknown",
"",
"Bulmer, Essex, England",
"Westbury, Queens, New York, United States",
"",
"",
"",
"Lenawee, Michigan",
"Bulmer, Essex, England",
"St Botolph Bishopsgate, London, England",
"",
"parish, Essex, England",
"St Mary, Whitechapel, Middlesex, England",
"",
"Fl\u00e8che, Sarthe, Pays de la Loire, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Eboracum, Yorkshire, England",
"",
"",
"England",
"England",
"",
"",
"",
"Staffordshire, England",
"New Jersey, United States",
"New Jersey, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vincentown, Burlington, New Jersey, United States of America",
"",
"Camden, Camden, New Jersey",
"",
"",
"",
"",
"Barrington, Camden, New Jersey, USA",
"",
"",
"",
"",
"",
"cherry hill, New Jersey, United States",
"Egg Harbor, Cape May, New Jersey, United States",
"",
"",
"",
"Westmeath, Ireland",
"Staffordshire Kent England",
"Staffordshire, England",
"",
"",
"Shropshire, England",
"Philadelphia, PA",
"Philadelphia, PA",
"Lapford, Devon, England",
"Walsham le Willows, Suffolk, England",
"Crediton, Devon, England",
"",
"",
"",
"",
"United States of America",
"Millsboro, Sussex, Delaware, USA",
"Delaware",
"",
"",
"",
"Morvern, Argyll, Scotland",
"",
"Morven, Argyll, Scotland",
"Roundhill, Somerset, England",
"Roundhill, Somerset, England",
"Derby, Derbyshire, England",
"Diseworth, Leicestershire, England",
"Derby, Derbyshire, England",
"Diseworth, Leicestershire, England",
"",
"Diseworth, Leichester, England",
"Diseworth, Leichester, England",
"Derby, Derbyshire, England",
"",
"Pittsgrove, Salem, New Jersey, USA",
"Anne Arundel County, Maryland, USA",
"Deptford, Gloucester, New Jersey, United States",
"Pilesgrove, Salem, New Jersey, USA",
"",
"Cape May, New Jersey, USA",
"New Jersey, USA",
"Waterford, Camden, New Jersey, United States",
"Falaise, Calvados, Basse-Normandie, France",
"",
"Windsor, Berkshire, England",
"Ulcombe, Kent",
"Gb",
"Banbury, Oxfordshire, England",
"Appleby-in-Westmorland, Cumbria, England",
"",
"",
"",
"",
"",
"",
"Kelso, Roxburghshire, Scotland",
"",
"Roxburgh Castle Scotland (cannon he lit during seige exploded",
"",
"scotland",
"",
"",
"strathbane, Stirlingshire, Scotland",
"Dundonald, Castle, Ayrshire, Scotland",
"Lorne, Argyll and Bute, Scotland",
"Bathgate Castle, West Lothian, Scotland",
"",
"",
"",
", Cape May, New Jersey, USA",
"Perth, Perthshire, , Scotland",
"",
"",
"",
"",
"Long Island City, Queens, New York, United States",
"England",
"Devon, England",
"Plympton St Mary, Devon, England",
"Plympton St Mary, Devon, England",
"Devon, England",
"",
"Plympton St Mary, Devon, England",
"Plympton Church, Devon, , England",
"Thornbury,Chester,Pennsylvania,USA",
"Thornbury,Chester,Pennsylvania,USA",
"Thornbury,Chester,Pennsylvania,USA",
"Uppsala, Sweden",
"",
"",
"",
"",
"",
"",
"Hitcham, Cosford, Suffolk, England",
"England",
"",
"",
"",
"Cape May, New Jersey, USA",
"",
"East Hampton, Suffolk County, New York, USA",
"East Hampton, Suffolk County, New York, USA",
"",
"Hambleton, Rutland, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Tunbridge, Kent, England",
"",
"",
"",
"Berks County, Pennsylvania",
"Stratford, Fairfield, Connecticut Colony",
"",
"Uppsala, Sweden",
"Uppsala, Sweden",
"",
"",
"Gloucester, Gloucestershire, England",
"1673104, Oxfordshire, England",
"",
"Gloucester, Gloucestershire, England",
", Oxfordshire, England",
"York, Virginia",
"",
"",
"Poitiers, Vienne, Poitou-Charentes, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Richmond Palace, Richmond, Surrey, England",
"",
"Showton, Worcestershire, England",
"Derby, Derbyshire, England",
"",
"Moulin, East Lothian, Scotland",
"",
"St Denis, Aude, Languedoc-Roussillon, France",
"Suffolk, England",
"Schreisheim, Baden-Wuerttemberg, Germany",
"",
"England",
"Thuborough Barton, Sutcombe, Devon, England",
"",
"",
"",
"",
"Pannonie Brigetio",
"",
"",
"",
"",
"",
"",
"",
"",
"Arkel, Z-H, Holland, Netherlands",
"",
"",
"",
"Syrie",
"IJsselmonde, Rotterdam, Zuid-Holland, Netherlands",
"",
"",
"",
"",
"",
"Arkel, Z-H, Holland, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"Schoorl, Noord-Holland, Netherlands",
"Ijsselstein, Utrecht, Netherlands",
"",
"",
"",
"",
"Heraklion, Greece",
"",
"",
"",
"Egmond, Noord-Holland, Netherlands",
"",
"near the Elbe in Germany",
"",
"",
"",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"gravenhage, Hollande",
"",
"",
"",
"Reims, Marne, Champagne-Ardenne, France",
"",
"",
"",
"",
"Egmond, Noord-Holland, Netherlands",
"",
"",
"",
"",
"Varenne, Seine-Infereieure, Normandy, France",
"Raffin, Meath, 1652383",
"Meath, Leinster, Ireland",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Derby, Derbyshire, England",
"Thornbury, Chester, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Longtown, City of Carlisle, Cumbria, England",
"Staplehurst, Kent, England",
"",
"Gwynedd, Wales",
"",
"Speldhurst, Kent, England",
"",
"Virginia, United States",
"Lancaster, Lancashire, England",
"Massachusetts, USA",
"",
"Massachusetts, USA",
"wampanoag village, Yarmouth, Barnstable, Massachusetts, USA",
"Rolvenden, Kent, England",
"Laughton, Sussex, England",
"Pokanoket Village, Massachusetts, USA",
"",
"Connecticut, USA",
"Evesham, Worcestershire, England",
"Long Island City, Queens, New York, United States",
"Long Island, New York",
"Long Island City, Queens, New York, United States",
"Bengeworth, Worcestershire, England",
"Bridgewater, Plymouth, Massachusetts, United States",
"Bridgewater, Plymouth, Massachusetts, United States",
"Bengeworth, Worcestershire, England",
"Stratford, Fairfield, Connecticut, United States",
"",
"Long Island City, Queens, New York, USA",
"",
"Bengeworth, Evesham, Worcestershire, England",
"Windsor, Hartford, Connecticut, United States",
"Hempstead, LI, New York, United States",
"Salem, Salem, New Jersey, USA",
"Gloucester, NJ",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"England",
"Winchester, Hampshire, England",
"",
"Steyning, Sussex, England",
"",
"",
"",
"",
"",
"Malden, Middlesex, Massachusetts, USA",
"Arnold, Nottinghamshire, England",
"Yarmouth, Barnstable County, Massachusetts, USA",
"Arnold, Nottinghamshire, England",
"",
"Dublin, Ireland",
"Cape May, New Jersey, USA",
"Cape May",
"Cold Spring, Cape May, New Jersey",
"",
"",
"",
"Warwickshire, England",
"Bengeworth, Worcestershire, England",
"Bengeworth, Worcestershire, England",
"",
"Seaville, Cape May, NJ",
"Seaville, Cape May, New Jersey, United States",
"",
"",
"",
"",
"",
"",
"Long Island City, Queens, New York, United States",
"",
"",
"Philadelphia, PA",
"",
"",
"Levittown, Bucks Co., PA",
"Nottingham, Chester, Pennsylvania, USA",
"",
"Philadelphia, PA",
"",
"",
"",
"",
"",
"Hempstead, Nassau, New York",
"",
"Camden, NJ, United States",
"",
"",
"",
"Philadelphia, Pennsylvania, USA",
"",
"Easton, Northampton Co., PA",
"",
"",
"",
"Philadelphia, PA",
"",
"Long Island City, Queens, New York, United States",
"Milton, DE",
"",
"Indianapolis, Marion Co., Indiana",
"Salt Lake City, Salt Lake, Utah",
"Hammond, Lake, Indiana, USA",
"Philadelphia, PA",
"",
"Philadelphia, PA",
"",
"East Bradford, Chester, Pennsylvania, United States",
"Thornbury, Chester, Pennsylvania, USA",
"Springfield, Burlington, New Jersey, USA",
"jerusalem, long island ,ny",
"Lincolnshire, England",
"lived Suffolk, England",
"England",
"Wincanton, Somerset, England",
"Cheshire, England",
"Scituate, Plymouth, Massachusetts, United States",
"Lynn, Essex County, Massachusetts, USA",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Woodstown, Salem, New Jersey, USA",
"New Jersey, USA",
"",
"Westmeath, Ireland",
"england",
"Ceshire, England",
"Upton, Buckinghamshire, England",
"St Olave, Bermondsey, Surrey, England",
"Upton, Buckinghamshire, England",
"New Buckenham, Norfolk, England",
"Westtown, Chester, Pennsylvania, USA",
"Haughton, Staffordshire, England",
"Dilhorne, Staffordshire, England",
"",
"Philadelphia, Delaware, Pennsylvania, United States",
"",
"",
"",
"Roslyn, Montgomery, Pennsylvania, USA",
"Tullamore, Kerry, Ireland",
"",
"Hatboro, Montgomery, Pennsylvania, United States",
"Somerset, England",
"",
"",
"Pottstown, Montgomery, Pennsylvania, USA",
"",
"",
"Fritz Burial Ground, Douglass Twp, Berks, PA",
"",
"",
"Morysville, PA",
"Colebrookdale, Berks, Pennsylvania, USA",
"Douglass Twp., Berks Co., PA",
"",
"",
"Pottstown, Montgomery, Pennsylvania, USA",
"",
"Berks, Pennsylvania, USA",
"",
"Allentown, Lehigh County, Pennsylvania, United States of America",
"Berks County, Pennsylvania, USA",
"Emaus, Lehigh, Pennsylvania, USA",
"Wernersville, Berks County, Pennsylvania, United States of America",
"Emmaus, Lehigh County, Pennsylvania, United States of America",
"Maxatawny, Berks County, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"",
"England"
]
Dwr.ScriptLoaded('dwr_db_I_death_place_0.js');
