// This file is generated

P_name_0 = [
", , , England",
", , , France",
", , England",
", , Massachusetts, USA",
", , Virginia, USA",
", Cape May, New Jersey, USA",
", Chester, Pennsylvania, United States",
", Devon, , England",
", Mecklenburg, Virginia, American Colonies",
", Oxfordshire, England",
", Warwickshire, , England",
",, Ipswich, England",
"(7) W. Nottingham, Chester, PA, USA",
"157 Capel St",
"1661089, Devon, England",
"1673104, Oxfordshire, England",
"1766 Norris St.",
"807 kings hwy south cherry hill, nj",
"Aachen, Reichsstad, Germany",
"Aaronsburg, Centre, Pennsylvania",
"Aaronsburg, Centre, Pennsylvania, USA",
"Aaronsburg, Pennsylvania, USA",
"Abbey,Saint Albans,Hertford,England",
"Aberdeen, Aberdeen City, Scotland",
"Aberdeenshire & Kincardineshire - Protocol Book of Sir John Christisone, 1518-1551",
"Aberdeenshire, Scotland",
"ABERDEENSHIRE, SCOTLAND",
"Abernethy, Perthshire, Scotland",
"Abington Hospital",
"Abington, Montgomery, PA, United States",
"Abington, Montgomery, Pennsylvania, United States",
"Abington, Montgomery, Pennsylvania, USA",
"Abington, Pennsylvania, United States",
"Access Control Experts, Inc.",
"Acre, Hatzafon (Northern District), Israel",
"Aix-en-Provence, Departement des Bouches-du-Rh\u00f4ne, Provence-Alpes-C\u00f4te d'Azur, France",
"Ajax Paving",
"Aldingham, Lancashire, England",
"All Saints Church, Derby, Derbyshire, England",
"All Saints Parish, Derby, Derbyshire, England",
"All Saints Parish, Derby, England",
"All Saints Parish, Derbyshire, England",
"All Saints Parrish, Derby, Derbyshire, England",
"All Saints, Derby, Derby, England",
"All Saints, Derby, Derbyshire, England",
"Allentown, Lehigh County, Pennsylvania, United States of America",
"Allentown, Lehigh, Pennsylvania, USA",
"Allentown, Pennsylvania, USA",
"Alnwick, Northumberland Unitary Authority, Northumberland, England",
"Alsace, France",
"Altena, Germany",
"Altena, M\u00e4rkischer Kreis, North Rhine-Westphalia, Germany",
"Altyre, Morayshire, Scotland",
"Amazing Tree, LLC",
"Ambler, Montgomery, PA, United States",
"Ambler, Pennsylvania, United States",
"America",
"Amesbury, Essex, Massachusetts, United States",
"Amesbury, Wiltshire Unitary Authority, Wiltshire, England",
"Amesbury, Wiltshire, England",
"Amiens, Somme, Picardie, France",
"Amington, Staffordshire, England",
"Anchorage, Alaska, United States",
"angus, scotland",
"Angus, Scotland",
"Angusshire, Scotland",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"AnjouPays-de-la-Loire, France",
"Anne Arundel County, Maryland, USA",
"Appleby-in-Westmorland, Cumbria, England",
"Aquitaine, France",
"Arbuthnott, Kincardineshire, Scotland",
"Arcadia University",
"Ardeley, Hertfordshire, England",
"Ardmore Ave Elementary",
"Ardsley, Pennsylvania, United States",
"Argyll, Scotland",
"Aries, Hautes-Pyr\u00e9n\u00e9es, Midi-Pyr\u00e9n\u00e9es, France",
"Arkel, Z-H, Holland, Netherlands",
"Armsberg, Germany",
"Armstrong County, Pennsylvania, USA",
"Arnold, Nottinghamshire, , England, ",
"Arnold, Nottinghamshire, England",
"Arnsberg, Germany",
"Arque, Seine Inferiere, Normandy, France",
"Arques, Seine Inferieure, Normandy, France",
"Arques, Seine-Maritime, Haute-Normandie, France",
"Arras, Hautes-Pyr\u00e9n\u00e9es, Midi-Pyr\u00e9n\u00e9es, France",
"Arundel, Arun District, West Sussex, England",
"Arundel, Sussex, England",
"as a prisoner accused of witchcraft, Peel Castle, Isle of Man, England",
"as her 2nd husband",
"Ashby-de-la-Zouch, North West Leicestershire District, Leicestershire, England",
"Ashford, Kent, England",
"Astley, Worcestershire, England",
"Astley,Worcester,England",
"Aston, Delaware, Pennsylvania, USA",
"Atherton, Lancashire, England",
"Atlantic, New Jersey",
"Audubon, Camden, NJ, United States",
"Aumale, Seine-Maritime, Haute-Normandie, France",
"Aunou, Orne, Basse-Normandie, France",
"Austin Friars,london,middlesex,england",
"Auvergne, France",
"Auxerre, Yonne, Bourgogne, France",
"Awilscombe, Devon, England",
"Awliscombe, Devon, England",
"Awliscombe, Devonshire, England",
"Ayrshire, Scotland",
"Ayrshire, Scotland, Ardrossan",
"Baddesley Clinton Manor, Warwick, Warwickshire, England",
"Baddesley Clinton, Warwickshire, , England",
"Baddesley Clinton, Warwickshire, England",
"Badenoch, Inverness-shire, Scotland",
"Badlesmere, Swale Borough, Kent, England",
"Balgonie, Scotland",
"Baltimore, Maryland",
"Baltimore, Maryland, United States",
"Baltimore, Maryland, USA",
"Bamberg Castle, Bamberg, Franken, Bayem, Germany",
"Bamberg, Germany",
"Bampton (Devonshire) England, Church",
"Banbury, Oxfordshire, England",
"Bank of America",
"Barnstable, Barnstable, Massachusetts, United States",
"Barrington, Camden, New Jersey, USA",
"Barrington, NJ",
"Barwick, Somerset, England",
"basford, Nottingham, Nottinghamshire, England",
"Basing, Hampshire, England",
"Basset, Leicester, Leicestershire, England",
"Bathgate Castle, West Lothian, Scotland",
"Battle Creeek, Kalamazoo, Michigan, United States",
"Baunton, Devon, England",
"Bavaria, , Bayern, Germany",
"Bayern, Staudach-Egerndach, Traunstein, Oberbayern, Bavaria, Germany",
"Bayeux, Calvados, Basse-Normandie, France",
"Bayeux, de, Evreux, Eure, Haute-Normandie, France",
"Baynard, Essex, England",
"Bayonne, Departement des Pyr\u00e9n\u00e9es-Atlantiques, Aquitaine, France",
"Beaudefert, Staffordshire, England",
"Beaugency, Loiret, Centre, France",
"Beaulieu, New Forest District, Hampshire, England",
"Beaumaris, Isle of Anglesey, Wales",
"beaumont-les-nonains, Oise, Picardie, France",
"Beauvois-en-Vermandois, Aisne, Picardie, France",
"Beckermet, Cumberland, England",
"Bedford, Bedfordshire, England",
"Bedford, Lawrence, Indiana, USA",
"Beimbach u. Brettheim, W\u00fcrttemberg, Deutschland",
"Bel Air, Harford, Maryland, United States",
"Bellencombre, Seine-Maritime, Haute-Normandie, France",
"Bellmawr, New Jersey, USA",
"Bellmawr, NJ",
"Belton, Uppingham, Rutland, England",
"Benenden, Kent, England",
"Bengeworth, Evesham, Worcester, England",
"Bengeworth, Evesham, Worcestershire, England",
"Bengeworth, Worcestershire, England",
"Bengeworth, Worchester, England, England",
"Berg , Germany",
"Berg, Germany",
"Berkeley, Gloucestershire, , England",
"Berkeley, Stroud District, Gloucestershire, England",
"Berkhamsted, Dacorum Borough, Hertfordshire, England",
"Berks Co, Pennsylvania",
"Berks Co., PA",
"Berks Co., Pennsylvania",
"Berks County, Pennsylvania",
"Berks County, Pennsylvania ",
"Berks County, Pennsylvania, United States of America",
"Berks County, Pennsylvania, USA",
"Berks, Pennsylvania, USA",
"Berkshire Parish, Wiltshire, England",
"Bershire Parish, Wiltshire, England",
"Berwick St John's, Cranborn Chase, Dorsetshire, Olde England",
"Bescote (Staffordshire) Gb",
"Bescote, Staffordshire, England",
"Bethlehem, leigh, Pennsylvania, United States",
"Beverly, Essex, Massachusetts, United States",
"Biggar, Lanarkshire, Scotland",
"Bilinghurst, Sussex, England",
"Billerica, Middlesex, Massachusetts Bay Colony, British Colonial America",
"Birkes House, , , England",
"Birkes House, Scaftworth, Notthinghamshire, England",
"Birlingham, Worcestershire, England",
"Birmensdorf, , Z\u00fcrich, Switzerland",
"Birmensdorf, Zurich, Switzerland",
"Birmingham, Warwickshire, England",
"Bishop McDevitt ",
"Bishop's Itchington, Warwickshire, England",
"Bishops, Stortford, Hertfordshire, England",
"Blackburn, Lancashire, England",
"Blandijnberg, Ghent. East Flanders Belgium",
"Bloomsburg University",
"Bolbec, Pays de Caux, Haute-Normandie, France",
"Bolney Church, Sussex County, England",
"Bolney, Sussex County, England",
"Bolney, Sussex, , England",
"Bolney, Sussex, England",
"Bolton-le-Sands, City of Lancaster, Lancashire, England",
"Boothwyn, Delaware, PA, United States",
"Bordeaux, Departement de la Gironde, Aquitaine, France",
"Boreham, Chelmsford Borough, Essex, England",
"Boston, Massachusetts, USA",
"Boston, Suffolk, Massachusetts",
"Boston, Suffolk, Massachusetts, United States",
"Boston, Suffolk, Massachusetts, USA",
"Boughton Monchelsea, Kent, England",
"Boulogne, Hauts-de-Seine, \u00cele-de-France, France",
"Boulogne, Vend\u00e9e, Pays de la Loire, France",
"Bound Brook, Somerset County, New Jersey, US",
"Bound Brook, Somerset, New Jersey, USA",
"Bourne, South Kesteven District, Lincolnshire, England",
"Bourneville, Eure, Haute-Normandie, France",
"Boynton Beach, Palm Beach, Florida, United States",
"Brackley, South Northamptonshire Borough, Northamptonshire, England",
"Branxton, Northumberland, England",
"Brasenhill, Cheshire, England",
"Brasenhill, Chester, England",
"Brattleby, Lincolnshire, England",
"breadalbane, Perthshire, Scotland",
"Brechin, Angus, Scotland",
"Bremen",
"Bretagne, Landes, Aquitaine, France",
"Bretten, Karlsruhe, Baden-Wuerttemberg, Germany",
"Brettenham, Suffolk, England",
"bridgen, of, Lintrathen, Angus, Scotland",
"Bridgen, of, Lintrathen, Angus, Scotland",
"Bridgeton City, Cumberland, New Jersey",
"Bridgeton, New Jersey, USA",
"Bridgewater State College",
"Bridgewater State College, MA",
"Bridgewater, Plymouth, Massachusetts, United States",
"Bristol Parish, Brunswick County, Virginia, USA",
"Bristol, Gloucestershire, , England",
"Brittainy, Normandy, France",
"Bromham, Wiltshire, England",
"bromscraft, England",
"Broncroft Castle, Tugford, Shropshire, England",
"Bronscroft Castle, Shropshire, England",
"Bronscroft, Shropshire, England",
"Brooklawn, NJ, United States",
"Brooklyn, New York",
"Broomscroft, Shropshire, England",
"Brooznell, Chester, Pennsylvania, United States",
"Brotherton, Selby District, North Yorkshire, England",
"Brough Castle, Westmoreland, England",
"Broughton, Kent, England",
"Brunswick Co., Virginia, United States",
"Brunswick County, Virginia, USA",
"Brunswick, Virginia, United States",
"Bruton, Somerset, England",
"Buckinghamshire, England",
"Buckinghamshire, Suffolk, England",
"Bucks County, Pennsylvania",
"Bucks, Pennsylvania, United States",
"Bulmer, Essex, England",
"Bulstrode, Buckinghamshire, England",
"Burbank, LA, California, United States",
"Bures St Mary, Suffolk, England",
"Burford, Shropshire Unitary Authority, Shropshire, England",
"Burgh by Sands, Cumberland, England",
"Burgh-by-Sands, City of Carlisle, Cumbria, England",
"Burgos, Provincia de Burgos, Castilla y Le\u00f3n, Spain",
"Buried: St. Peter and St. Paul Churchyard; Wincanton, Somerset, England",
"Burley, Hampshire, England",
"Burlington County, New Jersey, USA",
"Burlington, Burlington, NJ, Colonial America",
"Burlington, New Jersey",
"Burlington, New Jersey, United States",
"Burr Abbaye De St Vincent, Paris, Ile-De-France, France",
"Burstwick, East Riding of Yorkshire Unitary Authority, East Riding of Yorkshire, England",
"Burton upon Trent, Staffordshire, Kingdom of England",
"Burton, Yorkshire, England",
"Bury St Edmunds, St Edmundsbury Borough, Suffolk, England",
"Bute, Scotland",
"Bycot, Oxforshire",
"Cadogan, Armstrong, Pennsylvania",
"Cadogan, Armstrong, Pennsylvania, USA",
"Cadzow Castle, Hamilton, Lanark, Scotland",
"Caen, Calvados, Basse-Normandie, France",
"Caernarfon, Gwynedd, Wales",
"Caistor, Lincolnshire",
"California, USA",
"Camberwell, London Borough of Southwark, Greater London, England",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"Cambridge, Gloucestershire, England",
"Cambridge, Middlesex, Massachusetts, USA",
"Camden",
"Camden Camden County NJ USA",
"Camden CO, New Jersey",
"Camden County, New Jersey, USA",
"Camden North Ward, Camden, New Jersey, USA",
"Camden Ward 10, Camden, New Jersey, USA",
"Camden Ward 4, Camden, New Jersey, USA",
"Camden Ward 5, Camden, New Jersey, USA",
"Camden, Camden County, New Jersey, United States",
"Camden, Camden, New Jersey",
"Camden, Camden, New Jersey, United States",
"Camden, Camden, New Jersey, USA",
"Camden, N J",
"Camden, New Jersey",
"Camden, New Jersey, United States",
"Camden, New Jersey, USA",
"Camden, NJ",
"Camden, NJ, United States",
"Canon Court Manor, Ulcombe, Kent, England",
"Canterbury, City of Canterbury, Kent, England",
"Canterbury, Kent, England",
"Canton Berne, Old Swiss Confederation (now Swiss Confederation)",
"Cape May",
"Cape May County, New Jersey",
"Cape May County, New Jersey, Colonies",
"Cape May County, New Jersey, United States",
"Cape May County, NJ",
"Cape May Courthouse, Cape May, New Jersey",
"Cape May Courthouse, Cape May, New Jersey, USA",
"Cape May, Cape May County, New Jersey, United States of America",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, USA",
"Cape May, Cape May, NJ, USA",
"Cape May, New Jersey, United States",
"Cape May, New Jersey, USA",
"Cape May, NJ",
"Cape May,Cape May,New Jersey,USA",
"Cape May,New Jersey, Colonies",
"Cape May,New Jersey,USA",
"Carlisle, Cumbria, England",
"Carltonrode, Norfolk, England",
"Carnhill, Aberdeenshire, Scotland",
"Carthago",
"Caskieben, ABER, Scot.",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Castle Acre, Norfolk, England",
"Castle Ashby, South Northamptonshire Borough, Northamptonshire, England",
"Castle Donington, Leicestershire, England",
"Castle Dunbar, East Lothian, Scotland",
"Castle Groby, Leicester, Leicestershire, England",
"castle, Forbes, Aberdeenshire, Scotland",
"Catham, Barnstable, MA",
"Cecil, Maryland, United States",
"Cedarville, NJ, United States",
"Ceshire, England",
"Champagne-Ardenne, France",
"Charlestown, Massachusetts",
"Charleton Musgrave, Somerset, England",
"Charlto-Musgrove, Somerset, England",
"Charlton Musgrove, South Somerset District, Somerset, England",
"Charlton, Somerset, , England",
"Chartley, Staffordshire, , England",
"Chasseneuil-sur-Garonne, France",
"Chateau Landon, Seine-et-Marne, \u00cele-de-France, France",
"Chateau, Eure-et-Loir, Centre, France",
"Chatham, Barnstable, Massachusetts -LOST AT SEA",
"Chatham, Barnstable, Massachusetts, USA",
"Chellaston, Derbyshire, England",
"Cheltenham, Gloucestershire, England",
"Chepstow Wales",
"Chepstow, Monmouthshire, Wales",
"Cherry Hill West",
"Cherry Hill, Camden County, New Jersey, United States of America",
"Cherry Hill, Camden, New Jersey, USA",
"cherry hill, New Jersey, United States",
"Cherry Hill, New Jersey, United States",
"Cherry Hill, NJ",
"Cherry Hill, NJ, United States",
"Chertsey, Surrey, England",
"Chesham, Buckinghamshire, England",
"Cheshire, England",
"Chester Co., Pennsylvania",
"Chester, Cheshire, England",
"Chester, Newton, PA",
"Chester, PA",
"Chester, Pennsylvania",
"Chester, Pennsylvania, British Colonial America",
"Chester, Pennsylvania, United States",
"Chesterfield, Burlington, New Jersey, USA",
"Chestnut Hill, Pa, United States",
"Chew Magna, Somerset, England",
"Chicago, Cook County, Illinois, United States",
"Chicago, Illinois, United States",
"Chichester, Chichester District, West Sussex, England",
"Chilham, Ashford Borough, Kent, England",
"Chillesford, , Suffolk, England",
"Chinon, Indre-et-Loire, Centre, France",
"Christ the King",
"Church, Wetzel, West Virginia, United States",
"Cibalis Pannonie",
"Cinnaminson, Burlington, New Jersey, USA",
"Clare, St Edmundsbury Borough, Suffolk, England",
"Clarksboro, Gloucester, New Jersey, United States",
"Clarksboro, New Jersey, United States",
"Clayton, Gloucester Co., New Jersey",
"Clayton, Gloucester, New Jersey, USA",
"Clayton, Johnston County, NC, United States",
"Clayton, Johnston County, North Carolina, United States",
"Cleveland, Yorkshire, , England",
"Cleves, Germany",
"Clinton, Warwickshire, England",
"Clondrohid, Cork, Ireland",
"Clyst St George, Devon, England",
"Cochem, Cochem-Zell, Rheinland-Pfalz, Germany",
"Cold Spring, Cape May, New Jersey",
"Cold Spring, Cape May, New Jersey, United States",
"Colebrookdale, Berks, Pennsylvania, USA",
"Collegeville, Montgomery, Pennsylvania, United States",
"Collieston, Aberdeenshire, Scotland",
"Collingswoo, NJ, United States",
"Collingswood High School",
"Collingswood Junior High School",
"Collingswood, Camden, New Jersey, United States",
"COllingswood, Camden, New Jersey, United States",
"Collingswood, Camden, New Jersey, USA",
"Collingswood, New Jersey, United States",
"Collingswood, New Jersey, USA",
"Collingswood, NJ",
"Collingswood, NJ, United States",
"Colonial Era, Westmoreland, Virginia, USA",
"Colonies (USA)",
"Colorado Springs, Co",
"Colorado Springs, CO, United States",
"Colorado Springs, El Paso County, CO, United States",
"Colyton, Devon, England",
"Concord, Chester, Pennsylvania, United States",
"Connecticut, USA",
"Conquereuil, Loire-Inferierure, Bretagne, France",
"Constantinople, Istanbul, Turkey",
"County Offaly, Ireland",
"Covenham St. Mary, Lincoln, England",
"Coxwold, Hambleton District, North Yorkshire, England",
"Cranborn Chase, Dorset, England",
"Craven, North Carolina, United States",
"Crawford, Lanarkshire, Scotland",
"Crawne, Wiltshire, England",
"Crediton, Devon, , England",
"Crediton, Devon, England",
"Crepon, Calvados, Lower Normandy, France",
"Crewkerne, Somerset, England",
"Cropredy, Oxfordshire, England",
"Cropredy, Oxfordshire, England, United Kingdom",
"Crossing the pass at Brides-les-Bains, Rhone-Alpes, France",
"Crosswicks, Burlington, New Jersey, USA",
"Croydon, St John, Surrey, England",
"Cumberalnd Co., New Jersey",
"Cumberland Co., New Jersey",
"Cumberland, Cumberland, New Jersey, United States",
"Cumberland, England",
"Cumberland, New Jersey, United States",
"Cumberland, New Jersey, USA",
"Cupar, Fife, Scotland",
"Cushnie, Aberdeenshire, Scotland",
"Darby, Delaware, PA, United States",
"Darby, Delaware, Pennsylvania, United States",
"Daretown, Salem, New Jersey",
"Daretown, Salem, New Jersey, United States",
"Datchworth, Hertfordshire, , England",
"Dauiot Aberdeen, Kincardineshire, Scotland",
"Daventry District, Northamptonshire, England",
"Death Place: England Cemetery: Church of the Annunciation of St. Mary Burial or Cremation Place: Leicester, Leicester Unitary Authority, Leicestershire, England",
"Death Place: Leicester, Leicester Unitary Authority, Leicestershire, England Cemetery: Church of the Annunciation of St. Mary Burial or Cremation Place: Leicester, Leicester Unitary Authority, Leicestershire, England",
"Death Place: Staffordshire, England Cemetery: Saint Paul's Cathedral Burial or Cremation Place: London, City of London, Greater London, England",
"Deborah NJ",
"Deddington, Oxfordshire, England",
"Delaware",
"Delaware, Pennsylvania",
"Dennisville, Cape May, New Jersey",
"Dennisville, Cape May, New Jersey, United States",
"Departement de la Haute-Loire, Auvergne, France",
"Deptford",
"Deptford, Gloucester, New Jersey, United States",
"Derby, Derbyshire or Westmoreland, England",
"Derby, Derbyshire, England",
"Derby, Derbyshire, Kingdom of England",
"Derby, England",
"Derbyshire, England",
"Derbyshire, Kingdom of England",
"Derbyshire: - Registers of Marriages, 1558-1837a",
"Dethick Norbury, Derbyshire, England or Tamworth Castle, Tamworth, Staffordshire, England",
"Devon, England",
"Devonshire, England",
"Dilhorne, Staffordshire, England",
"Diseworth, Leicestershire, England",
"Diseworth, Leichester, England",
"District Twp., Berks Co., PA",
"District, Berks, Pennsylvania, USA",
"Dividing Creek, Cumberland, New Jersey, United States",
"Dividing Creek, Cumberland, New Jersey, USA",
"Dividing Creek, New Jersey",
"Dividing Creek, NJ",
"Donegal Ireland",
"Donegal, Ireland",
"Donnyat, Somerset, England",
"Donnyat, Somersetshire, England",
"Dorset County, Eng.",
"Dorset, England",
"Douai, Nord, Nord-Pas-de-Calais, France",
"Douglas, Berks, Pennsylvania, USA",
"douglas, castle, Lanarkshire, Scotland",
"douglas, Lanarkshire, Scotland",
"Douglass Township, Berks, Pennsylvania, USA",
"Douglass Twp, Berks Co, PA",
"Douglass Twp., Berks Co., PA",
"Douglass, Berks, Pennsylvania, USA",
"Dover, Strafford, New Hampshire, USA",
"Doveridge, Doveridge, Derbyshire, England",
"Downe Twsp.,Cumberland,New Jersey,USA",
"Downe, Cape May, New Jersey, USA",
"Downe, Cumberland, New Jersey, United States",
"Downe, Cumberland, New Jersey, USA",
"Downe, Cumberland,New Jersey",
"Downe, New Jersey, USA",
"Downe,Cumberland, New Jersey",
"Downingtown, PA, United States",
"Doylestown, Bucks, Pennsylvania, United States",
"Drexel University / College of Bomedical Engineering",
"Dublin, Dublin, Ireland",
"Dublin, Ireland",
"Dunbar, East Lothian, Scotland",
"dunbar, haddingtonshire, scotland",
"Dundonald, Ayrshire, Scotland",
"Dundonald, Castle, Ayrshire, Scotland",
"Dunfermline Abbey",
"Dunfermline, Fife, Scotland",
"Dunnottar, Kincardineshire, Scotland",
"Durham, Northumberland, England (killed by Northumbrians)",
"Dursley, Gloucestershire, England",
"East Bradford Twp., Chester Co., Pennsylvania",
"East Bradford, Chester, Pennsylvania, United States",
"East Bradford, Chester, Pennsylvania, USA",
"East Guilford, New Haven, Connecticut, USA",
"East Hampsett, Sussex, England",
"East Hampton, Livingston, New York, United States",
"East Hampton, Middlesex, Connecticut, United States",
"East Hampton, Suffolk County, New York, United States of America",
"East Hampton, Suffolk County, New York, USA",
"East Hampton, Suffolk, New York",
"East Hampton, Suffolk, New York, United States",
"East Hampton, Suffolk, NY, USA",
"East Nottingham, Chester, Pennsylvania, USA",
"East Peckham, Kent, England",
"East Texas, Lehigh, Pennsylvania, USA",
"Eastchurch, Kent, England",
"Eastchurch, Swale Borough, Kent, England",
"Eastham, Barnstable, Massachusetts, USA",
"Easthampton, Long Island, Suffolk, NY, USA",
"Easthampton, Suffolk, New York",
"Easthampton, Suffolk, New York, United States",
"Easton, Northampton Co., PA",
"Eaton, Nottinghamshire, England",
"Eaton, Nottinghamshire,England",
"Eboracum, Yorkshire, England",
"Edgecombe County, North Carolina, USA",
"Edgmont, Chester, Pennsylvania, USA",
"Edinburgh Castle, Midlothian, Scotland",
"Edinburgh, Midlothian, , Scotland",
"Edinburgh, Midlothian, Scotland",
"Edinburgh, Midlothian, Scotland, United Kingdom",
"Egg Harbor City, Atlantic, New Jersey, USA",
"Egg Harbor, Cape May, New Jersey, United States",
"Egmond, Noord-Holland, Netherlands",
"Elizabeth City, , Virginia, USA",
"Elizabethtown, NJ",
"Elmer, NJ, United States",
"Elmer, Salem, New Jersey, USA",
"Elmley Castle, Wychavon District, Worcestershire, England",
"Elstead,Surrey,England",
"Emaus, Lehigh, Pennsylvania, USA",
"Emmaus, Lehigh County, Pennsylvania",
"Emmaus, Lehigh County, Pennsylvania, United States of America",
"Emmaus, Lehigh County, Pennsylvania, USA",
"Emmaus, Lehigh, Pennsylvania, USA",
"En",
"EN",
"england",
"England",
"England ",
"England Earl, Sussex, England",
"England, United Kingdom",
"Enkirch, Bernkastel-Wittlich, Rheinland-Pfalz, Germany",
"Ermington, Devon, England",
"Errol, Perthshire, Scotland",
"erroll, Perthshire, Scotland",
"Essex County, New Jersey, US",
"Essex, England",
"Essex, Virginia, United States",
"Est, , , England",
"Evangelisch-Lutherische, Bergen Birkenfeld, Pfalz, Bavaria",
"Evangelisch, Winningen, Rheinland, Prussia",
"Evesham, Worcestershire, England",
"Evreux, Eure, Haute-Normandie, France",
"Fa",
"Falaise, Calvados, Basse-Normandie, France",
"Falmouth, Massachusetts, United States",
"Fardell Manor, Ivybridge, Devon, England",
"Fareham, Hampshire, England",
"Fearn, Ross-shire, Scotland",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"Fenzensac, France",
"Ferbane, County Offaly or Pollagh, Galway, Ireland",
"Fezensac, Gascony, France",
"Fife, Scotland",
"Finella's Castle, Fettercairn, Kincardineshire, Scotland",
"Finlaggan Castle, Isle of Islay, Argyll, Scotland",
"Firle Church, Sussex, England",
"Firle, Sussex, England",
"Fishing Creek, Cape May, New Jersey, United States",
"Fishing Creek, Cape May, New Jersey, USA",
"FL, United States",
"Flamstead, Hertfordshire, England",
"Flanders, Belgium",
"Flanders, Boulogne, Alsace, France",
"Flanders, Nord, Nord-Pas-Calais, France",
"Fl\u00e8che, Sarthe, Pays de la Loire, France",
"Fleetwood, Lehigh, Pennsylvania, USA",
"Fleury-Ouche-Anjou, Pay-de-la-Loire, France",
"Fleury-sur-Ouche",
"Flushing, Queens, New York, United States",
"Fontevrault, Maine-et-Loire, Pays de la Loire, France",
"Fonthill, Sussex, England",
"Ford City, Pennsylvania, USA",
"Forfar shire, Scotland",
"Forfar, Angus, Scotland",
"Fort Defiance, Happy Valley Wilkes, North Carolina, USA",
"Fort Defiance, Wilkes, North Carolina, United States",
"Fort Washington",
"France",
"Franciscan Missionary Union",
"Frankenthal Evangelical Church, Heuchelheim, Bayern, Germany ",
"Frankfurt am Main, Hesse, Germany",
"Frankfurt, Germany",
"franklinville, gloucester, nj, United States",
"Franklinville, New Jersey",
"Frederick, Montgomery, Pennsylvania, United States",
"Frederick, Montgomery, Pennsylvania, USA",
"Freehold, Monmouth, New Jersey",
"Freehold, Monmouth, New Jersey, United States",
"Freehold, Monmouth, New Jersey, USA",
"Freehold, Monmouth, NJ",
"Freudenstadt, Freudenstadt, Baden-Wuerttemberg, Germany",
"Friends Grnd, Movraverty, Drumgorr, Ireland",
"Fringford, Oxfordshire, England",
"Fritz Burial Ground, Douglass Twp, Berks, PA",
"Frome, Somersetshire, England",
"Ft. Lauderdale, Florida, United States",
"Fyvie Castle, Aberdeen, Aberdeenshire, Scotland",
"Fyvie, Aberdeenshire County, Scotland",
"Fyvie, Aberdeenshire, Scotland",
"Gainsborough Hall, Lincolnshire, England",
"Gainsborough, Lincolnshire, England",
"galicia, Poland",
"Gartly, Aberdeenshire, Scotland",
"Gatinais, Loire, Orleanais/Centre france",
"Gatinais, Loiret, Centre, France",
"Gb",
"Germantown, Philadelphia",
"Germantown, Philadelphia County, Pennsylvania, United States of America",
"Germantown, Philadelphia, Pennsylvania, United States",
"Germany",
"Ghent, Arrondissement Gent, East Flanders (Oost-Vlaanderen), Belgium",
"Ghent, East Flanders, Flanders, Belgium",
"Ghent, Flandre Orientale, Belgium",
"Gifford, East Lothian, Scotland",
"Gilbertsville, Montgomery County, Pennsylvania, United States of America",
"Giradow, Poland",
"Glack, Chapel Garioch, Aberdeen, Scotland",
"Glamis Castle, Angus, Forfarshire, Scotland",
"Glenkindle, House, Aberdeen, Aberdeenshire, Scotland",
"glenorchy, Argyll, Scotland",
"Glenside, Montgomery, Pennsylvania, United States",
"Glenwood Elementary",
"Gloucester City, NJ",
"Gloucester, City of Gloucester, Gloucestershire, England",
"Gloucester, Essex Co., MA",
"Gloucester, Essex County, Massachusetts, USA",
"Gloucester, Essex, Massachusetts",
"Gloucester, Essex, Massachusetts, United States",
"Gloucester, Essex, Massachusetts, USA",
"Gloucester, Gloucestershire, England",
"Gloucester, MA",
"Gloucester, Massachusetts",
"Gloucester, New Jersey, United States",
"Gloucester, NJ",
"Gloucestershire, England",
"Gloustershire, England",
"Goshen, Chester, PA",
"Goshen, Chester, Pennsylvania",
"Goshen, Chester, Pennsylvania, United States",
"Goshen, Lancaster, Pennsylvania, United States",
"Grange, Monifieth, Angusshire, Scotland",
"gravenhage, Hollande",
"Great Bentley, Essex, England",
"Great Drayton, Nottinghamshire, , England",
"Great Marlow, Buckinghamshire, , England",
"Great Moorsholm, Skelton-Cleveland, Yorkshire, England",
"Great Moorsholm, Yorkshire, England",
"Great Moorsome, Yorkshire, England",
"Great Saxham, Suffolk, England",
"great saxhams, Suffolk, England",
"Great Yarmouth, Norfolk, ENGLAND",
"Great, Egg, Harlow, New Jersey",
"Greenwich, Gloucester, New Jersey, United States",
"Greenwich, Gloucester, NJ",
"Greenwich, Royal Borough of Greenwich, Greater London, England",
"Grey Friars, Worcestershire, England.",
"Greyfriars, Kirkyard, Edinburgh, Midlothian, Scotland",
"Groby Castle, Leicestershire, England",
"Groby Old Hall, LEI, England",
"Groby, Leicestershire, England.",
"Groombridge, Kent, England",
"Groombridge, Speldhurst, Kent, or Parham, Suffolk, England",
"Groombridge,Speldhurst,Kent,England",
"Groomsbridge Manor, Speldhurst, Kent, England",
"Gt. Chesterford, Hertfordshire, England",
"Guilford, New Haven, Connecticut",
"Guilford, New Haven, Connecticut, United States",
"Gwynedd, Wales",
"Haddon Township, NJ",
"Haddon, Camden, New Jersey",
"Haddon, Camden, New Jersey, USA",
"Haddonfield, Camden, New Jersey, USA",
"Hadleigh, Essex, England",
"Hailes, Tewkesbury Borough, Gloucestershire, England",
"Hains Greene, Nottinghamshire, England",
"Halifax, Halifax, North Carolina, American Colonies",
"Halifax, Halifax, North Carolina, United States",
"Halifax, North Carolina, USA",
"Halifax, West Riding, Yorkshire, England",
"Halifax, West Ridng, Yorkshire,England",
"Halifax, Yorkshire, England",
"Hall, Ontario, New York, USA",
"Halland, J\u00e4mtland, Sweden",
"Hambleton, Rutland, England",
"Hamilton, Lanarkshire, Scotland",
"Hamilton, Lanarkshire, Scotland, United Kingdom",
"Hammond, Lake, Indiana, USA",
"Hammondssett/Guilford, New Haven, CT",
"Hampshire, England",
"Hampshire, Shropshire, England",
"Hampstead,Queens,New York,USA",
"Hanes Greane, Bawtry, Nottinghamshire, England",
"Harby, Newark and Sherwood District, Nottinghamshire, England",
"Hardin Co., KY",
"Hardingville, Gloucester, New Jersey, USA",
"Hardwick, Buckinghamshire, England",
"Hartford, Hartford, Connecticut, United States",
"Harwich, Barnstable, Massachusetts, United States",
"Hatboro, Montgomery, Pennsylvania, United States",
"Hatfield Heath, Essex, England",
"Haughton, Stafford, England",
"Haughton, Staffordshire, , England",
"Haughton, Staffordshire, England",
"Haverford, Delaware, Pennsylvania, USA",
"Hebron, Tolland, Connecticut, United States",
"Hedeby, Midtjylland, Denmark",
"Heidelberg, Baden-W\u00fcrttemberg, Germany",
"Heidelburg, Baden Baden, Germany",
"Hellidon, Buckinghamshire, England",
"Hemel Hempstead, Huntingdonshire, England",
"Hempstead, Kings, New York",
"Hempstead, LI, New York, United States",
"Hempstead, LI, New York, USA",
"Hempstead, Livingston, New York, United States",
"Hempstead, Long Island, Kings, NY",
"Hempstead, Long Island, New York, USA",
"Hempstead, Nassau, Long Island, New York, United States",
"Hempstead, Nassau, New York",
"Hempstead, Nassau, New York, United States",
"Hempstead, Nassau, New York, USA",
"Hempstead, Queens, New York",
"Hempstead, Queens, New York, United States",
"Heraklion, Greece",
"Hereford, Herefordshire Unitary Authority, Herefordshire, England",
"Herefordshire, England",
"Hermiston, Midlothian, Scotland",
"Herricks, Nassau, Long Island, New York USA",
"Hertford, Hertfordshire, England",
"Hertfordshire, England",
"Heuchelheim, Bamberg, Bayern, Germany",
"Hill Bishop, Somerset, England",
"hill, western, Australia",
"Hillesden, Buckinghamshire, England",
"Hitcham, Cosford, Suffolk, England",
"Hitcham, England",
"Hitcham, Suffolk, England",
"Hitchin, Hertfordshire, England",
"Hollington, Sussex, , England",
"Holy Cross High School",
"Holyrood, Palace, Edinburgh, Midlothian, Scotland",
"Homestead, Long Island",
"Hopewell, Independent Cities, Virginia, United States",
"Horsham, Sussex, England",
"Hortencie, New Jersey, United States",
"Hortensia, Monmouth, New Jersey",
"Houghton,,Staffordshire,England",
"Hundon, Suffolk, England",
"Huntingdon, Huntingdonshire, England",
"huntley, Aberdeenshire, Scotland",
"Huntly, Aberdeenshire, Scotland",
"Hurstpierpoint, Sussex, England",
"I\u2019ll-et-villainess, Brittany, France",
"IJsselmonde, Rotterdam, Zuid-Holland, Netherlands",
"Ijsselstein, Utrecht, Netherlands",
"Imperial Frankish Court in Aachen",
"Inchmohomo, Scotland",
"Indiana, Indiana, Pennsylvania, USA",
"Indiana, United States",
"Indianapolis, Marion Co., Indiana",
"Ingelheim, Germany",
"Ingelheim, Germany (buried in Metz, France)",
"Innermeath,, Scotland",
"Inverness-shire, Scotland",
"Iona, Argyll, Scotland",
"Ipswich, Essex, Massachusetts",
"Ipswich, Essex, Massachusetts, United States",
"Ipswich, Essex, Massachusetts, USA",
"Ipswich, Suffolk, England",
"ireland",
"Ireland",
"italy",
"Italy",
"Italy (one source said Russia but I think it was transcribed wrong)",
"Itchell, Hampshire, England",
"Ivrea, Torino, Piemonte, Italy",
"Jacksonville, Duval, Florida, USA",
"Jamaica, Long Island, New York",
"Jamaica,Livingston,New York,USA",
"Jamaica,Long Island,New York,USA",
"James City, Virginia, United States",
"Jedburgh, Roxburghshire, Scotland",
"Jefferson, Alexandria, Virginia, United States",
"Jenkintown, Montgomery, Pennsylvania, USA",
"jerusalem, long island ,ny",
"Jerusalem, Palestine",
"Jupille , Belgium",
"Jupille, Belgium",
"Jury List, Salem County, NJ",
"Jutland, Denmark",
"Kaighn Point, Camden, NJ",
"Kelso, Roxburghshire, Scotland",
"Kelso, Sutherland, Scotland",
"Kensington, Philadelphia, Pennsylvania, USA",
"Kent County, England",
"Kent, England",
"Kentisbeare, Devon, England",
"Keynsham, Bath and North East Somerset Unitary Authority, Somerset, England",
"Keynsham, Bath and North East Somerset Unitary Authority, Somerset, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"Kilkenny, Ireland",
"killed in battle of Halidon Hill",
"Kilmarnock, Ayreshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Renfrewshire, Scotland",
"Kilmaurs, Ayrshire, Scotland",
"Kilnaleck, Cavan, Ireland",
"Kincardineshire, Scotland",
"Kinfare, Stafford, Staffordshire, England",
"Kingdom of England",
"Kingdom, of, the, isles, Scotland",
"KIngs Co. Offaly, Ireland",
"Kings County (Brooklyn), New York, United States of America",
"Kingston upon Soar, Nottinghamshire, England",
"Kingston, Washington, Rhode Island, USA",
"Kirkcudbrightshire, Scotland",
"Kirkintilloch, Dunbartonshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kittery, York, Maine, USA",
"Kleve, Rheinland, Prussia",
"Kyle, Ayrshire, Scotland",
"Lacock Abbey, Wiltshire, England",
"lahngau, Germany",
"Lamborne Wodlnds,Berkshire Parish,Wiltshire,England",
"Lamborne, Wodlands, Berkshire, Wiltshire, England",
"Lambourn,Berkshire,England",
"Lanarkshire, Scotland",
"Lancashire, England",
"Lancaster Co, Pennsylvania",
"Lancaster, City of Lancaster, Lancashire, England",
"Lancaster, England",
"Lancaster, Lancashire, England",
"Landsall, Sussex, England",
"Lanesville, Essex, Massachusetts, United States",
"langerak, Z-H Holland, Netherlands",
"Langhorne, Pennsylvania, United States",
"Lansdowne Aldan HS",
"Lansdowne, Delaware, Pennsylvania, United States",
"Lapford, Devon, England",
"LaSalle",
"Laufen, Berchtesgadener Land, Bavaria, Germany",
"Laughton, Sussex, England",
"Lay-Saint-Christofe, France",
"Le Mans, Sarthe, Pays de la Loire, France",
"Leabeg, Ferbane, County Offaly or Pollagh, Galway, Ireland (died of pneumonia)",
"Leeds Castle, Canon Court Manor, Ulcombe, Kent, England",
"Leicester, Leicester Unitary Authority, Leicestershire, England",
"Leicester, Leicester Unitary Authority, Leicestershire, England Cemetery: Saint Paul's Cathedral Burial or Cremation Place: London, City of London, Greater London, England",
"Leicester, Leicestershire, England",
"Leicestershire, England",
"LeMans, Sartre, Maine-et-Loire, Pays de la Loire, France",
"Lenawee, Michigan",
"Lens, Artois, Flemish region, Holy Roman Empire",
"Lens, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Leptis Magna, Africa",
"Leuven, Flemish Brabant, Flanders, Belgium",
"Levittown, Bucks Co., PA",
"Lewes, Lewes District, East Sussex, England",
"Lewes, Sussex, England",
"Lewistown, Mifflin, Pennsylvania, USA",
"leys, kincardine, Scotland",
"Licily",
"Lille, Nord, Nord-Pas-de-Calais, France",
"Limerick, Montgomery, Pennsylvania, United States",
"Limestone, Maine, United States",
"Limpsfield, St Peter, Surrey, England",
"Lincoln, City of Lincoln, Lincolnshire, England",
"Lincolnshire, England",
"Lincolnshire, England, United Kingdom",
"Lintrathen, Angus, Scotland",
"Little Britain, Lancaster, Pennsylvania, USA",
"Little Dunmow, Essex, England",
"Little Easton, Uttlesford District, Essex, England",
"Little Eaton, Ess, England",
"Little Eaton, Essex, England",
"Little Egg Harb, Burlington, New Jersey, United States",
"Little Egg Harbor Twp, Burlington County, NJ",
"Little Egg Harbor, Burlington, New Jersey, USA",
"Little Egg Harbor, Ocean, New Jersey, United States",
"Little Egg Harbor, Ocean, New Jersey, USA",
"lived Suffolk, England",
"Liverpool and Londonderry",
"Llanthony, Monmouthshire, Wales",
"Lobdengau, Germany",
"Lobith, Rijnwaarden, Gelderland, Netherlands",
"Lochorwort Castle, Gorebridge, Midlothian, Scotland",
"Logiealmond, Perthshire, Scotland",
"Logy Almond,,Perth,Scotland    ",
"London, City of London, Greater London, England",
"London, City of London, Greater London, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"London, England",
"London, London, England",
"London, middlesex, england",
"Long Island City, Queens, New York",
"Long Island City, Queens, New York, United States",
"Long Island City, Queens, New York, USA",
"Long Island, Nassau, New York, United States",
"Long Island, New York",
"Long Island, New York, United States",
"Long Island, Suffolk, New York, United States",
"Longford,Derby,Eng",
"Longswamp, Berks County, Pennsylvania, United States of America",
"Longswamp, Berks, Pennsylvania, USA",
"Longtown, City of Carlisle, Cumbria, England",
"Longueville, Normandy, France",
"Lorne, Argyll and Bute, Scotland",
"Lorraine, France",
"Lot-et-Garonne, Aquitaine, France",
"Loth, Sutherland, Scotland",
"Lower Alloways Creek, Salem, New Jersey, USA",
"Lower, Cape May County, NJ  (weaver)",
"Lumberton, New Jersey, United States",
"Lurgan, Armagh, Ireland",
"Lurgan, Armagh, Northern Ireland",
"Luton, Luton Borough, Bedfordshire, England",
"Lynn, Essex Co., MA",
"Lynn, Essex County, Massachusetts, USA",
"Lynn, Essex County. Massachusetts Bay Colony",
"Lynn, Essex, Massachusetts, United States",
"Lynn, Essex, Massachusetts, USA",
"MA",
"Macon, Saone-et-Loire, Bourgogne, France",
"Maidencreek, Berks, Pennsylvania, USA",
"Maidstone Borough, Kent, England",
"Maidstone, Maidstone Borough, Kent, England",
"Malaga, Gloucester County, New Jersey, United States of America",
"Malden, Middlesex, Massachusetts, USA",
"Mancetter, Warwickshire, England",
"Mar Castle, Aberdeenshire, Scotland",
"Mar, Aberdeenshire, Scotland",
"Marcon, Sarthe, Pays de la Loire, France",
"Mark, Germany",
"Marlboro, Monmouth County, New Jersey",
"Marlboro, Monmouth County, New Jersey, United States of America",
"Marlborough, Wiltshire Unitary Authority, Wiltshire, England",
"Marlborough, Wiltshire, England",
"Marlborrough, Witlshire, England",
"Marlton, New Jersey, United States",
"Maryland",
"Maryland, United States",
"massachusetts bay colony",
"Massachusetts, United States",
"Massachusetts, USA",
"Massachusetts?",
"Maxatawny, Berks County, Pennsylvania, United States of America",
"Maxatawny, Berks County, Pennsylvania, USA",
"Maxstoke castle, Maxstoke, Warwickshire, England",
"Maxtote castle, Warwickshire, England",
"Maybe died at birth",
"Mearns, Kincardineshire, Scotland",
"Meath, Leinster, Ireland",
"Meaux, Seine-et-Marne, \u00cele-de-France, France",
"Medford, Burlington, New Jersey",
"Media, Pennsylvania, United States",
"Melrose Abbey (buried in Paisley Priory)",
"Melton Mowbray, Leicestershire, England",
"Membury, Devon, Enland",
"Merchantville, Camden, New Jersey, USA",
"Mertztown, Berk County, Pennsylvania",
"Mertztown, Berks County, Pennsylvania, United States of America",
"Mesen, West Flanders, Belgium",
"Metz, Moselle, Alsace-Champagne-Ardenne-Lorraine, France",
"Metz, Moselle, Lorraine, France",
"Meulan, Yvelines, \u00cele-de-France, France",
"Michigan Tech",
"Michigan, United States",
"Mickleton, NJ, United States",
"Middle, Cape May County, NJ",
"Middle, Cape May, New Jersey, USA",
"Middlesex, Colony of New Jersey, British Colonial America",
"Middlesex, England",
"Middlesex: - Register of Marriages, 1582-1837",
"Middleton Falls, Bucks, Pennsylvania, USA",
"Middleton, Essex, Massachusetts, United States",
"Middletown, Bucks, Pennsylvania, United States",
"Middletown, Chester, Pennsylvania",
"Middletown, Chester, Pennsylvania, United States",
"Middletown, Middlesex, Connecticut, United States",
"Middletown, Penn.",
"Milford Middle School",
"Millsboro, Sussex, Delaware, USA",
"Millville, NJ",
"Milton, DE",
"Mistley, Essex, England",
"Modena, Emilia-Romagna, Italy  (buried in Paris, France)",
"Monamny, Cork, Ireland",
"Monfort, Normandy, France",
"Monmouth, Monmouthshire, Wales",
"Monmouth, New Jersey, USA",
"Monmouthshire, Wales",
"Monongahela",
"Montfort, lAmaury, Yvelines, \u00cele-de-France, France",
"Montgomery County, Pennsylvania, USA",
"Montgomery, Montgomery, Pennsylvania, USA",
"Montgomery, Pennsylvania, United States",
"Monzie, Perthsire, Scotland",
"Monzievaird and Strowan, Perthshire, Scotland",
"Moray, Scotland",
"Morayshire, Scotland",
"Morris Twnsp, Washington County, Pa",
"Morven, Argyll, Scotland",
"Morvern, Argyll, Scotland",
"Morysville, PA",
"Mottisfont, Test Valley Borough, Hampshire, England",
"Moulin, East Lothian, Scotland",
"Moulin, Perthshire, Scotland",
"Mount Ephraim, NJ, United States",
"Moviddy, Cork, Ireland",
"Msgr. Bonner High School",
"Mt Ephraim BOE",
"M\u00fcnchen, M\u00fcnchen, Oberbayern, Bayern, Germany",
"Murdered at Picquigny, Somme, Picardy, France",
"murdered in Vermandois, Aisne, Picardie, France",
"my studio",
"Myers",
"Naperville, IL, United States",
"Naples, Florida, United States",
"Naples, Italy",
"Narragasett Bay, Middlesex, Massachusetts, United States",
"Nashua, New Hampshire, United States",
"Nassau, Deggendorf, Bayern, Germany",
"Nassau, Livingston, New York, United States",
"Nazing, Essex, England",
"near the Elbe in Germany",
"Neckartailfingen, Germany",
"Neiderlahngau, Germany",
"Neithrop, Oxford, England",
"New Buckenham, Norfolk, England",
"New Buckingham, Norfolk, England",
"New Cumberland, Pennsylvania",
"New England, USA",
"New Hanover, Montgomery County, Pennsylvania, United States of America",
"New Hanover, Montgomery, Pennsylvania, United States",
"New Hanover, Montgomery, Pennsylvania, USA",
"New Haven, New Haven County, Connecticut, USA",
"New Hempstead, Orange, New York, United States",
"new jersey",
"New Jersey",
"New Jersey, Monmouth, New Jersey, United States",
"New Jersey, United States",
"New Jersey, US",
"New Jersey, USA",
"New Jersey,USA",
"New Kent, New Kent, Virginia, American Colonies",
"New Port, Cumberland, New Jersey",
"New York",
"New York, New York",
"New York, New York County (Manhattan), New York, United States of America",
"New York, United States",
"New York, USA",
"Newark-on-Trent, Newark and Sherwood District, Nottinghamshire, England",
"Newark-on-Trent, Newark and Sherwood District, Nottinghamshire, England Cemetery: Worcester Cathedral Burial or Cremation Place: Worcester, City of Worcester, Worcestershire, England",
"Newcastle Upon Tyne, Northumberland, England, ",
"Newenham Hall, Devon, England",
"Newenham, Devon, England",
"Newfield, NJ, United States",
"Newham Manor, Plympton St Mary, Devon, England",
"Newnham Manor, Plympton St Mary, Devon, England",
"Newnham Manor, Plympton St Mary, Devonshire, Bermuda",
"Newnham, Devon, England",
"Newport and Dividing Creek, Cumberland, New Jersey, USA",
"Newport Richey, Florida, United States",
"Newport, Buckinghamshire, England",
"Newport, Cumberland Co., New Jersey",
"Newport, Cumberland County, New Jersey",
"Newport, Cumberland, New Jersey",
"Newport, Cumberland, New Jersey, United States",
"Newport, Cumberland, New Jersey, USA",
"Newport, Dividing Creek, NJ",
"Newport, New Jersey, US",
"Newport, Newport, Rhode Island",
"Newport, Newport, Rhode Island, United States",
"Newport, Shropshire, England",
"Newton Abbot, Devon, England",
"Newton, Chester, PA",
"Newton, Waterford, Ireland",
"Newtown, Queens County, New York Colony",
"Nicea, Bithynia, Turkey",
"Niddrew Castle, Dunbartonshire, Scotland",
"Niddrew Castle, Edinburgh, Scotland",
"Niddry Castle, Midlothian, Scotland",
"Niddry-Seton Castle, Edinburgh, Scotland ",
"Niddry, West Lothian, Scotland",
"Niederlahngau, Germany",
"Nithrop, Oxfordshire, England",
"NJ",
"NJ, United States",
"Nord-Pas-de-Calais, France",
"Nordhausen, Saxony, Prussia, Germany",
"Nordrhein-Westfalen, Germany",
"Norfolk: Norwich - Minutes of Court of Mayoralty, 1632-1635",
"Norman, Hampshire, England",
"Normandie, France",
"Normandy",
"Normandy , France",
"normandy, France",
"Normandy, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Normany, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Norristown, Montgomery, PA, United States",
"Norte dame, Rosen, Seine-Maritime France",
"North Burton, Yorkshire, England",
"North Carolina, United States",
"North Molton, North Devon District, Devon, England",
"north, Benefield, Northamptonshire, England",
"Northalteron, Morayshire, Scotland",
"Northern Ireland",
"Northumberland, England",
"Norton, Northamptonshire, , England",
"Norwalk, Fairfield, Connecticut, United States",
"Notre Dame High School",
"Nottingham, Chester County, PA, Colonial America",
"Nottingham, Chester County, Pennsylvania, US",
"Nottingham, Chester, PA, Colonial America",
"Nottingham, Chester, Pennsylvania, British Colonial America",
"Nottingham, Chester, Pennsylvania, United States",
"Nottingham, Chester, Pennsylvania, USA",
"Nottinghamshire, England",
"Nottinghamshire, Flintham, Wiltshire, England",
"Nythway, Devon, England",
"Oak Valley",
"Oaklyn, New Jersey, USA",
"Oaklyn, NJ",
"Obelisk, Montgomery County, Pennsylvania, United States of America",
"Ochiltree (Ayrshire) Scotland",
"Ochiltree Castle, Uphall, West-Lothian, Schotland",
"Ochiltree, Ayrshire, Scotland",
"of",
"of Berks Co., Pennsylvania",
"Of Chawleigh, Devonshire, England",
"of Hartford, Hartford, CT",
"of MA",
"of NC",
"of New Jersey",
"of NJ",
"of PA",
"of Scituate, Plymouth, MA",
"Of Staveley, Woodthrope, Yorkshire, England",
"of Uitikon, Zurich, Switzerland",
"Of Upton, Buckingham, England",
"Oizy, Namur, Belgium",
"Okeover, Staffordshire, , England",
"Old Bolingbroke, East Lindsey District, Lincolnshire, England",
"Onaway",
"Onaway High School",
"Oppenheim, , Rheinland-Pfalz, Germany",
"Orkney, Scotland",
"Orleans, Loiret, Centre, France",
"Osceola, Florida",
"Over Wallop, Hampshire, England",
"Overton, Hampshire, England",
"Owlpen, Gloustershire, England",
"Oxford, City of Oxford, Oxfordshire, England",
"Oxfordshire, England",
"pa",
"PA",
"PA Leadership Charter School",
"PA, Abington",
"PA, Montgomery, Hatbor0, United States",
"PA, United States",
"Padula",
"Paisley Abbey, Renfrewshire, Scotland",
"Paisley, Abbey, Renfrewshire, Scotland",
"Palermo, Italy",
"Pannonie Brigetio",
"Pantfield Bulmer, Essex, England",
"Pantfield, Essex, England",
"Paris, City of Paris, \u00cele-de-France, France",
"Paris, Paris, Ile-De-France, France",
"parish, Essex, England",
"Parish, Essex, England",
"Parkertown, Burlington, New Jersey, United States",
"Paul VI High School",
"Peckham, Kent, England",
"Pembroke Castle, Pembrokeshire, Wales",
"Penllyn, Pennsylvania, United States",
"Penn State",
"Penn State Brandywine",
"Penn State University",
"Penncrest High School",
"Pennsylvania",
"Pennsylvania, United States",
"Pennsylvania, USA",
"Perth, Perthshire, , Scotland",
"Perth, Perthshire, Scotland",
"Perugia, Perugia, Umbria, Italy",
"Peterborough Castle, Northamptonshire, England",
"Pfalzdorf, Kleve, Nordrhein-Westfalen, Germany ",
"Phiadelphia, PA",
"Phiadelphia, United States",
"Phila",
"Phila Brideb, Pennsylvania",
"Phila, pa",
"Phila, Pennsylvania",
"Phila, Phila, Pennsylvania, USA",
"Phila., Pennsylvania, United States",
"Philadelphia",
"Philadelphia , pa",
"Philadelphia City, Philadelphia, Pennsylvania",
"Philadelphia County, Pennsylvania, United States of America",
"Philadelphia County, Pennsylvania, USA",
"Philadelphia Ward 1, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 19, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 2, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 22 District 73, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 22, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 25, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 39, Philadelphia, Pennsylvania, USA",
"Philadelphia Ward 45, Philadelphia, Pennsylvania, USA",
"Philadelphia, Delaware, Pennsylvania, United States",
"Philadelphia, Pa",
"Philadelphia, PA",
"Philadelphia, PA, United States",
"Philadelphia, Pennsylvania",
"Philadelphia, Pennsylvania USA",
"Philadelphia, Pennsylvania, United States",
"Philadelphia, Pennsylvania, USA",
"Philadelphia, Philadelphia Co,, PA",
"Philadelphia, Philadelphia Co., PA",
"Philadelphia, Philadelphia County, PA",
"Philadelphia, Philadelphia County, Pennsylvania",
"Philadelphia, Philadelphia County, Pennsylvania, United States of America",
"Philadelphia, Philadelphia County, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Pierrepont, 54, Briey, Meurthe-et-Moselle, Lorraine, France",
"Pilesgrove, Salem County, New Jersey, United States of America",
"Pilesgrove, Salem, New Jersey, USA",
"Piscataway, Middlesex County, New Jersey",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex, New Jersey",
"Piscataway, Middlesex, New Jersey, United States",
"Pittsgrove Twp., Salem Co., New Jersey",
"Pittsgrove Twp., Salem Co., NJ",
"Pittsgrove, Salem, New Jersey, United States",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, NJ",
"Plantfield, Essex, England",
"Pleshey, Chelmsford Borough, Essex, England",
"Plouigneau, Finist\u00e8re, Bretagne, France",
"Pluderhausen, Wurttemberg, Germany",
"Plymouth County, Massachusetts, USA",
"Plymouth, Devon, England",
"Plymouth, Massachusetts",
"Plymouth, Plymouth, Massachusetts, United States",
"Plympton Church, Devon, , England",
"Plympton St Mary, Devon, England",
"Plympton, Plymouth Unitary Authority, Devon, England",
"Plympton, St Mary, Devonshire, England",
"Poitiers, Vienne, Poitou-Charentes, France",
"Pokanoket Village, Massachusetts, USA",
"Poland",
"Port Norris, Commercial Township, Cumberland Co., New Jersey",
"Port Norris, Downe Twsp.,Cumberland, New Jersey, USA",
"Pottstown, Montgomery County, Pennsylvania, United States of America",
"Pottstown, Montgomery, Pennsylvania, USA",
"Pottstown, Pennsylvania, United States",
"Powderham Castle, Devon, England",
"Preston on Stour, Gloucestershire, England",
"Preston-on-Stour, Gloucestershire, England",
"Preston, City of Preston, Lancashire, England",
"Preston, Glocestershire, England",
"Preston, Kent, England",
"Prob. Derbyshire, England",
"Puddington, Northamptonshire, England",
"Quaker Monthly Meeting, Thornbury,  Chester County, Pa",
"Quakertown Community High School",
"Quakertown, Bucks, Pennsylvania, United States",
"Queens, New York",
"Queens, New York, USA",
"Quendon, Uttlesford District, Essex, England",
"Quibbletown (now New Market area), Piscataway, Middlesex County, New Jersey, US",
"Quierzy, France",
"Raby, Durham, England",
"Raffin, Meath, 1652383",
"Raffin, Meath, Ireland",
"Raglan, Monmouth, Gwent, Wales",
"Raglan, Monmouth, Wales, Great Britain",
"Rainham, Kent, , England",
"Rainham, Kent, England",
"Rainham, Medway Unitary Authority, Kent, England",
"Rancocas Valley Regional High School",
"Raritan Landing, Somerset, New Jersey, United States",
"Rattlesden, Suffolk, England",
"Ravanusa",
"Ravanusa, Agrigente, Sicile, Italie",
"Ravanusa, Agrigento, Italy",
"Ravanusa, Agrigento, Sicilia, Italy",
"Ravanusa, Civile, Agrigento, Sicilia, Italy",
"RCA",
"Reading, Middlesex, Ma",
"Reali Saline,Foggia,Italy",
"Reims, Marne, Champagne-Ardenne, France",
"Remiremont, Vosges, Lorraine, France",
"Renfrewshire, Scotland",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"Rhaunen, Rheinland, Preu\u00dfen, Germany",
"Rhuddlan, Denbighshire, Wales",
"Richboro, PA",
"Richmond Palace, Richmond, Surrey, England",
"Richmond, London Borough of Richmond upon Thames, Greater London, England",
"Rillington, Leicestershire, England",
"Rishangles, Suffolk, England",
"Rishangles, Suffolkshire, England",
"Rising Sun, Cecil, Maryland, USA",
"Rochester, Kent, England",
"Rockland, Berks, Pennsylvania",
"Rockledge, Montgomery County, Pennsylvania, USA",
"Rolvenden, Kent, England",
"Roma, Lazio, Italy",
"Rome, Italy",
"Roslyn, Montgomery, Pennsylvania, USA",
"Roslyn, Pennsylvania, United States",
"Ross Cromarty, Scotland",
"Ross, Scotland",
"Rotherfield, Sussex, England",
"Rotherham, West Yorkshire, Kingdom of England",
"Rothley, Leicestershire, , England",
"Rouen, Haute-Normandie, France",
"Rouen, Seine-Maritime, Haute-Normandie, France",
"Rouncy, Marne, Champagne-Ardenne, France",
"Roundhill, Somerset, England",
"Rowan University",
"Roxborough, Philadelphia, Pennsylvania, USA",
"Roxburgh Castle Scotland (cannon he lit during seige exploded",
"Roxeth, Middlesex, England",
"Ruden McClosky",
"Runnemede, NJ",
"Russia",
"Rutgers Uniiversity",
"Rutgers University / College of Engineering",
"Ruthin, Denbighshire, Wales",
"Saffron Walden, Uttlesford District, Essex, England",
"Sag Harbor, East Hampton Suffolk, NY, USA",
"Saint Cuthberts, Edinburgh, Midlothian, Scotland",
"Saint Denis, France",
"Saint John The Baptist,Croydon,Surrey,England",
"Saint Michael Bassishaw,London,London,England",
"Salem, Essex, Massachusetts Bay Colony, British Colonial America",
"Salem, Massachusetts",
"Salem, Salem, New Jersey",
"Salem, Salem, New Jersey, USA",
"Salins, Seine-et-Marne, \u00cele-de-France, France",
"Salisbury castle, Wiltshire, England",
"Salisbury, MA",
"Salisbury, Wiltshire, England",
"Salt Lake City, Salt Lake, Utah",
"Samlesbury, Lancashire, England",
"San fernando, L.A., California, United States",
"San Fernando, LA, California, United States",
"San Francisco, California",
"Sandwich, Barnstable, Massachusetts, British Colony",
"Sandwich, Barnstable, Massachusetts, United States",
"Sanquhar Castle, Dumfrieshire, Schotland",
"Saybrook, Middlesex, Connecticut, United States",
"SC",
"Scaftworth, Nottinghamshire, England",
"Scheer, Sigmaringen, Baden-Wuerttemberg, Germany",
"Sch\u00f6mberg, Freudenstadt, Baden-W\u00fcrttemberg, Germany",
"Sch\u00f6nbrunn, Bamberg, Bayern, Germany",
"Schoorl, Noord-Holland, Netherlands",
"Schreisheim, Baden-Wuerttemberg, Germany",
"Schwenksville, Pennsylvania, United States",
"Scituate, Plymouth, Massachusetts, United States",
"Scituate, Plymouth, Massachusetts, USA",
"Scituate, USA",
"Scone, Pershire, Scotland",
"scotland",
"Scotland",
"SCOTLAND",
"Scotland Neck, Halifax, North Carolina, American Colonies",
"Scotland, Belize, Belize",
"Scotland, United Kingdom",
"Seaville, Cape May, New Jersey, United States",
"Seaville, Cape May, NJ",
"Sedgeberrow, Worcester County, England",
"Seven Oaks, Sunbridge, Kent, England UK",
"Sewell, Gloucester, New Jersey, USA",
"Sewell, Gloucester, NJ, United States",
"Shaftesbury, Dorset, England",
"Shavington, Cheshire, England",
"Shelby, Illinois, United States",
"Showton, Hallow, Worcestershire, England",
"Showton, Worcestershire, England",
"Shrewsbury Abbey, Shrewsbury, Shropshire, England",
"Shrewsbury, Shropshire Unitary Authority, Shropshire, England",
"Shrewsbury, Shropshire, England",
"Shropshire, England",
"Shwenksville, Pennsylvania, United States",
"Siege, of, Damietta, Egypt",
"Silkstone with Stainborough, All Saints, Yorkshire, England",
"Skelmersdale, West Lancashire District, Lancashire, England",
"Skelton in Cleveland, Yorkshire, England",
"Skelton In Cleveland, Yorkshire, England",
"Skelton- In- Cleveland, Yorks, England",
"Skelton-Cleveland, Yorkshire, England",
"Skelton, Yorkshire, England",
"Slain by Saracens of Battle of Mansura, Nile, delta, Egypt",
"slipton, in, Topcliffe, Yorkshire, England",
"Slot O Hoef, Netherlands",
"Smyrna, Kent, De",
"Smyrna, Kent, Delaware, United States",
"Soissons-sur-nacey, Burgandy, France",
"Solihull, Warwickshire, England",
"Somerset, Devon, England",
"Somerset, England",
"Somerset, NJ",
"Sommatrino, Sicily",
"Somme, Picardie, France",
"South Hempstead, Queens, New York, United States",
"South Yorkshire, England",
"Southampton, LI",
"Southampton, Livingston, New York, United States",
"Southampton, New York Colony, New England",
"Southampton, Pennsylvania, United States",
"Southampton, Suffolk County, New York, Colonies",
"Southampton, Suffolk County, New York, USA",
"Southampton, Suffolk, New York, United States",
"Southfield, Oakland, Michigan, United States",
"southhampton, long island, NY",
"Speldhurst, Kent, England",
"Springfield, Burlington, New Jersey, USA",
"Springfield, Essex, New Jersey, USA",
"Springfield, Hampden, Massachusetts, USA",
"Springfield, PA, United States",
"Springfield,Hampden,Massachusetts, USA",
"Springton Lake Middle School",
"SS, Simon and Jude School",
"St Albans",
"St Albans, Hertfordshire, , England",
"St Albans, Somerset, England",
"St Andrew Wardrobe, London, London, England",
"St Andrews, Brunswick, Virginia, United States",
"St Andrews,Dundee, Scotland.",
"St Botolph Bishopsgate, London, England",
"St Denis, Aude, Languedoc-Roussillon, France",
"St Dunstan and All Saints, Middlesex, England",
"St Dunstan and All Saints, Stepney, Middlesex, England",
"St Edmundsbury Borough, Suffolk, England",
"st james, Clerkenwell, Middlesex, England",
"St James, Clerkenwell, Middlesex, England",
"St John the Baptist, Hillingdon, Middlesex, England",
"St Lukes School",
"St Martin Vintry, London, England",
"St Mary, Devon, England",
"St Mary, Islington, Middlesex, England",
"St Mary, Whitechapel, Middlesex, England",
"St Michael Bassishaw, London, England",
"St Michael Paternoster Royal, London, England",
"St Michael, Crooked Lane, London, or Speldhhurst, Tonbridge Wells, Kent, England",
"St Olave, Bermondsey, Surrey, England",
"St Omer, Pas-de-Calais, Nord-Pas-de-Calais, France",
"St Pauls Church, Chester, Pennsylvania, United States",
"St Saviour, Surrey, England",
"St, Mary, Churchyard, Melton Mowbray, Leicestershire, England",
"St. Cecilia",
"St. Cray's, North Cray, Bromley, Kent, England",
"St. Dunstan, Stepney, Middlesex, England",
"St. John of the Cross",
"St. Johnston, Donegal, Ireland",
"St. Modwen, Burton Upon Trent, Staffordshire, England",
"St. Peters, Lincolnshire, England.",
"St. Philomena's School",
"Stafford Township, Monmouth, New Jersey, USA",
"Stafford, England",
"Stafford, Monmouth, New Jersey",
"Stafford, Monmouth, New Jersey, United States",
"Stafford, Staffordshire, England",
"Staffordshire Kent England",
"Staffordshire, England",
"Stamford, Fairfield, Connecticut, United States",
"Stamford, South Kesteven District, Lincolnshire, England",
"Stanstead, Kent, , England",
"Stansted, Kent, England",
"Stansted, Maidstone, Kent, England",
"Stanstede Parish Kent Co England",
"Stanstede, Kent, , England",
"Stanstede, Kent, England UK ",
"Staplehurst, Kent, England",
"State College, Centre, Pennsylvania, USA",
"Staveley, Derbyshire, Kingdom of England",
"Steinenbronn, Boblingen, Baden-Wuerttemberg, Germany",
"Stepney, Middlesex, England",
"Sterborough Castle, Lingfield, East Grinstead, Tandridge, West Kent",
"Stewton, Lincoln, England",
"Steyning, Sussex, England",
"Stirling Castle, Scotland",
"Stirling, Stirlingshire, Scotland",
"Stobhall, Cargill, Perthshire, Scotland",
"Stockwell, London Borough of Lambeth, Greater London, England",
"Stone Staffordshire England",
"Stone, Ashton, Stafford, Staffordshire, England",
"Stone, Staffordshire, England",
"stonehaven kincardine, Scotland",
"Stony Brook, Middlesex County, New Jersey",
"Stratford, Avon, Warwicksire, England",
"Stratford, Fairfield County, Connecticut, United States of America",
"Stratford, Fairfield County, Connecticut, USA",
"Stratford, Fairfield, Connecticut Colony",
"Stratford, Fairfield, Connecticut, United States",
"Stratford, Fairfield, Connecticut, USA",
"strathbane, Stirlingshire, Scotland",
"Streat, Sussex, England",
"Suffolk, England",
"suffolk, ny, british colonial america",
"Sundridge, County Kent, England",
"Sundridge, Kent, England",
"Sundridge, Kent, England UK",
"Sundridge, Kent, England UK ",
"Sundridge, Kent, England, United Kingdom",
"Surrey, England",
"Surrey, England Cemetery: Canterbury Cathedral Burial or Cremation Place: Canterbury, City of Canterbury, Kent, England",
"sURREY, vIRGINIA",
"Sussex England",
"Sussex, Delaware, United States",
"Sussex, England",
"Swabia, Germany",
"Swallowcliffe, Wiltshire, England",
"Swarkston on the trent, Derbyshire, England",
"swarkstone, Derbyshire, England",
"Switzerland",
"Syrie",
"Tamworth CASTLE Staffordshire, England",
"Tamworth Castle, Staffordkshire, England",
"Tamworth Castle, Staffordshire, England",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Tamworth, Leicestershire, England",
"Tamworth, Staffordshire, England",
"Tamworth, Tamworth Borough, Staffordshire, England",
"Tantallon Castle, East Lothian, Scotland",
"Tantallon Castle, North Berwick, East Lothian, Scotland",
"Tarboro, Edgecombe, North Carolina, USA",
"Tarrant Crawford, North Dorset District, Dorset, England",
"Tarsus, Turkey",
"Tawstock Manor, Devonshire, England",
"Tawstock, Devon, England",
"Tawstock, Devonshire",
"Tewkesbury, Tewkesbury Borough, Gloucestershire, England",
"the church of the holy cross, crediton on the creedy river, England",
"The Netherlands",
"The Richard Stockton College of New Jersey",
"Theuborough,Sutcombe,Devonshire,England",
"Thewborough, Devon, England",
"Thewbourough, Devonshire, England",
"Thomas Sharp School",
"Thornbury, Chester, Pennsylvania, United States",
"Thornbury, Chester, Pennsylvania, USA",
"Thornbury,Chester,Pennsylvania,USA",
"Thorne, Devon, England",
"Thuborough Barton, Sutcombe, Devon, England",
"Thueringen, Germany",
"Thursley, Surrey, England",
"Tidkinhow, Skelton, England",
"Tilstock, Shropshire, England",
"Tohicken Valley ",
"Tonbridge Castle, East Peckham, Kent, England",
"Tonbridge, Castle, East Peckham, Kent, England",
"Tonbridge, Kent, , England",
"Tonbridge, Kent, England",
"Torino Piedmonte, Sardegna, Italy",
"torrence, Lanarkshire, Scotland",
"Toulouse, Haute-Garonne, Midi-Pyr\u00e9n\u00e9es, France",
"Toulouse, Hautes-Pyrenees, Midi-Pyr\u00e9n\u00e9es, France",
"Town Bank, Cape May County, New Jersey, United States of America",
"Tredington, Gloucestershire, England",
"Tredington, Gloucestershire, England, United Kingdom",
"Tredington, Staffordshire, Worcestershire, England",
"Tredington, Worcestershire, England",
"Trenton, Hunterdon, New Jersey, United States",
"Troup, Banffshire, Scotland",
"Troy, Oakland, Michigan, United States",
"Troyes, Departement de l'Aube, Champagne-Ardenne, France",
"Trussville, Jefferson, Alabama, United States of America",
"Trussville, Jefferson, Alabama, USA",
"Tuckerton, Ocean County, New Jersey, United States of America",
"Tuckerton, Ocean County, New Jersey, USA",
"Tuckerton, Ocean, New Jersey",
"Tufara, Campobasso, Molise, Italy",
"Tullamore, Kerry, Ireland",
"Tullamore, Kings County (now Offaly), Ireland ",
"Tulpehocken Township, Berks, Pennsylvania, USA",
"Tunbridge Castle, Kent, England",
"Tunbridge, Kent, , England",
"Tunbridge, Kent, England",
"Tundridge, Kent, England",
"Turin, Torino, Piemonte, Italy",
"Turkey",
"Turkey Point, Cumberland, New Jersey, United States",
"Turriff, Aberdeenshire, Scotland",
"Twyford, Buckinghamshire, , England",
"Tyler School o fArt",
"Tynedale, East Lothian, Scotland",
"Ufgau, Germany",
"Uitikon,  Zurich,  Switzerland",
"Uitikon, Zurich, Switzerland",
"Uitikon, Z\u00fcrich, Switzerland",
"Ulcombe, Kent",
"Ulcombe, Kent, , England",
"Ulcombe, Kent, England",
"Ulcombe, Maidstone Borough, Kent, England",
"United States",
"United States of America",
"University of the Sciences of Philadelphia",
"Unknown",
"Up Darby, Delaware, Pennsylvania, United States",
"Up Holland, West Lancashire District, Lancashire, England",
"Upham, Hampshire, England",
"Upper Alloway Creek, Salem, New Jersey, United States",
"Upper Dublin High School",
"Upper Dublin, Pennsylvania, United States",
"Upper Frederick Township, Montgomery, Pennsylvania",
"Upper Pittsgrove, Salem, New Jersey, USA",
"Upper Providence Twp., Chester (later Delaware), Pennsylvania",
"Uppsala, Sweden",
"Uppsala, Uppsala, Kronoberg, Orebro, Sweden",
"Upton, Buckingham, Buckinghamshire, England",
"Upton, Buckinghamshire, Eng",
"Upton, Buckinghamshire, England",
"USA",
"Valenciennes, Departement du Nord, Nord-Pas-de-Calais, France",
"Varenne, Cher, Centre, France",
"Varenne, Seine-Infereieure, Normandy, France",
"Vascoeuiil, Seine Inferieure, Normandy, France",
"Vermand, Aisne, Picardie, France",
"Vermandois, Aisne, Picardie, France",
"Vermandois, France",
"Vermandois, Normandy, France",
"Vermondois, Aisne, Picardie, France",
"Vincennes, Val-de-Marne, \u00cele-de-France, France",
"Vincentown, Burlington, New Jersey, United States of America",
"Vineland, Cumberland, New Jersey, USA",
"Virginia",
"VIRGINIA",
"Virginia Colony",
"Virginia,  United States",
"Virginia, United States",
"Virginia, USA",
"Vlaanderen, East Flanders, Belgium",
"Voorhees, Camden, New Jersey, USA",
"Voorhees, NJ, United States",
"W. Nottingham, Chester, PA, USA",
"Waldeck, Ansbach, Bayern, Germany",
"Wales",
"Wallingford, South Oxfordshire District, Oxfordshire, England",
"Walsham le Willows, Suffolk, England",
"Walton, Lancashire,  England",
"wamanoag, village, Massachusetts Bay Colony, Colonial, America",
"Wamonoag, Village, MassachusettsBay Colony, Colonial, USA",
"wampanoag village, Yarmouth, Barnstable, Massachusetts, USA",
"wampanoag, village, Yarmouth, Barnstable, Massachusetts, USA",
"Wantage, Oxfordshire, England",
"Warwick, Warwick District, Warwickshire, England",
"Warwickshire, England",
"Washington Co, Virginia, United States",
"Washington County, VA",
"Washington County, Virginia, USA",
"Washington, Virginia",
"Washington, Virginia, United States",
"Washington, Virginia, USA",
"Waterford, Camden, New Jersey, United States",
"Watford, Hertfordshire, England",
"Weedon, Buckinghamshire, England",
"Welcome Volunteer Fire Company",
"Wellfleet, Barnstable County, Massachusetts, USA",
"Wellington",
"Wem, Shropshire, England",
"Werl, Germany",
"Werle, Germany",
"Wernersville, Berks County, Pennsylvania, United States of America",
"Wessex, England",
"West Cape May, Cape May, New Jersey, USA",
"West Chester State College",
"West Chester University",
"West Chester, Chester, Pennsylvania",
"West cot, Dorking, Surrey, England",
"West Creek, Monmouth, New Jersey",
"West Creek, Monmouth, New Jersey, United States",
"West Creek, Ocean, New Jersey",
"West Creek, Ocean, New Jersey, United States",
"West Creek, Ocean, New Jersey, USA",
"West Deptford, Gloucester, New Jersey, United States",
"West Laurel Hill Cemetery, Philadelphia, PA",
"West Melbury, Dorset, England",
"West Nottingham Hundred, Cecil, Maryland, United States",
"West Nottingham, Cecil County, Maryland",
"West Nottingham, Cecil, Maryland, USA",
"West Nottingham, Cecil, MD, Colonial America",
"West Nottingham, Chester Co., Pennsylvania",
"West Nottingham, Chester, PA, Colonial America",
"West Nottingham, Chester, PA, USA",
"West Nottingham, Chester, Pennsylvania, British Colonial America",
"West Peckham, Kent, , England",
"West Point Troup Georgia",
"West Rasen, Lincolnshire, England",
"West Sussex, England",
"West Titherlay, Hertfordshire, England",
"West Town, Chester, Pennsylvania, USA",
"West Yarmouth, Barnstable or  Salem, Essex, MA",
"West Yarmouth, Barnstable, Massachusetts, United States",
"West Yarmouth, Barnstable, New Plymouth Colony, MA",
"West, Essex, England",
"West, Jersey, Channel Islands",
"West, Wiltshire, England",
"Westampton, burlington, New Jersey, United States",
"Westampton, Burlington, New Jersey, United States",
"Westampton, NJ, United States",
"Westbury, Nassau, New York, United States",
"Westbury, Queens, New York, United States",
"Westchester Square, Bronx County, New York, United States of America",
"Westmeath, Ireland",
"Westminster Palace, Westminster, London, Middlesex, England",
"WESTMINSTER PAR/SO RIV PAR, A. ARUN., Maryland",
"Westminster, City of Westminster, Greater London, England",
"Westminster, England",
"Westminster, Middlesex, England",
"Westmoreland, Virginia, United States",
"Weston-on-Trent, Derbyshire, England",
"Westover Parish, Lunenburg, Virginia, American Colonies",
"Westtown, Chester, Pennsylvania, British Colonial America",
"Westtown, Chester, Pennsylvania, United States",
"Westtown, Chester, Pennsylvania, USA",
"Westville, Gloucester, New Jersey, USA",
"Wherwell, Hampshire, , England",
"Whitechapel, London, Middlesex, England",
"Whitstone, Cornwall, England",
"Wilby, Mid Suffolk District, Suffolk, England",
"Wilford, Nottinghamshire, England",
"Williamsport, Pennsylvania",
"Willingboro, Burlington, New Jersey, USA",
"Willingboro, New Jersey, USA",
"Willingboro, NJ",
"Wilmington, Dartford, Kent, England",
"Wilmington, Kent, England",
"Wilmington, New Castle, Delaware, USA",
"Wilmington, New Hanover County, North Carolina, US",
"Wiltshire, England",
"Wincanton, Somerset, , England",
"Wincanton, Somerset, England",
"Wincanton, South Somerset District, Somerset, England",
"Winchester, City of Winchester, Hampshire, England",
"Winchester, Hampshire, England",
"Windham, Windham, Connecticut, United States",
"Windsor, Berkshire, England",
"Windsor, Hartford County, Connecticut Colony, USA",
"Windsor, Hartford, Connecticut, United States",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"Winningen, Mayen-Koblenz, Rheinland-Pfalz, Germany",
"Winningen, Mayen-Koblenz, Rhineland-Palatinate, Germany",
"Winningen, Pfalz, Bavern, Germany",
"Woburn, Middlesex, Massachusetts, USA",
"Woobury, NJ, New Jersey, United States",
"Woodbridge, Middlesex Co, New Jersey",
"Woodbridge, Middlesex County, New Jersey Colony",
"Woodbridge, Middlesex County, New Jersey, US",
"Woodbridge, Middlesex, New Jersey",
"Woodbridge, Middlesex, New Jersey, United States",
"Woodbury, Gloucester, New Jersey, United States",
"Woodbury, New Jersey",
"Woodbury, New Jersey, United States",
"Woodham Ferrers, Chelmsford Borough, Essex, England",
"Woodham Walter, Essex, England",
"Woodlynne CA, New Jersey",
"Woodlynne, Camden, New Jersey, USA",
"Woodmancote, Sussex, England",
"Woodstock, West Oxfordshire District, Oxfordshire, England",
"Woodstown, Salem County, New Jersey, United States of America",
"Woodstown, Salem, New Jersey, USA",
"Woodthorpe, Staveley, Derbyshire, Kingdom of England",
"Worcester,   Worcestershire,   England",
"Worcester, City of Worcester, Worcestershire, England",
"Worcester, Worcestershire, England",
"Worcestershire, England",
"Worksop, Nottinghamshire, England",
"Worms, Rhineland-Palatinate, Germany",
"Wrightstown, Burlington County, New Jersey, United States of America",
"Wrotham, Kent, England",
"Wysmirzcye, Poland",
"Y",
"Y, Somme, Picardie, France",
"Yardley Hastings, Northamptonshire, England",
"Yardley Hastings, Rutland, England",
"Yarmouth, Barnstable County, Massachusetts, USA",
"Yarmouth, Barnstable, MA",
"Yarmouth, Barnstable, MA, USA",
"Yarmouth, Barnstable, Massachusetts",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, USA.",
"Yarmouth, Barnstable.Mass",
"Yeldham or Chelmsford, Essex, England",
"Yester Castle, Gifford, East Lothian, Scotland",
"yester, haddingtonshire scotland",
"yester, hadingtonshire, Scotland",
"York College of PA",
"York, Virginia",
"York, Virginia, United States",
"Yorkshire",
"Yorkshire, England",
"Yorktown, York County, Virginia, United States of America",
"Yorktown, York, Virginia, United States",
"Yorktown, York, Virginia, USA",
"Zachary, LA",
"Zane North",
"Zug,  Switzerland",
"Zurich, Switzerland",
"Z\u00fcrich, Zurich, Switzerland"
]
Dwr.ScriptLoaded('dwr_db_P_name_0.js');
