// This file is generated

I_birth_place_0 = [
"",
"",
"",
"",
", , , France",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Horsham, Sussex, England",
"Somerset, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Normandie, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Rillington, Leicestershire, England",
"Gloucester, Essex, Massachusetts, United States",
"",
"",
"New Jersey",
"Orkney, Scotland",
"",
"",
"",
"",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"Cumberland, Cumberland, New Jersey, United States",
"",
"",
"",
"",
"",
"Oxfordshire, England",
"",
"",
"Pembroke Castle, Pembrokeshire, Wales",
"",
"Plympton, St Mary, Devonshire, England",
"",
"Oxford, City of Oxford, Oxfordshire, England",
"",
"",
"",
"",
"",
"",
"",
"Steinenbronn, Boblingen, Baden-Wuerttemberg, Germany",
"Benenden, Kent, England",
"",
"",
"Long Island City, Queens, New York",
"",
"London, middlesex, england",
"",
"",
"",
", , England",
"",
"",
"Baynard, Essex, England",
"",
"England",
"Poland",
"",
"",
"",
"ireland",
"",
"Ireland",
"M\u00fcnchen, M\u00fcnchen, Oberbayern, Bayern, Germany",
"",
"",
"Montgomery, Pennsylvania, United States",
"Tantallon Castle, North Berwick, East Lothian, Scotland",
"Catham, Barnstable, MA",
"",
"Wincanton, Somerset, England",
"Tunbridge, Kent, , England",
"",
"Landsall, Sussex, England",
"Norman, Hampshire, England",
"Lochorwort Castle, Gorebridge, Midlothian, Scotland",
"Moray, Scotland",
"Scotland",
"Tawstock Manor, Devonshire, England",
"Newport, Shropshire, England",
"",
"Fyvie, Aberdeenshire, Scotland",
"ABERDEENSHIRE, SCOTLAND",
"",
"",
"",
"",
"",
"",
"",
"",
"Pennsylvania",
"",
"",
"Kittery, York, Maine, USA",
"Paris, Paris, Ile-De-France, France",
"Paris, Paris, Ile-De-France, France",
"Paris, Paris, Ile-De-France, France",
"Great Yarmouth, Norfolk, ENGLAND",
"Kent, England",
"",
"Hatfield Heath, Essex, England",
"",
"Newtown, Queens County, New York Colony",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"",
"",
"",
"",
"Forfar, Angus, Scotland",
"",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Ivrea, Torino, Piemonte, Italy",
"Torino Piedmonte, Sardegna, Italy",
"",
"",
"",
"",
"Arbuthnott, Kincardineshire, Scotland",
"",
"Aberdeenshire, Scotland",
"",
"Kincardineshire, Scotland",
"Greyfriars, Kirkyard, Edinburgh, Midlothian, Scotland",
"Arbuthnott, Kincardineshire, Scotland",
"",
"Kilkenny, Ireland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"North Burton, Yorkshire, England",
"Pennsylvania",
"",
"",
"York, Virginia, United States",
"Halifax, Halifax, North Carolina, United States",
", Mecklenburg, Virginia, American Colonies",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Covenham St. Mary, Lincoln, England",
"",
"swarkstone, Derbyshire, England",
"Swarkston on the trent, Derbyshire, England",
"Chellaston, Derbyshire, England",
"Weston-on-Trent, Derbyshire, England",
"Gartly, Aberdeenshire, Scotland",
"",
"Cropredy, Oxfordshire, England, United Kingdom",
"",
"",
"",
"",
"",
"",
"",
"",
"New York, New York",
"",
"",
"",
"",
"",
"Italy",
"",
"Pennsylvania",
"New York",
"Italy (one source said Russia but I think it was transcribed wrong)",
"",
"",
"",
"",
"",
"",
"",
"New York",
"",
"italy",
"",
"",
"",
"Pennsylvania",
"",
"Hampshire, England",
"Crediton, Devon, , England",
"St Mary, Devon, England",
"Awilscombe, Devon, England",
"Awliscombe, Devon, England",
"Scotland, Belize, Belize",
"Derby, Derbyshire, England",
"Basset, Leicester, Leicestershire, England",
"",
"",
"Heidelberg, Baden-W\u00fcrttemberg, Germany",
"Heidelburg, Baden Baden, Germany",
"Heidelberg, Baden-W\u00fcrttemberg, Germany",
"Scheer, Sigmaringen, Baden-Wuerttemberg, Germany",
"",
"Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Departement de la Haute-Loire, Auvergne, France",
"",
"England",
"Westminster Palace, Westminster, London, Middlesex, England",
"East Hampsett, Sussex, England",
"",
"Germany",
"",
"",
"Bolney, Sussex, England",
"",
"Ravanusa",
"Ravanusa, Agrigento, Sicilia, Italy",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Audubon, Camden, NJ, United States",
"",
"",
"",
"",
"Brittainy, Normandy, France",
"Brittainy, Normandy, France",
"Woodbury, Gloucester, New Jersey, United States",
"Woodbury, Gloucester, New Jersey, United States",
"Philadelphia, Pennsylvania, United States",
"Philadelphia, Pennsylvania, United States",
"Camden, Camden, New Jersey, United States",
"",
"Philadelphia, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"Uppsala, Sweden",
"Stratford, Fairfield, Connecticut, USA",
"Stratford, Fairfield County, Connecticut, USA",
"Yorktown, York County, Virginia, United States of America",
"Dividing Creek, New Jersey",
"Dividing Creek, Cumberland, New Jersey, United States",
"Berks Co, Pennsylvania",
"Rockland, Berks, Pennsylvania",
"",
"",
"",
"",
"",
"",
"",
"Elstead,Surrey,England",
"Greenwich, Gloucester, New Jersey, United States",
"Surrey, England",
"England",
"Bolney, Sussex, England",
"Bolney, Sussex, England",
"Bolney, Sussex County, England",
"Bolney, Sussex, England",
"Awilscombe, Devon, England",
"",
"Aries, Hautes-Pyr\u00e9n\u00e9es, Midi-Pyr\u00e9n\u00e9es, France",
"Haughton, Staffordshire, England",
"",
"Camden, NJ, United States",
"",
"Baunton, Devon, England",
"Little Easton, Uttlesford District, Essex, England",
"Chertsey, Surrey, England",
"Dorset, England",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"",
"Kilmarnock, Ayrshire, Scotland",
"",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Camden, Camden, New Jersey, United States",
"Gloucester, New Jersey, United States",
"",
"Camden, Camden, New Jersey, United States",
"",
"Pennsylvania, United States",
"",
"Camden",
"Hundon, Suffolk, England",
"Paisley Abbey, Renfrewshire, Scotland",
"Z\u00fcrich, Zurich, Switzerland",
"",
"",
"",
"Philadelphia, Pennsylvania",
"",
"",
"West Nottingham, Chester, Pennsylvania, British Colonial America",
"West Nottingham, Cecil County, Maryland",
"West Nottingham, Chester, Pennsylvania, British Colonial America",
"",
"",
"West Nottingham, Cecil, MD, Colonial America",
"Nottingham, Chester, Pennsylvania, USA",
"Nottingham, Chester, PA, Colonial America",
"Nottingham, Chester, PA, Colonial America",
"Nottingham, Chester, Pennsylvania, British Colonial America",
"West Nottingham, Cecil, Maryland, USA",
"",
"",
"West Chester, Chester, Pennsylvania",
"West Nottingham, Chester, PA, Colonial America",
"Puddington, Northamptonshire, England",
"",
"",
"Seven Oaks, Sunbridge, Kent, England UK",
"Maidstone Borough, Kent, England",
"Halifax, West Ridng, Yorkshire,England",
"Halifax, West Ridng, Yorkshire,England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"Staplehurst, Kent, England",
"England",
"Great Marlow, Buckinghamshire, , England",
"",
"",
"Tewkesbury, Tewkesbury Borough, Gloucestershire, England",
"",
"",
"Broomscroft, Shropshire, England",
"Broncroft Castle, Tugford, Shropshire, England",
"leys, kincardine, Scotland",
"",
"Long Island City, Queens, New York, United States",
"Kincardineshire, Scotland",
"scotland",
"leys, kincardine, Scotland",
"stonehaven kincardine, Scotland",
"",
"",
"Long Island City, Queens, New York",
"",
"Hitchin, Hertfordshire, England",
"",
"Hertfordshire, England",
"Camden, New Jersey, United States",
"",
"Kentisbeare, Devon, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Tidkinhow, Skelton, England",
"Great Moorsome, Yorkshire, England",
"",
"glenorchy, Argyll, Scotland",
"breadalbane, Perthshire, Scotland",
"SC",
"Ravanusa, Agrigente, Sicile, Italie",
"Ravanusa, Agrigento, Sicilia, Italy",
"Ravanusa, Agrigento, Sicilia, Italy",
"",
"Kilmarnock, Ayrshire, Scotland",
"Toulouse, Hautes-Pyrenees, Midi-Pyr\u00e9n\u00e9es, France",
"Beauvois-en-Vermandois, Aisne, Picardie, France",
"Toulouse, Haute-Garonne, Midi-Pyr\u00e9n\u00e9es, France",
"",
"",
"St Dunstan and All Saints, Middlesex, England",
"Ireland",
"Philadelphia, Pa",
"Philadelphia, Pa",
"Ireland",
"Ireland",
"Phila, Phila, Pennsylvania, USA",
"Philadelphia, Pa",
"",
"",
"",
"Philadelphia, PA",
"",
"Darby, Delaware, Pennsylvania, United States",
"United States",
"Meaux, Seine-et-Marne, \u00cele-de-France, France",
"Frankfurt am Main, Hesse, Germany",
"Poitiers, Vienne, Poitou-Charentes, France",
"Vermondois, Aisne, Picardie, France",
"",
"Orleans, Loiret, Centre, France",
"Meaux, Seine-et-Marne, \u00cele-de-France, France",
"",
"",
"Ravanusa, Agrigento, Sicilia, Italy",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Baltimore, Maryland, United States",
"",
"",
"Malaga, Gloucester County, New Jersey, United States of America",
"",
"Pilesgrove, Salem, New Jersey, USA",
"",
"",
"",
"Long Island City, Queens, New York, United States",
"Kent, England",
"Kent, England",
"Ashford, Kent, England",
"Gloucestershire, England",
"Bulmer, Essex, England",
"",
"Thornbury, Chester, Pennsylvania, United States",
"",
"Edinburgh Castle, Midlothian, Scotland",
"Ravanusa, Agrigento, Sicilia, Italy",
"Camden, Camden, New Jersey, United States",
"",
"Ravanusa, Agrigento, Sicilia, Italy",
"Ravanusa, Agrigento, Sicilia, Italy",
"Camden, New Jersey, United States",
"Camden, Camden County, New Jersey, United States",
"Ravanusa, Agrigento, Sicilia, Italy",
"Ravanusa, Agrigento, Italy",
"Sommatrino, Sicily",
"",
"Newport, Newport, Rhode Island",
"St Albans, Somerset, England",
"Hertfordshire, England",
"Nottinghamshire, England",
"",
"",
"",
"",
"",
"",
"",
"New Kent, New Kent, Virginia, American Colonies",
"Sterborough Castle, Lingfield, East Grinstead, Tandridge, West Kent",
"",
"Upton, Buckinghamshire, Eng",
"Goshen, Chester, Pennsylvania, United States",
"Goshen, Chester, Pennsylvania, United States",
"Westtown, Chester, Pennsylvania, United States",
"Massachusetts, United States",
"Lancashire, England",
"Ochiltree (Ayrshire) Scotland",
"Ayrshire, Scotland, Ardrossan",
"Italy (one source said Russia but I think it was transcribed wrong)",
"Gatinais, Loire, Orleanais/Centre france",
"AnjouPays-de-la-Loire, France",
"Rouncy, Marne, Champagne-Ardenne, France",
"Fl\u00e8che, Sarthe, Pays de la Loire, France",
"",
"",
"Altyre, Morayshire, Scotland",
"Northalteron, Morayshire, Scotland",
"Morayshire, Scotland",
"Altyre, Morayshire, Scotland",
"",
"West Rasen, Lincolnshire, England",
"",
"",
"Atherton, Lancashire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Winchester, City of Winchester, Hampshire, England",
"",
"",
"",
"",
"",
"Phila., Pennsylvania, United States",
"",
"Gatinais, Loire, Orleanais/Centre france",
"Gatinais, Loire, Orleanais/Centre france",
"Gatinais, Loire, Orleanais/Centre france",
"Orleans, Loiret, Centre, France",
"Gatinais, Loire, Orleanais/Centre france",
"Chateau Landon, Seine-et-Marne, \u00cele-de-France, France",
"Macon, Saone-et-Loire, Bourgogne, France",
"Macon, Saone-et-Loire, Bourgogne, France",
"Powderham Castle, Devon, England",
"",
"Southfield, Oakland, Michigan, United States",
"",
"",
"",
"",
"",
"",
"Anchorage, Alaska, United States",
"",
"",
"Philadelphia, PA, United States",
"Ireland",
"West Creek, Ocean, New Jersey, USA",
"Hertford, Hertfordshire, England",
"London, London, England",
"St Albans, Somerset, England",
"Brunswick County, Virginia, USA",
"St Albans, Hertfordshire, , England",
"New York, United States",
"Arque, Seine Inferiere, Normandy, France",
"Sanquhar Castle, Dumfrieshire, Schotland",
"",
"",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"Newton, Waterford, Ireland",
"Cape May, Cape May, New Jersey, United States",
"West Yarmouth, Barnstable, New Plymouth Colony, MA",
"England",
"Yarmouth, Barnstable, MA",
"Yarmouth, Barnstable, MA",
"",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Cape May, Cape May, New Jersey, United States",
"West Yarmouth, Barnstable or  Salem, Essex, MA",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Carltonrode, Norfolk, England",
"Stratford, Fairfield, Connecticut, United States",
"Nazing, Essex, England",
"Stratford, Fairfield County, Connecticut, United States of America",
"England",
"",
"",
"",
"",
"",
"",
"",
"",
"Bordeaux, Departement de la Gironde, Aquitaine, France",
"",
"",
"",
"",
"",
"Toulouse, Haute-Garonne, Midi-Pyr\u00e9n\u00e9es, France",
"Valenciennes, Departement du Nord, Nord-Pas-de-Calais, France",
"",
"",
"",
"",
"AnjouPays-de-la-Loire, France",
"Auvergne, France",
"Le Mans, Sarthe, Pays de la Loire, France",
"Evreux, Eure, Haute-Normandie, France",
"",
"",
"",
"Tullamore, Kings County (now Offaly), Ireland ",
"County Offaly, Ireland",
"",
"Pennsylvania",
"Steinenbronn, Boblingen, Baden-Wuerttemberg, Germany",
"Steinenbronn, Boblingen, Baden-Wuerttemberg, Germany",
"Cadogan, Armstrong, Pennsylvania",
"Armstrong County, Pennsylvania, USA",
"Armstrong County, Pennsylvania, USA",
"",
"Camden, NJ, United States",
"",
"",
"",
"District Twp., Berks Co., PA",
"Berks County, Pennsylvania, United States of America",
"Berks County, Pennsylvania ",
"Berks County, Pennsylvania, USA",
"Montfort, lAmaury, Yvelines, \u00cele-de-France, France",
"Evreux, Eure, Haute-Normandie, France",
"Lincolnshire, England",
"Bourneville, Eure, Haute-Normandie, France",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"beaumont-les-nonains, Oise, Picardie, France",
"Monmouthshire, Wales",
"",
"",
"Leicester, Leicestershire, England",
"",
"Boulogne, Vend\u00e9e, Pays de la Loire, France",
"Lens, Pas-de-Calais, Nord-Pas-de-Calais, France",
"",
"",
"",
"",
"Bronscroft Castle, Shropshire, England",
"",
"Cambrai, Nord, Nord-Pas-de-Calais, France",
"Brattleby, Lincolnshire, England",
"West Sussex, England",
"Kent, England",
"Eastchurch, Kent, England",
"",
"Crawford, Lanarkshire, Scotland",
"",
"Arque, Seine Inferiere, Normandy, France",
"Crepon, Calvados, Lower Normandy, France",
"Crepon, Calvados, Lower Normandy, France",
"Douai, Nord, Nord-Pas-de-Calais, France",
"",
"Oizy, Namur, Belgium",
"",
"Dunbar, East Lothian, Scotland",
"Dunbar, East Lothian, Scotland",
"Northumberland, England",
"Northumberland, England",
"Falaise, Calvados, Basse-Normandie, France",
"Falaise, Calvados, Basse-Normandie, France",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Leicester, Leicestershire, England",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Tamworth, Staffordshire, England",
"",
"",
"Peckham, Kent, England",
"Tamworth Castle, Tamworth, Staffordshire, England",
"Tamworth Castle, Staffordkshire, England",
"Luton, Luton Borough, Bedfordshire, England",
"Castle Groby, Leicester, Leicestershire, England",
"Fenzensac, France",
"Fezensac, Gascony, France",
"St Omer, Pas-de-Calais, Nord-Pas-de-Calais, France",
"Biggar, Lanarkshire, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"",
"",
"",
"",
"",
"Fonthill, Sussex, England",
"",
"Ruthin, Denbighshire, Wales",
"Groby Castle, Leicestershire, England",
"",
"",
"France",
"",
"",
"",
"Up Holland, West Lancashire District, Lancashire, England",
"Up Holland, West Lancashire District, Lancashire, England",
"Fyvie, Aberdeenshire, Scotland",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Aberdeenshire, Scotland",
"Bolton-le-Sands, City of Lancaster, Lancashire, England",
"Jupille, Belgium",
"Errol, Perthshire, Scotland",
"Ashby-de-la-Zouch, North West Leicestershire District, Leicestershire, England",
"",
"Lens, Artois, Flemish region, Holy Roman Empire",
"Leuven, Flemish Brabant, Flanders, Belgium",
"",
"",
"Salisbury, Wiltshire, England",
"Salisbury, Wiltshire, England",
"",
"Lorraine, France",
"",
"",
"",
"scotland",
"",
"",
"Macon, Saone-et-Loire, Bourgogne, France",
"",
"",
"Lay-Saint-Christofe, France",
"",
"",
"",
"",
"Vermandois, Aisne, Picardie, France",
"",
"Evreux, Eure, Haute-Normandie, France",
"Falaise, Calvados, Basse-Normandie, France",
"Rouen, Seine-Maritime, Haute-Normandie, France",
"Maxstoke castle, Maxstoke, Warwickshire, England",
"Belton, Uppingham, Rutland, England",
"Maxtote castle, Warwickshire, England",
"Maxtote castle, Warwickshire, England",
"",
"England",
"Raby, Durham, England",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"",
"",
"Reims, Marne, Champagne-Ardenne, France",
"",
"",
"scotland",
"",
"",
"Aberdeenshire, Scotland",
"",
"",
"",
"normandy, France",
"Flamstead, Hertfordshire, England",
"Flamstead, Hertfordshire, England",
"",
"",
"",
"",
"",
"",
"Worms, Rhineland-Palatinate, Germany",
"",
"",
"",
"Constantinople, Istanbul, Turkey",
"Vermandois, Normandy, France",
"I\u2019ll-et-villainess, Brittany, France",
"Lancashire, England",
"Groombridge, Kent, England",
"Surrey, England",
"Bellencombre, Seine-Maritime, Haute-Normandie, France",
"Sussex, England",
"Bellencombre, Seine-Maritime, Haute-Normandie, France",
"Aunou, Orne, Basse-Normandie, France",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"Bretagne, Landes, Aquitaine, France",
"Bretagne, Landes, Aquitaine, France",
"Clinton, Warwickshire, England",
"Perugia, Perugia, Umbria, Italy",
"",
"Ulcombe, Kent, England",
"Scotland, United Kingdom",
"Donegal Ireland",
"Banbury, Oxfordshire, England",
"Cropredy, Oxfordshire, England",
"Springfield, Hampden, Massachusetts, USA",
"Paris, Paris, Ile-De-France, France",
"Derbyshire, Kingdom of England",
"",
"",
"",
"",
"Flanders, Nord, Nord-Pas-Calais, France",
"Warwick, Warwick District, Warwickshire, England",
"Vermandois, France",
"",
"Ravanusa",
"",
"",
"",
"",
"",
"",
"",
"Willingboro, Burlington, New Jersey, USA",
"",
"",
"Yarmouth, Barnstable County, Massachusetts, USA",
"",
"Membury, Devon, Enland",
"Membury, Devon, Enland",
"",
"",
"",
"Lynn, Essex, Massachusetts, United States",
"Rainham, Kent, , England",
"Rainham, Medway Unitary Authority, Kent, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Donegal, Ireland",
"Donegal Ireland",
"",
"Hermiston, Midlothian, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"scotland",
"Aberdeenshire, Scotland",
"",
"Kilmaurs, Ayrshire, Scotland",
"Hermiston, Midlothian, Scotland",
"Hermiston, Midlothian, Scotland",
"Tantallon Castle, East Lothian, Scotland",
"douglas, Lanarkshire, Scotland",
"Abington, Montgomery, Pennsylvania, United States",
"Philadelphia, Pennsylvania, United States",
"Melton Mowbray, Leicestershire, England",
"Nottinghamshire, Flintham, Wiltshire, England",
"Nottinghamshire, Flintham, Wiltshire, England",
"Melton Mowbray, Leicestershire, England",
"",
"",
"United States",
"",
"Stobhall, Cargill, Perthshire, Scotland",
"",
"Inchmohomo, Scotland",
"Scotland",
"",
"",
"Scotland",
"",
"Scotland",
"",
"Pittsgrove Twp., Salem Co., New Jersey",
"",
"Fl\u00e8che, Sarthe, Pays de la Loire, France",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, NJ",
"Pittsgrove Twp., Salem Co., NJ",
"Pittsgrove, Salem, New Jersey, United States",
"",
"Pittsgrove, Salem, New Jersey, USA",
"",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, United States",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, United States",
"Pittsgrove, Salem, New Jersey, United States",
"Pittsgrove, Salem, New Jersey, USA",
"Pittsgrove, Salem, New Jersey, United States",
"",
"",
"dunbar, haddingtonshire, scotland",
"Grange, Monifieth, Angusshire, Scotland",
"",
"",
"Cambridge, Gloucestershire, England",
"Bridgen, of, Lintrathen, Angus, Scotland",
"Bruton, Somerset, England",
"Roundhill, Somerset, England",
"Wincanton, Somerset, , England",
"",
"Whitechapel, London, Middlesex, England",
"Halifax, West Ridng, Yorkshire,England",
"Halifax, West Ridng, Yorkshire,England",
"Wincanton, Somerset, England",
"",
"Hill Bishop, Somerset, England",
"Wincanton, Somerset, England",
"Somerset, England",
"",
"Washington Co, Virginia, United States",
"Westminster, City of Westminster, Greater London, England",
"Westminster, City of Westminster, Greater London, England",
"Caernarfon, Gwynedd, Wales",
"Caernarfon, Gwynedd, Wales",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"",
"",
"",
"New Buckingham, Norfolk, England",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts",
"Yarmouth, Barnstable, Massachusetts, USA",
"great saxhams, Suffolk, England",
"Wellfleet, Barnstable County, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, United States",
"Massachusetts, United States",
"Yarmouth, Barnstable, Massachusetts, USA",
"Cape May,New Jersey, Colonies",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts",
"Yarmouth, Barnstable.Mass",
"Cape May, Cape May, New Jersey, USA",
"Yarmouth, Barnstable, Massachusetts, USA",
"Yarmouth, Barnstable, Massachusetts",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"Yarmouth, Barnstable, MA, USA",
"Yarmouth, Barnstable, Massachusetts, USA",
"Cape May County, New Jersey",
"Cape May, Cape May, New Jersey, United States",
"Cape May County, New Jersey",
"Cape May County, New Jersey",
"Cape May County, New Jersey",
"Yarmouth, Barnstable, Massachusetts, USA",
"Cape May County, New Jersey",
"Cape May, Cape May, New Jersey, United States",
"",
"New Jersey",
"Cape May County, New Jersey",
"Cambridge, Middlesex, Massachusetts, USA",
"Cape May County, NJ",
"Aix-en-Provence, Departement des Bouches-du-Rh\u00f4ne, Provence-Alpes-C\u00f4te d'Azur, France",
"",
"",
"Cape May, Cape May, New Jersey, USA",
"",
"",
"",
"",
"",
"Maybe died at birth",
"Hempstead, Queens, New York, United States",
"Hempstead, Queens, New York, United States",
"Hempstead, Kings, New York",
"Hempstead, Queens, New York",
"",
"Hempstead, Livingston, New York, United States",
"Hempstead, Nassau, New York, United States",
"",
"",
"Hempstead, Nassau, New York, United States",
"Hempstead, Nassau, New York, United States",
"Hempstead, Nassau, New York, United States",
"Queens, New York, USA",
"Long Island City, Queens, New York, USA",
"",
"Blackburn, Lancashire, England",
"Newcastle Upon Tyne, Northumberland, England, ",
"Burgh by Sands, Cumberland, England",
"",
"",
"",
"",
"",
"",
"Mistley, Essex, England",
"",
"",
"New Jersey, United States",
"Longford,Derby,Eng",
"Groby, Leicestershire, England.",
"Peckham, Kent, England",
"Leicestershire, England",
"Tamworth, Leicestershire, England",
"Raglan, Monmouth, Wales, Great Britain",
"Chillesford, , Suffolk, England",
"East Peckham, Kent, England",
"Newton Abbot, Devon, England",
"Staffordshire, England",
"",
"Groby Old Hall, LEI, England",
"Chartley, Staffordshire, , England",
"Baddesley Clinton, Warwickshire, , England",
"",
"Tamworth CASTLE Staffordshire, England",
"Dethick Norbury, Derbyshire, England or Tamworth Castle, Tamworth, Staffordshire, England",
"Halifax, Yorkshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"England",
"",
"Arundel, Sussex, England",
"Monmouthshire, Wales",
"",
"Amesbury, Wiltshire, England",
"Salisbury, Wiltshire, England",
"Little Dunmow, Essex, England",
"",
"Woodham Walter, Essex, England",
"Woodham Walter, Essex, England",
"Tawstock, Devonshire",
"Little Eaton, Ess, England",
"Tawstock, Devon, England",
"Tewkesbury, Tewkesbury Borough, Gloucestershire, England",
"Ghent, East Flanders, Flanders, Belgium",
"Flanders, Belgium",
"Flanders, Nord, Nord-Pas-Calais, France",
"Flanders, Nord, Nord-Pas-Calais, France",
"Vlaanderen, East Flanders, Belgium",
"Flanders, Boulogne, Alsace, France",
"",
"",
"Biggar, Lanarkshire, Scotland",
"Kilmarnock, Ayrshire, Scotland",
"Biggar, Lanarkshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"England",
"",
"",
"",
"",
"Leicestershire, England",
"Devon, England",
"",
"Roxeth, Middlesex, England",
"Wincanton, Somerset, England",
"Rolvenden, Kent, England",
"Rolvenden, Kent, England",
"Derby, Derbyshire, England",
"Tamworth, Tamworth Borough, Staffordshire, England",
"",
"",
"",
"",
"",
"Woodmancote, Sussex, England",
"",
"",
"",
"Derby, Derbyshire, England",
"Derby, Derbyshire, England",
"Dursley, Gloucestershire, England",
"Derby, Derbyshire, England",
"Dursley, Gloucestershire, England",
"Dursley, Gloucestershire, England",
"",
"",
"",
"",
"",
"Tufara, Campobasso, Molise, Italy",
"Tufara, Campobasso, Molise, Italy",
"Tufara, Campobasso, Molise, Italy",
"",
"Nassau, Deggendorf, Bayern, Germany",
"Waldeck, Ansbach, Bayern, Germany",
"",
"",
"",
"",
"",
"Ireland",
"Ireland",
"Ipswich, Essex, Massachusetts, United States",
"Ipswich, Essex, Massachusetts, USA",
"Longueville, Normandy, France",
"",
"Bolbec, Pays de Caux, Haute-Normandie, France",
"Wiltshire, England",
"",
"",
"Itchell, Hampshire, England",
"Twyford, Buckinghamshire, , England",
"Itchell, Hampshire, England",
"Itchell, Hampshire, England",
"Hellidon, Buckinghamshire, England",
"Itchell, Hampshire, England",
"",
"Hellidon, Buckinghamshire, England",
"Salem, Essex, Massachusetts Bay Colony, British Colonial America",
"Woodbridge, Middlesex, New Jersey, United States",
"Hertfordshire, England",
"Hertfordshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Aberdeenshire, Scotland",
"Glack, Chapel Garioch, Aberdeen, Scotland",
"",
"Wilmington, Kent, England",
"Rotherfield, Sussex, England",
"",
"",
"",
"",
"",
"Cushnie, Aberdeenshire, Scotland",
"Barnstable, Barnstable, Massachusetts, United States",
"north, Benefield, Northamptonshire, England",
"",
"",
"",
"",
"Myers",
"",
"Tunbridge, Kent, England",
"",
"Tunbridge, Kent, England",
"Tunbridge, Kent, , England",
"PA, United States",
"",
"",
"Philadelphia, Pennsylvania, United States",
"",
"",
"",
"",
"Abington, Pennsylvania, United States",
"",
"Abington, Pennsylvania, United States",
"",
"Leicester, Leicestershire, England",
"Stratford, Fairfield, Connecticut, USA",
"Newport, Newport, Rhode Island, United States",
"Newport, Newport, Rhode Island",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Great Bentley, Essex, England",
"Jacksonville, Duval, Florida, USA",
"Ruthin, Denbighshire, Wales",
"",
"Poland",
"Wysmirzcye, Poland",
"Philadelphia, Philadelphia County, Pennsylvania, United States of America",
"Horsham, Sussex, England",
"Groombridge, Speldhurst, Kent, or Parham, Suffolk, England",
"",
"Mancetter, Warwickshire, England",
"",
"Speldhurst, Kent, England",
"Speldhurst, Kent, England",
"",
"",
"Pennsylvania",
"Germantown, Philadelphia County, Pennsylvania, United States of America",
"Ireland",
"Nottingham, Chester County, PA, Colonial America",
"",
"Scotland, United Kingdom",
"",
"Cadzow Castle, Hamilton, Lanark, Scotland",
"Aberdeenshire, Scotland",
"Carnhill, Aberdeenshire, Scotland",
"torrence, Lanarkshire, Scotland",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Astley, Worcestershire, England",
"",
"",
"",
"Cape May, New Jersey, United States",
"Long Island City, Queens, New York, USA",
"new jersey",
"",
"Camden, Camden, New Jersey, USA",
"Long Island City, Queens, New York, United States",
"",
"Hartford, Hartford, Connecticut, United States",
"Long Island, Suffolk, New York, United States",
"Sundridge, Kent, England",
"East Hampton, Suffolk, NY, USA",
"East Hampton, Suffolk, NY, USA",
"Tunbridge, Kent, England",
"Newport, Cumberland, New Jersey, USA",
"southhampton, long island, NY",
"Lynn, Essex, Massachusetts, United States",
"East Hampton, Middlesex, Connecticut, United States",
"Southampton, Suffolk, New York, United States",
"",
"",
"New Jersey",
"",
"New Jersey, United States",
"Cape May, New Jersey, United States",
"Cape May, Cape May, NJ, USA",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"East Hampton, Suffolk, New York, United States",
"",
"",
"Tilstock, Shropshire, England",
"Tilstock, Shropshire, England",
"Dividing Creek, Cumberland, New Jersey, USA",
"NJ",
"Cape May, New Jersey, United States",
"Cumberland Co., New Jersey",
"Newport, Cumberland, New Jersey, United States",
"New Jersey",
"Virginia",
"New Port, Cumberland, New Jersey",
"Sundridge, Kent, England",
"Tunbridge, Kent, , England",
"Cape May, Cape May, New Jersey, United States",
"",
"Downe, Cumberland, New Jersey, United States",
"",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"Washington, Virginia, United States",
"Washington County, Virginia, USA",
"Easthampton, Long Island, Suffolk, NY, USA",
"Cape May, Cape May, New Jersey, United States",
"Washington Co, Virginia, United States",
"Tundridge, Kent, England",
"Cape May, Cape May, New Jersey, United States",
"Sundridge, Kent, England",
"New Jersey, United States",
"Newport, Cumberland, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"Tredington, Gloucestershire, England",
"England",
"Tredington, Gloucestershire, England, United Kingdom",
"Stone Staffordshire England",
"Gloucestershire, England",
"",
"",
"England",
"Stone, Staffordshire, England",
"Stone, Staffordshire, England",
"Tonbridge, Kent, England",
"Sundridge, County Kent, England",
"Stansted, Maidstone, Kent, England",
"Tunbridge, Kent, , England",
"Long Island, Suffolk, New York, United States",
"",
"Tredington, Worcestershire, England",
"",
"Sundridge, Kent, England",
"Stansted, Kent, England",
"Staffordshire, England",
"Tredington, Staffordshire, Worcestershire, England",
"",
"",
"Lynn, Essex, Massachusetts, USA",
"Ashford, Kent, England",
"",
"New Jersey",
"",
"",
"New Jersey",
"",
"",
"Kent County, England",
"Sundridge, Kent, England UK ",
"Sundridge, Kent, England UK ",
"New Jersey,USA",
"East Hampton, Suffolk, New York, United States",
"Cape May, Cape May, New Jersey, United States",
"",
"",
"New Jersey, United States",
"Kent County, England",
"Stanstede Parish Kent Co England",
"Stanstede, Kent, , England",
"",
"Kent County, England",
"Stanstead, Kent, , England",
"Stanstead, Kent, , England",
"",
"Cape May, Cape May, New Jersey, United States",
"Fishing Creek, Cape May, New Jersey, USA",
"Camden, Camden, New Jersey, USA",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"Middletown, Middlesex, Connecticut, United States",
"New Jersey, United States",
"Virginia,  United States",
"",
"Southampton, Suffolk County, New York, Colonies",
"",
"Cape May, Cape May, New Jersey, United States",
"Cape May, Cape May, New Jersey, United States",
"Stanstede, Kent, , England",
"Cape May, Cape May, New Jersey, United States",
"",
"Downe Twsp.,Cumberland,New Jersey,USA",
"",
"",
"Fishing Creek, Cape May, New Jersey, United States",
"Southampton, Suffolk, New York, United States",
"Lynn, Essex, Massachusetts, United States",
"East Hampton, Suffolk, NY, USA",
"Cape May, Cape May, New Jersey, United States",
"Tredington, Worcestershire, England",
"Benenden, Kent, England",
"Tonbridge, Kent, , England",
"Kent County, England",
"Tonbridge, Kent, England",
"Kent, England",
"",
"Cape May, Cape May, New Jersey, United States",
"Tonbridge, Kent, England",
"Dover, Strafford, New Hampshire, USA",
"Stansted, Kent, England",
"England",
"Dover, Strafford, New Hampshire, USA",
"Benenden, Kent, England",
"Benenden, Kent, England",
"Staffordshire, England",
"",
"The Netherlands",
"",
"Southampton, New York Colony, New England",
"Worcestershire, England",
"England",
"Tredington, Worcestershire, England",
"Southampton, Suffolk County, New York, Colonies",
"Tredington, Worcestershire, England",
"Benenden, Kent, England",
"",
"Wilmington, Kent, England",
"",
"",
"Newport, Cumberland, New Jersey, United States",
"",
"New Jersey",
"",
"Kent, England",
"Wilmington, Dartford, Kent, England",
"",
"Benenden, Kent, England",
"Wilmington, Kent, England",
"East Hampton, Suffolk, New York",
"Maidstone, Maidstone Borough, Kent, England",
"East Hampton, Suffolk, New York",
"Benenden, Kent, England",
"",
"",
"Wincanton, Somerset, England",
"Montgomery, Montgomery, Pennsylvania, USA",
"Steinenbronn, Boblingen, Baden-Wuerttemberg, Germany",
"Montgomery, Montgomery, Pennsylvania, USA",
"Montgomery, Montgomery, Pennsylvania, USA",
"",
"Douglass, Berks, Pennsylvania, USA",
"Freudenstadt, Freudenstadt, Baden-Wuerttemberg, Germany",
"Sch\u00f6mberg, Freudenstadt, Baden-W\u00fcrttemberg, Germany",
"Douglass, Berks, Pennsylvania, USA",
"",
"",
"",
"Kent, England",
"Piscataway, Middlesex County, New Jersey, US",
"Essex County, New Jersey, US",
"West Nottingham, Chester, PA, Colonial America",
"Nottingham, Chester, Pennsylvania, United States",
"",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex County, New Jersey, US",
"Frome, Somersetshire, England",
"Bound Brook, Somerset, New Jersey, USA",
"Hopewell, Independent Cities, Virginia, United States",
"Chester Co., Pennsylvania",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex, New Jersey, United States",
"Tunbridge, Kent, , England",
"Quibbletown (now New Market area), Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex County, New Jersey, US",
"",
"",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex County, New Jersey, US",
"",
"",
"Piscataway, Middlesex County, New Jersey, US",
"Piscataway, Middlesex County, New Jersey, US",
"Ipswich, Essex, Massachusetts, United States",
"West Nottingham, Chester Co., Pennsylvania",
"W. Nottingham, Chester, PA, USA",
"Devon, England",
"Gloucester, Essex, Massachusetts, United States",
"Lynn, Essex Co., MA",
"Gloucester, Essex, Massachusetts, United States",
"Gloucester, Essex, Massachusetts, USA",
"Wincanton, Somerset, England",
"Gloucester, Essex, Massachusetts, USA",
"Gloucester, Essex, Massachusetts, USA",
"Wincanton, Somerset, England",
"Charleton Musgrave, Somerset, England",
"Wincanton, Somerset, England",
"",
"",
"Westminster, England",
"",
"",
"",
"Errol, Perthshire, Scotland",
"Aberdeenshire, Scotland",
"",
"Huntly, Aberdeenshire, Scotland",
"erroll, Perthshire, Scotland",
"Errol, Perthshire, Scotland",
"",
"yester, hadingtonshire, Scotland",
"Yester Castle, Gifford, East Lothian, Scotland",
"",
"",
"",
"",
"",
"",
"Chestnut Hill, Pa, United States",
"",
"Abington, Montgomery, PA, United States",
"Perth, Perthshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"Diseworth, Leicestershire, England",
"Diseworth, Leicestershire, England",
"",
"",
"",
"Argyll, Scotland",
"",
"Tulpehocken Township, Berks, Pennsylvania, USA",
"",
"Montgomery, Montgomery, Pennsylvania, USA",
"Douglass, Berks, Pennsylvania, USA",
"",
"Troup, Banffshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Nottinghamshire, England",
"Winchester, City of Winchester, Hampshire, England",
"Old Bolingbroke, East Lindsey District, Lincolnshire, England",
"Berks County, Pennsylvania",
"Derbyshire, Kingdom of England",
"Rotherham, West Yorkshire, Kingdom of England",
"Abington, Montgomery, Pennsylvania, United States",
"Chester, PA",
"Abington, Pennsylvania, United States",
"",
"",
"PA, Abington",
"Derby, Derbyshire, England",
"Derby, Derbyshire, England",
"Derby, Derbyshire, England",
"New Jersey, United States",
"Bershire Parish, Wiltshire, England",
"Newport, Cumberland, New Jersey, United States",
"Westtown, Chester, Pennsylvania, United States",
"Marlborough, Wiltshire, England",
"Berkshire Parish, Wiltshire, England",
"Berkshire Parish, Wiltshire, England",
"Berkshire Parish, Wiltshire, England",
"Newport, Cumberland Co., New Jersey",
"Great, Egg, Harlow, New Jersey",
"Great, Egg, Harlow, New Jersey",
"Newport, Cumberland Co., New Jersey",
"New Jersey, United States",
"Dividing Creek, Cumberland, New Jersey, United States",
"Lamborne, Wodlands, Berkshire, Wiltshire, England",
"Lincolnshire, England, United Kingdom",
"Gainsborough, Lincolnshire, England",
"Sussex, Delaware, United States",
"Essex, England",
"",
"Enkirch, Bernkastel-Wittlich, Rheinland-Pfalz, Germany",
"Barwick, Somerset, England",
"",
"Wincanton, Somerset, England",
"England",
"Philadelphia, Pennsylvania",
"Pennsylvania, USA",
"Lancaster, England",
"Pennsylvania",
"Pennsylvania",
"Arundel, Arun District, West Sussex, England",
"Lancashire, England",
"Wallingford, South Oxfordshire District, Oxfordshire, England",
"",
"",
"Up Holland, West Lancashire District, Lancashire, England",
"Skelmersdale, West Lancashire District, Lancashire, England",
"England",
"Up Holland, West Lancashire District, Lancashire, England",
"",
"",
"East Bradford, Chester, Pennsylvania, USA",
"Skelton in Cleveland, Yorkshire, England",
"Goshen, Chester, Pennsylvania",
"Great Moorsholm, Skelton-Cleveland, Yorkshire, England",
"Great Moorsholm, Yorkshire, England",
"West Town, Chester, Pennsylvania, USA",
"Preston, Kent, England",
"",
"",
"Scituate, Plymouth, Massachusetts, United States",
"Argyll, Scotland",
"scotland",
"",
"Scituate, Plymouth, Massachusetts, United States",
"Plymouth County, Massachusetts, USA",
"",
"",
"",
"Salisbury, MA",
"",
"",
"",
"",
"",
"",
"Abington, Montgomery, Pennsylvania, United States",
"",
"West Melbury, Dorset, England",
"",
"",
"",
"",
"",
"Birmingham, Warwickshire, England",
"Chester, Pennsylvania, British Colonial America",
"Germany",
"",
"",
"",
"",
"",
"",
"",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"Anjou, Is\u00e8re, Rh\u00f4ne-Alpes, France",
"",
"",
"",
"Ivrea, Torino, Piemonte, Italy",
"",
"",
"Bengeworth, Worcestershire, England",
"Stratford, Avon, Warwicksire, England",
"Acre, Hatzafon (Northern District), Israel",
"Acre, Hatzafon (Northern District), Israel",
"Oxford, City of Oxford, Oxfordshire, England",
"",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"Aberdeenshire, Scotland",
"",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"caskieben, Aberdeen, Aberdeenshire, Scotland",
"",
"Pennsylvania, USA",
"Douglass, Berks, Pennsylvania, USA",
"PA",
"Allentown, Lehigh, Pennsylvania, USA",
"Allentown, Lehigh, Pennsylvania, USA",
"Ingelheim, Germany",
"",
"Frankfurt, Germany",
"",
"Chasseneuil-sur-Garonne, France",
"Camden, NJ, United States",
"",
"",
"",
"ireland",
"",
"",
"",
"",
"",
"",
"",
"",
"Abington, Montgomery, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kincardineshire, Scotland",
"",
"Derbyshire, England",
"Hitcham, England",
"",
"",
"Worcester, Worcestershire, England",
"Over Wallop, Hampshire, England",
"Kent, England",
"Canterbury, Kent, England",
"Canterbury, Kent, England",
"England",
"",
"Tonbridge, Castle, East Peckham, Kent, England",
"",
"",
"Over Wallop, Hampshire, England",
"Tonbridge Castle, East Peckham, Kent, England",
"Tunbridge Castle, Kent, England",
"Tunbridge Castle, Kent, England",
"Groombridge, Kent, England",
"",
"",
"Brettenham, Suffolk, England",
"Nithrop, Oxfordshire, England",
"",
"",
"Sch\u00f6nbrunn, Bamberg, Bayern, Germany",
"",
"",
"",
"",
"Philadelphia, PA, United States",
"galicia, Poland",
"",
"Voorhees, NJ, United States",
"Limestone, Maine, United States",
"",
"Camden, Camden County, New Jersey, United States",
"Philadelphia, Pennsylvania, United States",
"",
"Pennsylvania, USA",
"",
"Phila Brideb, Pennsylvania",
"Pennsylvania",
"",
"",
"San Francisco, California",
"San Francisco, California",
"",
"Collingswood, NJ",
"Phila, Pennsylvania",
"",
"Voorhees, NJ, United States",
"",
"Winningen, Mayen-Koblenz, Rheinland-Pfalz, Germany",
"Pennsylvania",
"",
"",
"",
"",
"Boughton Monchelsea, Kent, England",
"Burstwick, East Riding of Yorkshire Unitary Authority, East Riding of Yorkshire, England",
"Burford, Shropshire Unitary Authority, Shropshire, England",
"Peterborough Castle, Northamptonshire, England",
"",
"Lanesville, Essex, Massachusetts, United States",
"of Berks Co., Pennsylvania",
"Edinburgh, Midlothian, , Scotland",
"",
"",
"Berks County, Pennsylvania ",
"Wem, Shropshire, England",
"",
"",
"",
"slipton, in, Topcliffe, Yorkshire, England",
"Aldingham, Lancashire, England",
"Cumberland, England",
"",
"",
"Cape May, Cape May, New Jersey, United States",
"",
"Cape May, Cape May, New Jersey, USA",
"Cape May County, New Jersey",
"Southampton, LI",
"Long Island City, Queens, New York, USA",
"Eaton, Nottinghamshire, England",
"",
"Brechin, Angus, Scotland",
"Philadelphia, Pa",
"Brunswick, Virginia, United States",
"Brunswick, Virginia, United States",
"St Andrews, Brunswick, Virginia, United States",
"Philadelphia, Pa",
"New York, New York County (Manhattan), New York, United States of America",
"Nordrhein-Westfalen, Germany",
"Jamaica,Long Island,New York,USA",
"",
"",
"",
"",
"",
"",
"England Earl, Sussex, England",
"England",
"Stratford, Fairfield, Connecticut, United States",
"Caskieben, ABER, Scot.",
"Scotland",
"leys, kincardine, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Logiealmond, Perthshire, Scotland",
"Logiealmond, Perthshire, Scotland",
"Logy Almond,,Perth,Scotland    ",
"",
"",
"LeMans, Sartre, Maine-et-Loire, Pays de la Loire, France",
"Kilmarnock, Ayrshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Kinfare, Stafford, Staffordshire, England",
"",
"Yarmouth, Barnstable, Massachusetts, USA",
"St. Peters, Lincolnshire, England.",
"Turriff, Aberdeenshire, Scotland",
"Cushnie, Aberdeenshire, Scotland",
"huntley, Aberdeenshire, Scotland",
"Aberdeenshire, Scotland",
"huntley, Aberdeenshire, Scotland",
"of Uitikon, Zurich, Switzerland",
"",
"Angus, Scotland",
"",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Phila, Pennsylvania",
"Pennsylvania",
"Ireland",
"Phila",
"Philadelphia",
"Philadelphia",
"Pennsylvania",
"Monamny, Cork, Ireland",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Philadelphia, Pennsylvania",
"Philadelphia, Pennsylvania",
"Philadelphia City, Philadelphia, Pennsylvania",
"Ireland",
"Pennsylvania",
"Phila, Pennsylvania",
"Phila",
"Philadelphia, Pennsylvania, USA",
"Philadelphia, Pennsylvania, USA",
"Pennsylvania",
"",
"Edinburgh Castle, Midlothian, Scotland",
"Forfar, Angus, Scotland",
"Forfar, Angus, Scotland",
"Iona, Argyll, Scotland",
"",
"Perth, Perthshire, , Scotland",
"Lorne, Argyll and Bute, Scotland",
"",
"",
"",
"Kingdom, of, the, isles, Scotland",
"Ross, Scotland",
"",
"",
"",
"Glamis Castle, Angus, Forfarshire, Scotland",
"Italy",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Abington, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"Chester, Newton, PA",
"Cheshire, England",
"",
"",
"",
"",
"Poitiers, Vienne, Poitou-Charentes, France",
"Haughton, Staffordshire, England",
"Paris, City of Paris, \u00cele-de-France, France",
"Chepstow, Monmouthshire, Wales",
"Ravanusa, Agrigento, Sicilia, Italy",
"Bolney, Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Uitikon, Zurich, Switzerland",
"Colonies (USA)",
"",
"Stewton, Lincoln, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Mearns, Kincardineshire, Scotland",
"",
"castle, Forbes, Aberdeenshire, Scotland",
"Fyvie, Aberdeenshire, Scotland",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Zug,  Switzerland",
"Scotland, United Kingdom",
"Hamilton, Lanarkshire, Scotland, United Kingdom",
"Bishops, Stortford, Hertfordshire, England",
"Lamborne, Wodlands, Berkshire, Wiltshire, England",
"Wiltshire, England",
"",
"Crawne, Wiltshire, England",
"",
"Bescote, Staffordshire, England",
"Bescote (Staffordshire) Gb",
"",
"Hempstead, Nassau, New York, USA",
"Westtown, Chester, Pennsylvania, British Colonial America",
"Dunbar, East Lothian, Scotland",
"Dunbar, East Lothian, Scotland",
"",
"",
"",
"Aberdeenshire, Scotland",
"",
"",
"Monmouthshire, Wales",
"Bristol, Gloucestershire, , England",
"Camden, NJ, United States",
"",
"Gainsborough, Lincolnshire, England",
"Berks County, Pennsylvania, USA",
"Germany",
"Winningen, Pfalz, Bavern, Germany",
"Birmensdorf, Zurich, Switzerland",
"Uitikon, Zurich, Switzerland",
"Schreisheim, Baden-Wuerttemberg, Germany",
"Winningen, Mayen-Koblenz, Rheinland-Pfalz, Germany",
"Uitikon, Zurich, Switzerland",
"",
"Germany",
"Germany",
"Sch\u00f6nbrunn, Bamberg, Bayern, Germany",
"Canton Berne, Old Swiss Confederation (now Swiss Confederation)",
"",
"",
"Hains Greene, Nottinghamshire, England",
"Eaton, Nottinghamshire, England",
"Eaton, Nottinghamshire,England",
"Skelton, Yorkshire, England",
"Lincolnshire, England",
"Colonial Era, Westmoreland, Virginia, USA",
"",
"Champagne-Ardenne, France",
"Ipswich, Essex, Massachusetts, United States",
"Sussex, England",
"Sussex England",
"",
"Sedgeberrow, Worcester County, England",
"",
"",
"Armstrong County, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Rouen, Haute-Normandie, France",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"Fecamp, Seine-Maritime, Haute-Normandie, France",
"",
"",
"Bayeux, Calvados, Basse-Normandie, France",
"Bayeux, Calvados, Basse-Normandie, France",
"",
"",
"",
"Altena, Germany",
"",
"",
"Altena, M\u00e4rkischer Kreis, North Rhine-Westphalia, Germany",
"Arnsberg, Germany",
"Armsberg, Germany",
"",
"",
"",
"Auvergne, France",
"Auvergne, France",
"Evreux, Eure, Haute-Normandie, France",
"",
"Bengeworth, Evesham, Worcestershire, England",
"Berg , Germany",
"Berg , Germany",
"Berg, Germany",
"",
"",
"",
"",
"",
"Auxerre, Yonne, Bourgogne, France",
"Burgos, Provincia de Burgos, Castilla y Le\u00f3n, Spain",
"",
"Kleve, Rheinland, Prussia",
"",
"Cleves, Germany",
"Cleves, Germany",
"Cleves, Germany",
"",
"Dublin, Dublin, Ireland",
"Alsace, France",
"",
"",
"Westminster, City of Westminster, Greater London, England",
"",
"Gatinais, Loiret, Centre, France",
"Ghent, Arrondissement Gent, East Flanders (Oost-Vlaanderen), Belgium",
"",
"",
"",
"",
"",
"",
"",
"Niederlahngau, Germany",
"Lincolnshire, England",
"Monmouth, Monmouthshire, Wales",
"England",
"",
"",
"",
"Lobdengau, Germany",
"Lobdengau, Germany",
"",
"Mark, Germany",
"Mark, Germany",
"Neiderlahngau, Germany",
"",
"lahngau, Germany",
"",
"",
"France",
"France",
"",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"",
"Swabia, Germany",
"Swabia, Germany",
"",
"Ufgau, Germany",
"",
"",
"Werl, Germany",
"Hereford, Herefordshire Unitary Authority, Herefordshire, England",
"",
"",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Uppsala, Uppsala, Kronoberg, Orebro, Sweden",
"Uppsala, Uppsala, Kronoberg, Orebro, Sweden",
"",
"Woodbridge, Middlesex County, New Jersey, US",
"",
"Stony Brook, Middlesex County, New Jersey",
"Stony Brook, Middlesex County, New Jersey",
"Woodbridge, Middlesex, New Jersey, United States",
"Woodbridge, Middlesex, New Jersey, United States",
"Stony Brook, Middlesex County, New Jersey",
"Woodbridge, Middlesex, New Jersey, United States",
"Piscataway, Middlesex, New Jersey, United States",
"Piscataway, Middlesex County, New Jersey",
"Derby, Derbyshire, England",
"Kings County (Brooklyn), New York, United States of America",
"Bound Brook, Somerset, New Jersey, USA",
"Derby, England",
"Derby, Derbyshire, England",
"Bound Brook, Somerset, New Jersey, USA",
"Derby, Derbyshire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Cape May, New Jersey, USA",
"Baltimore, Maryland, USA",
"Boston, Suffolk, Massachusetts, USA",
"",
"Wessex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Italy",
"New Jersey",
"New Jersey",
"",
"New York",
"",
"Chesham, Buckinghamshire, England",
"Bycot, Oxforshire",
"Hillesden, Buckinghamshire, England",
"",
"",
"Bronscroft, Shropshire, England",
"bromscraft, England",
"bromscraft, England",
"Staffordshire, England",
"Skelton In Cleveland, Yorkshire, England",
"Haughton, Staffordshire, , England",
"",
"Bulmer, Essex, England",
"Little Egg Harbor, Ocean, New Jersey, United States",
"Little Egg Harb, Burlington, New Jersey, United States",
"Hanes Greane, Bawtry, Nottinghamshire, England",
"Great Drayton, Nottinghamshire, , England",
"",
"",
"",
"Bayonne, Departement des Pyr\u00e9n\u00e9es-Atlantiques, Aquitaine, France",
"Bayonne, Departement des Pyr\u00e9n\u00e9es-Atlantiques, Aquitaine, France",
"",
"",
"London, City of London, Greater London, England",
"",
"",
"",
"Rhuddlan, Denbighshire, Wales",
"Rhuddlan, Denbighshire, Wales",
"",
"",
"",
"",
"",
"Windsor, Windsor and Maidenhead Royal Borough, Berkshire, England",
"",
"",
"England",
"Oxfordshire, England",
"Brotherton, Selby District, North Yorkshire, England",
"Brotherton, Selby District, North Yorkshire, England",
"Woodstock, West Oxfordshire District, Oxfordshire, England",
"AnjouPays-de-la-Loire, France",
"Firle, Sussex, England",
"Bolney, Sussex, England",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Watford, Hertfordshire, England",
"Deddington, Oxfordshire, England",
"Bavaria, , Bayern, Germany",
"M\u00fcnchen, M\u00fcnchen, Oberbayern, Bayern, Germany",
"Brooklyn, New York",
"Nord-Pas-de-Calais, France",
"Nord-Pas-de-Calais, France",
"",
"Gloustershire, England",
"",
"",
"",
"",
"",
"",
"",
"",
"Argyll, Scotland",
"",
"",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"Kirkton of Auchterhouse, Forfarshire Aberdeenshire, Scotland",
"",
"",
"Pennsylvania",
"",
"Freehold, Monmouth, New Jersey, United States",
"Saint Cuthberts, Edinburgh, Midlothian, Scotland",
"Niddrew Castle, Dunbartonshire, Scotland",
"Niddry, West Lothian, Scotland",
"Kirkintilloch, Dunbartonshire, Scotland",
"",
"Rennes, Ille-et-Vilaine, Bretagne, France",
"lived Suffolk, England",
"Hundon, Suffolk, England",
"Hundon, Suffolk, England",
"England",
"Rishangles, Suffolk, England",
"",
"",
"Derby, Derbyshire, England",
"",
"Derby, Derbyshire, England",
"Derby, Derbyshire, England",
"",
"",
"Derby, Derbyshire, England",
"",
"",
"Pennsylvania",
"Italy",
"Stanstede, Kent, England UK ",
"Stirling, Stirlingshire, Scotland",
"Stirling, Stirlingshire, Scotland",
"Cumberland, New Jersey, United States",
"Beaudefert, Staffordshire, England",
"",
"",
"Oxfordshire, England",
"",
"",
"Gloucester, Essex, Massachusetts, USA",
"Gloucester, Essex, Massachusetts, USA",
"",
"Woodthorpe, Staveley, Derbyshire, Kingdom of England",
"Staveley, Derbyshire, Kingdom of England",
"",
"Thueringen, Germany",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Ireland",
"Giradow, Poland",
"",
"Fearn, Ross-shire, Scotland",
"",
"Ross Cromarty, Scotland",
"",
"",
"",
"",
"",
"Pennsylvania",
"Philadelphia, Pennsylvania USA",
"Pennsylvania, USA",
"Woodbury, New Jersey, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"Camden, New Jersey, United States",
"Philadelphia, PA, United States",
"Abington Hospital",
"Philadelphia, Pennsylvania, United States",
"",
"",
"Pennsylvania",
"Woodbury, New Jersey, United States",
"",
"Colorado Springs, El Paso County, CO, United States",
"",
"",
"",
"Philadelphia, Pennsylvania, USA",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"Chicago, Cook County, Illinois, United States",
"",
"Camden, NJ, United States",
"Pennsylvania, USA",
"",
"",
"Nashua, New Hampshire, United States",
"Ferbane, County Offaly or Pollagh, Galway, Ireland",
"Woodbury, New Jersey, United States",
"",
"",
"",
"",
"",
"Phiadelphia, United States",
"Philadelphia, Pennsylvania",
"",
"",
"",
"Naperville, IL, United States",
"",
"Woodbury, New Jersey, United States",
"",
"",
"",
"",
"Ireland",
"",
"",
"Camden, NJ",
"",
"Pennsylvania",
"KIngs Co. Offaly, Ireland",
"Darby, Delaware, PA, United States",
"",
"",
"Pennsylvania",
"Pennsylvania",
"",
"",
"",
"",
"",
"Pennsylvania",
"",
"Burbank, LA, California, United States",
"",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"Glenside, Montgomery, Pennsylvania, United States",
"",
"",
"",
"",
"Collingswood, NJ",
"",
"",
"",
"New Jersey, United States",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"Pennsylvania, United States",
"Philadelphia City, Philadelphia, Pennsylvania",
"Pennsylvania",
"Pennsylvania, United States",
"Pennsylvania, USA",
"Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"England",
"England",
"Ulcombe, Kent, England",
"England",
"",
"Ulcombe, Maidstone Borough, Kent, England",
"",
"Niddry Castle, Midlothian, Scotland",
"Niddrew Castle, Edinburgh, Scotland",
"New York",
"",
"England ",
"",
"Pennsylvania",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Uitikon, Zurich, Switzerland",
"Uitikon, Z\u00fcrich, Switzerland",
"Pennsylvania",
"Pennsylvania",
"Mertztown, Berk County, Pennsylvania",
"Pennsylvania, USA",
"Pennsylvania",
"Philadelphia City, Philadelphia, Pennsylvania",
"Pennsylvania",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Phila, Pennsylvania",
"",
"",
"",
"West Creek, Ocean, New Jersey, USA",
"Little Egg Harbor, Ocean, New Jersey, United States",
"Stafford, Monmouth, New Jersey, United States",
"Bulmer, Essex, England",
"Springfield,Hampden,Massachusetts, USA",
"West Creek, Ocean, New Jersey, USA",
"Hempstead, LI, New York, United States",
"Bulmer, Essex, England",
"Bulmer, Essex, England",
"Little Egg Harbor Twp, Burlington County, NJ",
"Hempstead, LI, New York, United States",
"Little Egg Harbor, Ocean, New Jersey, USA",
"West Creek, Ocean, New Jersey, USA",
"Hempstead, LI, New York, USA",
"Nassau, Livingston, New York, United States",
"West Creek, Ocean, New Jersey, United States",
"Hempstead, LI, New York, United States",
"",
"West Creek, Ocean, New Jersey, USA",
"Little Egg Harbor, Ocean, New Jersey, United States",
"Hempstead, Nassau, Long Island, New York, United States",
"",
"Hempstead, Nassau, New York, USA",
"Plantfield, Essex, England",
"Yeldham or Chelmsford, Essex, England",
"Hempstead, Long Island, New York, USA",
"Hempstead, Queens, New York, United States",
"Hempstead, Nassau, New York, USA",
"Long Island City, Queens, New York, United States",
"Long Island City, Queens, New York",
"Long Island City, Queens, New York, United States",
"",
"Hempstead, Nassau, New York, USA",
"West Creek, Ocean, New Jersey, USA",
"Hempstead, Nassau, New York, United States",
"",
"West Creek, Ocean, New Jersey, USA",
"",
"Weedon, Buckinghamshire, England",
"Long Island City, Queens, New York, United States",
"Tuckerton, Ocean, New Jersey",
"West Creek, Ocean, New Jersey, USA",
"Bulmer, Essex, England",
"Hempstead, Queens, New York, United States",
"",
"West Creek, Ocean, New Jersey, USA",
"",
"West Creek, Ocean, New Jersey",
"Bulmer, Essex, England",
"Bulmer, Essex, England",
"Bulmer, Essex, England",
"Bulmer, Essex, England",
"Parish, Essex, England",
"",
"Beaugency, Loiret, Centre, France",
"Montfort, lAmaury, Yvelines, \u00cele-de-France, France",
"Newport, Shropshire, England",
"",
"",
"",
"",
"",
"",
"",
"Leptis Magna, Africa",
"",
"",
"Ardeley, Hertfordshire, England",
"Derby, Derbyshire, England",
"Scotland",
"Balgonie, Scotland",
"",
"Tunbridge, Kent, , England",
"Camden, Camden, New Jersey, USA",
"Camden, Camden, New Jersey, USA",
"pa",
"Pennsylvania",
"New Jersey",
"New Jersey",
"Pennsylvania",
"New Jersey, United States",
"Pennsylvania",
"",
"",
"",
"Camden County, New Jersey, USA",
"",
"Pennsylvania",
"New Jersey",
"New Jersey",
"",
"",
"New Jersey",
"New Jersey",
"Camden, New Jersey",
"",
"",
"Westville, Gloucester, New Jersey, USA",
"New Jersey",
"Egg Harbor, Cape May, New Jersey, United States",
"",
"",
"",
"Tilstock, Shropshire, England",
"Owlpen, Gloustershire, England",
"Owlpen, Gloustershire, England",
"England",
"England",
"Herefordshire, England",
"Philadelphia County, Pennsylvania, United States of America",
"Philadelphia, PA",
"Devon, England",
"England",
"Lapford, Devon, England",
"Devonshire, England",
"Woodlynne, Camden, New Jersey, USA",
"Philadelphia, Philadelphia, Pennsylvania, USA",
"Russia",
"",
"Woodlynne CA, New Jersey",
"Woodlynne, Camden, New Jersey, USA",
"",
"",
"Pennsylvania",
"Morvern, Argyll, Scotland",
"Finlaggan Castle, Isle of Islay, Argyll, Scotland",
"Morven, Argyll, Scotland",
"Swallowcliffe, Wiltshire, England",
"Swallowcliffe, Wiltshire, England",
"Derby, Derbyshire, England",
"Castle Donington, Leicestershire, England",
"All Saints, Derby, Derbyshire, England",
"Castle Donington, Leicestershire, England",
"",
"Diseworth, Leichester, England",
"Diseworth, Leichester, England",
"Derby, Derbyshire, England",
"",
"Pittsgrove, Salem, New Jersey, USA",
"Fareham, Hampshire, England",
"Salem, Salem, New Jersey",
"Pittsgrove, Salem, New Jersey, USA",
"",
"Egg Harbor City, Atlantic, New Jersey, USA",
"New Jersey, USA",
"New Jersey, Monmouth, New Jersey, United States",
"Halland, J\u00e4mtland, Sweden",
"",
"Ulcombe, Kent, England",
"Leeds Castle, Canon Court Manor, Ulcombe, Kent, England",
"Pleshey, Chelmsford Borough, Essex, England",
"Banbury, Oxfordshire, England",
"Brough Castle, Westmoreland, England",
"",
"",
"",
"",
"",
"",
"Huntingdon, Huntingdonshire, England",
"Dunfermline Abbey",
"Holyrood, Palace, Edinburgh, Midlothian, Scotland",
"",
"scotland",
"",
"Stirling Castle, Scotland",
"Bute, Scotland",
"Paisley, Abbey, Renfrewshire, Scotland",
"Innermeath,, Scotland",
"",
"",
"Long Island, New York, United States",
"",
"Thursley, Surrey, England",
"Perth, Perthshire, , Scotland",
"",
"Glenkindle, House, Aberdeen, Aberdeenshire, Scotland",
"",
"scotland",
"Hempstead, Nassau, New York, United States",
"England",
"Ermington, Devon, England",
"Plympton St Mary, Devon, England",
"Plymouth, Devon, England",
"Newnham Manor, Plympton St Mary, Devon, England",
"Plymouth, Devon, England",
"Plympton St Mary, Devon, England",
"Newenham, Devon, England",
"Lamborne Wodlnds,Berkshire Parish,Wiltshire,England",
"Lamborne Wodlnds,Berkshire Parish,Wiltshire,England",
"Lamborne Wodlnds,Berkshire Parish,Wiltshire,England",
"Uppsala, Sweden",
"",
"",
"",
"",
"",
"",
"Hitcham, England",
"England",
"New Haven, New Haven County, Connecticut, USA",
"",
"",
"East Hampton, Suffolk County, New York, USA",
"",
"Southampton, Suffolk County, New York, USA",
"Wherwell, Hampshire, , England",
"",
"Hambleton, Rutland, England",
"",
"Camden, Camden, New Jersey, United States",
"",
"",
"",
"",
"",
"",
"Tunbridge, Kent, England",
"",
"",
"",
"Berks County, Pennsylvania, USA",
"Stratford, Fairfield, Connecticut Colony",
"Maryland",
"Uppsala, Sweden",
"Uppsala, Sweden",
"",
"",
"Gloucestershire, England",
"Bengeworth, Worcestershire, England",
"",
"Preston-on-Stour, Gloucestershire, England",
"Preston on Stour, Gloucestershire, England",
"Virginia",
"",
"",
"Poitiers, Vienne, Poitou-Charentes, France",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Pembroke Castle, Pembrokeshire, Wales",
"",
"Derby, Derbyshire, England",
"Derby, Derbyshire, England",
"Wales",
"Tynedale, East Lothian, Scotland",
"",
"Orleans, Loiret, Centre, France",
"Lancaster, City of Lancaster, Lancashire, England",
"Neckartailfingen, Germany",
"",
"Thewbourough, Devonshire, England",
"Thewborough, Devon, England",
"",
"",
"",
"",
"Cibalis Pannonie",
"",
"",
"",
"",
"",
"",
"Lorraine, France",
"Arkel, Z-H, Holland, Netherlands",
"Arkel, Z-H, Holland, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"Pierrepont, 54, Briey, Meurthe-et-Moselle, Lorraine, France",
"",
"",
"",
"",
"",
"",
"langerak, Z-H Holland, Netherlands",
"",
"",
"",
"",
"Egmond, Noord-Holland, Netherlands",
"",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Nordhausen, Saxony, Prussia, Germany",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Vascoeuiil, Seine Inferieure, Normandy, France",
"Dublin, Dublin, Ireland",
"Meath, Leinster, Ireland",
"Monfort, Normandy, France",
"Bedford, Bedfordshire, England",
"Thornbury, Chester, Pennsylvania, United States",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Orleans, Loiret, Centre, France",
"Orleans, Loiret, Centre, France",
"",
"",
"",
"Slot O Hoef, Netherlands",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Longtown, City of Carlisle, Cumbria, England",
"Bures St Mary, Suffolk, England",
"",
"England",
"",
"Kent, England",
"",
"Virginia, United States",
"Walton, Lancashire,  England",
"wamanoag, village, Massachusetts Bay Colony, Colonial, America",
"",
"Wamonoag, Village, MassachusettsBay Colony, Colonial, USA",
"wampanoag, village, Yarmouth, Barnstable, Massachusetts, USA",
"Rolvenden, Kent, England",
"Horsham, Sussex, England",
"Pokanoket Village, Massachusetts, USA",
"",
"Bengeworth, Worcestershire, England",
"Worcester, Worcestershire, England",
"Bengeworth, Worcestershire, England",
"Hempstead, Nassau, New York, United States",
"Bengeworth, Worcestershire, England",
"Bengeworth, Worcestershire, England",
"Bengeworth, Worchester, England, England",
"Evesham, Worcestershire, England",
"Bengeworth, Worcestershire, England",
"Bengeworth, Evesham, Worcester, England",
"",
"Bengeworth, Worcestershire, England",
"",
"Bengeworth, Evesham, Worcestershire, England",
"Westbury, Nassau, New York, United States",
"Bengeworth, Evesham, Worcester, England",
"Greenwich, Gloucester, New Jersey, United States",
"Greenwich, Gloucester, NJ",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Wessex, England",
"Wantage, Oxfordshire, England",
"",
"Imperial Frankish Court in Aachen",
"",
"",
"",
"",
"",
"basford, Nottingham, Nottinghamshire, England",
"Arnold, Nottinghamshire, England",
"basford, Nottingham, Nottinghamshire, England",
"Arnold, Nottinghamshire, England",
"",
"Raffin, Meath, Ireland",
"West Yarmouth, Barnstable, Massachusetts, United States",
"Plymouth, Massachusetts",
"Yarmouth, Barnstable, Massachusetts, USA",
"",
"",
"",
"Peckham, Kent, England",
"Bengeworth, Worcestershire, England",
"West Titherlay, Hertfordshire, England",
"",
"of Hartford, Hartford, CT",
"Southampton, Livingston, New York, United States",
"",
"",
"",
"",
"",
"",
"West, Wiltshire, England",
"",
"",
"Philadelphia, PA",
"Camden, Camden, New Jersey, USA",
"",
"Pennsylvania",
"Nottingham, Chester, Pennsylvania, United States",
"",
"PA",
"",
"",
"Philadelphia, PA",
"",
"",
"Hempstead, Nassau, New York, United States",
"Philadelphia, PA",
"Pennsylvania",
"",
"",
"",
"Philadelphia, PA",
"Pennsylvania",
"Pennsylvania",
"Pennsylvania",
"Phiadelphia, PA",
"Pennsylvania",
"Philadelphia, PA",
"New Jersey",
"Long Island City, Queens, New York, USA",
"Chepstow Wales",
"Philadelphia, PA",
"Philadelphia, Philadelphia, Pennsylvania, United States",
"",
"Pennsylvania",
"Philadelphia, PA",
"New Jersey",
"Kaighn Point, Camden, NJ",
"",
"Edgmont, Chester, Pennsylvania, USA",
"Newton, Chester, PA",
"Hempstead, Long Island, Kings, NY",
"Hempstead, Nassau, Long Island, New York, United States",
"Bedford, Bedfordshire, England",
"lived Suffolk, England",
"Bengeworth, Worcestershire, England",
"Wincanton, Somerset, , England",
"Brasenhill, Cheshire, England",
"of Scituate, Plymouth, MA",
"Lynn, Essex County, Massachusetts, USA",
"Pennsylvania",
"Pennsylvania",
"Clayton, Gloucester, New Jersey, USA",
"New Jersey, USA",
"",
"Tilstock, Shropshire, England",
"Lancashire, England",
"Shavington, Cheshire, England",
"Upton, Buckinghamshire, England",
"Upton, Buckinghamshire, England",
"Upton, Buckinghamshire, England",
"Wilby, Mid Suffolk District, Suffolk, England",
"Haughton, Staffordshire, , England",
"Haughton, Staffordshire, England",
"Haughton, Staffordshire, England",
"Dilhorne, Staffordshire, England",
"Haughton, Staffordshire, , England",
"",
"",
"",
"Tullamore, Kerry, Ireland",
"",
"Philadelphia, Pennsylvania, USA",
"",
"Crewkerne, Somerset, England",
"Pennsylvania",
"",
"Pottstown, Montgomery, Pennsylvania, USA",
"",
"",
"Douglass Twp., Berks Co., PA",
"",
"Douglass Township, Berks, Pennsylvania, USA",
"Douglass Twp, Berks Co, PA",
"Douglass Twp., Berks Co., PA",
"Douglass Twp., Berks Co., PA",
"",
"",
"Douglass Twp., Berks Co., PA",
"",
"Douglass Twp., Berks Co., PA",
"Douglass Twp., Berks Co., PA",
"Longswamp, Berks County, Pennsylvania, United States of America",
"Germany",
"Pennsylvania, USA",
"Mertztown, Berks County, Pennsylvania, United States of America",
"Berks County, Pennsylvania, United States of America",
"Montgomery County, Pennsylvania, USA",
"State College, Centre, Pennsylvania, USA",
"",
"",
"",
"",
"",
"",
"North Molton, North Devon District, Devon, England"
]
Dwr.ScriptLoaded('dwr_db_I_birth_place_0.js');
